### ISSUE TITLE
Comments: user redirected to `example.com`

### ISSUE THREAD

**Issue by isedwards** [unicef/iogt#102]
When testing comments with a fresh deployment (i.e. dropping my database), I have the same issue that @istride mentioned in https://github.com/unicef/iogt/pull/81#pullrequestreview-677208727: When I type in a comment and click send the page reload substitutes `example.com` as the site's domain name.

The issue appears to be related to the difference between Django and Wagtail handling of multi-sites (see [here](https://stackoverflow.com/questions/67495411/)) - and may be limited to the case where we only have one site set up.

**Comment by ehmadzubair** [comment]
@isedwards The initial data command has been updated in #81 to mitigate this issue. Did you run `python manage.py create_initial_data`? That should have called the other management command named `create_default_site` which updates or creates the Site object.

**Comment by sheralim012** [comment]
@ChrisMarsh82 this is done and you can close this.
