### ISSUE TITLE
Add method for navigating to Menu (ie section list) on mobile

### ISSUE THREAD

**Issue by cbunicef** [unicef/iogt#1029]
As a MOBILE USER I want to be able to easily get to the navigation menu on the website. 

Currently the navigation is below all content, including on the homepage, and we don't have support for a Flat Menu button that either 1) expands from the Flat Menu to list top-level sections 2) clicks to a list of top-level sections.

The simplest possible solution may be adding an HTML anchor at the top of the navigation menu, and using a Flat Menu button to link to that anchor. This doesn't work well on desktop, but solves the problem on mobile platforms.

**Comment by geoo89** [comment]
Resolution:

Two stages (please comment on how difficult they are to implement, we can defer (2) to later if it's complicated):

1. Replicate the v1 functionality in **single-column view only**: (see ![image](https://user-images.githubusercontent.com/678199/150389751-35db8390-0c23-4a01-9d8b-12bee10d31de.png) )
    - Add a menu button using `iogt/static/icons/burger.svg` next to search icon in the header (here: ![image](https://user-images.githubusercontent.com/678199/150389885-a184b160-8d4d-44fe-a3b7-3152dcb82946.png) )
    - For column width < 280px, it might not fit; in that case replace the search button with the menu button.
    - Add an anchor before the row with second instance of the language picker (i.e. just before here
![image](https://user-images.githubusercontent.com/678199/150390324-9b8504f0-d137-4479-a2bb-f6d8d4a439eb.png) ). Pressing the menu button should take you to that anchor on the page (so you see the language picker, search bar, top-level sections/footers).
2. Allow replicating this functionality via flat menus
    - Allow to reference the anchor also in flat menus (maybe by specifying `#menu` as the URL?)
    - Add a checkbox for flat menu items "Only display in single column view"
    - Somewhere in the CMS add a setting where it's possible to enable/disable the menu button from point 1.

**Comment by geoo89** [comment]
Note: In the future #573 might make this redundant.

**Comment by cbunicef** [comment]
I think we can already add anchors eg `#menu` to URLs in Flat Menus:

![image](https://user-images.githubusercontent.com/30042226/150511457-1074a655-03a7-4ce8-8945-f3564bee2bff.png)
