### ISSUE TITLE
Inconsistent section card scaling 

### ISSUE THREAD

**Issue by geoo89** [unicef/iogt#1032]
At wide resolutions:
![image](https://user-images.githubusercontent.com/678199/150394409-1e2ae02b-259a-4a57-9a21-fbb0de07e9cd.png)

At narrow resolution (here: 360px column width): Images are displayed at different widths.
![image](https://user-images.githubusercontent.com/678199/150394942-28c5b3fe-4f88-46c3-a38c-cbf130cee18c.png)

What determines this?

**Comment by cbunicef** [comment]
Moving this up in priority as it really distracts from a new piece of content we've created, and hopefully it is not too difficult.

It looks like eg the `<p>` tag on the title for sub-section cards is lacking a class. Hopefully much of the problem's resolution can come from the article cards css.
