### ISSUE TITLE
Image size in the thank you page of the quiz Make the Plastic Tide Turners Pledge

### ISSUE THREAD

**Issue by micheladegiusti** [unicef/iogt#1044]
On a computer screen, after you submit the "Make the Plastic Tide Turners Pledge" you're redirected to the Thank you page where the following picture 
![image](https://user-images.githubusercontent.com/98154212/150677693-31004702-102a-4fcc-b075-32b88d09e9e3.png)
 appears in a odd shape. 
The text "You did it! Thank you for signing the Plastic Tide Turners Pledge. If you haven't already, check out these important activities to reduce plastic use in your community: How to: Reduce your Plastic Consumption, Activities at Home, Activities in the Community,
Start a Climate Campaign" appears all in small characters, so from an user point of view the all page looks not quite right.
The same goes if I do it from a phone. The image is elongated and looks not quite right.

**Comment by ChrisMarsh82** [comment]
@micheladegiusti Can you add a link to the page?

**Comment by micheladegiusti** [comment]
https://global.iogt.site/en/sections/youth/climate-change/take-the-plastic-challenge/make-the-plastic-tide-turners-pledge/ for the quiz, and after submitting it it takes me to this page:

https://global.iogt.site/en/sections/youth/climate-change/take-the-plastic-challenge/make-the-plastic-tide-turners-pledge/?back_url=/en/sections/youth/climate-change/take-the-plastic-challenge/make-the-plastic-tide-turners-pledge/&form_length=4

**Comment by micheladegiusti** [comment]
I have difficulties in adding a screenshot at the moment..

**Comment by micheladegiusti** [comment]
<img width="960" alt="image" src="https://user-images.githubusercontent.com/98154212/150756415-93c5f3ce-e127-4c75-961d-a3c1d36cbbfe.png">

**Comment by micheladegiusti** [comment]
This happens also when I do it on the phone

**Comment by geoo89** [comment]
It appears that this got fixed via #1040
