### ISSUE TITLE
Missing Scenario

### ISSUE THREAD

**Issue by micheladegiusti** [unicef/iogt#1050]
On https://global.iogt.site/en/sections/youth/your-health/sexual-health/all-about-hiv/ there's no HIV scenario or options to "What should Teresa do?"

<img width="439" alt="image" src="https://user-images.githubusercontent.com/98154212/150784551-8862502b-de39-4fab-a8ec-252d2d7a8b22.png">
 
Only by clicking on the choice dot and then on the submit button you are taken to the scenario page, but still no options to choose from: 
https://global.iogt.site/en/sections/youth/your-health/sexual-health/all-about-hiv/hiv-scenario-quiz/?back_url=/en/sections/youth/your-health/sexual-health/all-about-hiv/&form_length=1

<img width="419" alt="image" src="https://user-images.githubusercontent.com/98154212/150785151-0028472f-5b64-4e28-94bd-06c0663f9f84.png">

**Comment by micheladegiusti** [comment]
Same as before, also in https://global.iogt.site/en/sections/youth/your-health/sexual-health/sex-and-other-stuff/ the consent scenario is missing too, we've got just the questions with the options. Only when I answer the quiz do I get to see the scenario

![image](https://user-images.githubusercontent.com/98154212/150788951-832a433a-6b17-4c45-9bdc-fc60da01a7cc.png)

**Comment by cbunicef** [comment]
The missing scenarios should be resolved when the update with the PR resolving #977 is pushed to this platform.

The lack of choices on the first question was an entry error, but #1053 should help prevent this in the future.

Thanks @micheladegiusti !
