### ISSUE TITLE
Inconsistency in the way the end page surveys are displayed

### ISSUE THREAD

**Issue by micheladegiusti** [unicef/iogt#1052]
In https://global.iogt.site/en/sections/youth/your-health/mental-health/understanding-mental-health/ the "Was this mental health information helpful" survey is displayed at the end of the page

![image](https://user-images.githubusercontent.com/98154212/150786956-a9c86159-6ca5-48e9-be6e-c343d950ed56.png)

 while in https://global.iogt.site/en/sections/youth/your-health/mental-health/keeping-mentally-healthy-self-care-tips/ clicking on the survey banner the survey is displayed on a different page

![image](https://user-images.githubusercontent.com/98154212/150787130-4f73ba16-e3b5-4179-ba3f-360b39c66159.png)

as same as in https://global.iogt.site/en/sections/youth/your-health/mental-health/keeping-mentally-healthy-self-care-tips/breathing-exercises/ and for the HIV page in https://global.iogt.site/en/sections/youth/hidden-surveys/was-this-hiv-information-helpful/

**Comment by cbunicef** [comment]
Thanks @micheladegiusti. These are implemented differently in the Admin Panel, so they are showing correctly even though they are not showing the same way.

**Comment by micheladegiusti** [comment]
The same actually happens on https://global.iogt.site/en/sections/youth/your-health/sexual-health/pregnancy/ 
with the survey questions at the end of the page 

![image](https://user-images.githubusercontent.com/98154212/150788363-bd26bdc8-aa10-4ac5-b9bc-364fbc4f87f1.png)

**Comment by micheladegiusti** [comment]
I see @cbunicef many thanks!
