### ISSUE TITLE
End of word missing

### ISSUE THREAD

**Issue by micheladegiusti** [unicef/iogt#1054]
in https://global.iogt.site/en/sections/youth/your-health/mental-health/stress-and-me/being-a-young-parent/young-parents-scenario/ in the quiz answer the last word miss the last two letters "Ani is in a difficult situation and she should feel safe and that her baby is getting the best care. She should not be pressured to give up breastfeeding nor should she have to suffer insults and blame. It is important that Ani gets some support for herse"

![image](https://user-images.githubusercontent.com/98154212/150792088-5ee7bf1f-c1d7-4bc7-96d1-713d4de5825d.png)

**Comment by cbunicef** [comment]
This is related to #954. This is a quiz Feedback field, and right now it's limited to 255 characters. It looks like when content is pasted it's cut off where the length is longer than 255.

@lauriemarkle could you please just the text here to fit 255?

**Comment by lauriemarkle** [comment]
> This is related to #954. This is a quiz Feedback field, and right now it's limited to 255 characters. It looks like when content is pasted it's cut off where the length is longer than 255.
> 
> @lauriemarkle could you please adjust the text here to fit 255?

@cbunicef Done!
