### ISSUE TITLE
Creating array of resources that should be cached available to serviceworker

### ISSUE THREAD

**Issue by Kishokanth-netizen** [unicef/iogt#108]
The current implementation to precache resources which we deem necessary is as below 
![image](https://user-images.githubusercontent.com/80698644/121650924-600a6380-ca9a-11eb-82d6-ae1328c5e9b2.png)

As discussed with @ehmadzubair, since the content on the app is dynamic, we would need to find a way access these resources dynamically. Ehmad suggested an interesting way to action this using a sitemap related implementation.

**Comment by dannyparsons** [comment]
Related to #67

**Comment by sheralim012** [comment]
@ChrisMarsh82 this is done and you can close this.
