### ISSUE TITLE
WagtailTransfer: images not transferred

### ISSUE THREAD

**Issue by istride** [unicef/iogt#1084]
Images are not being transferred when transferring articles from the Global site. The article itself is transferred, but there are issues with images, including:

- references to images are not transferred with the article i.e. null reference
- references to images in articles are transferred, along with database entry for the image, but the image file is missing

An error occurs when trying to view the transferred article in the admin. For example, after transferring the article called 'Myths' from Global:

```
ValueError: The 'file' attribute has no file associated with it.
```
Full stacktrace provided below.

**Comment by istride** [comment]
[wagtailtransfer_image-no-file-attribute.txt](https://github.com/unicef/iogt/files/7971696/wagtailtransfer_image-no-file-attribute.txt)

**Comment by sheralim012** [comment]
to fix svg import kindly add ‘wagtailsvg.svg’ in setting WAGTAILTRANSFER_UPDATE_RELATED_MODELS
