### ISSUE TITLE
During migration, move List blocks to lists in Paragraph blocks

### ISSUE THREAD

**Issue by cbunicef** [unicef/iogt#1087]
List blocks in V1 are a compact list of single-row fields for markdown entry.

![image](https://user-images.githubusercontent.com/30042226/151829070-4f0dc0a3-fd55-48eb-8652-ab670fbd113d.png)

List blocks in V2 are a very long list of large fields for markdown entry.

![image](https://user-images.githubusercontent.com/30042226/151829170-35455a8a-f7b4-4054-9423-e7ae4432cee6.png)

It would be better to migrate List blocks to Paragraph blocks which are easier to manage:

![image](https://user-images.githubusercontent.com/30042226/151829433-033e8348-e587-4788-9e83-621f1aa8b089.png)

**Comment by cbunicef** [comment]
@geoo89 please size this one. If this can be done quickly let's do it immediately after wagtail-transfer. Otherwise we'll push back.

@lauriemarkle

**Comment by geoo89** [comment]
List blocks used to be small, but then we had to support Markdown inside list blocks as it was supported in V1.
We could also investigate whether we could simplify the input interface, so that any Markdown/HTML has to be entered manually.
If that's possible, that seems like a safer option to me at this point.

**Comment by cbunicef** [comment]
Just to be clear from my side, I don't mind waiting a bit to adjust the List blocks input, as the Paragraph list is a perfectly good alternative - if we can migrate the V1 Lists to Paragraph.

But if you're saying it will be tricky to properly do that migration, then yes let's work with the interface.

I would also be happy with the Markdown blocks within List blocks to have 1-line long text fields by default with a draggable field size eg as in GitHub comments:

![image](https://user-images.githubusercontent.com/30042226/151955114-3ccc7b22-eb0c-4b8f-846d-7385890fcde9.png)

If that's possible we could keep the normal Markdown block interface with the tools.

**Comment by cbunicef** [comment]
@geoo89 If this can't be done simply let's push to the next release.

**Comment by sheralim012** [comment]
* it is easy to update content migration to migrate v1-list to v2-(paragraph/markdown) (small size)
* changing UI will require overriding wagtail's richtail editor which could be quite complex and could cause issue when we update wagtail version (large size)

also v1-list was written in markdown style (e.g., https://rke-iogt.unicef.io/admin/pages/483/edit/ list item has URL embedded URL) and it would be better if we migrate v1-list as v2-markdown.

**Comment by cbunicef** [comment]
So the easiest way to address this is to migrate the v1-list to v2-markdown as a list of items? That is fine with me.

**Comment by geoo89** [comment]
I noticed that the line spacing is different between list elements and lists in a single content block (e.g. in markdown blocks).
Example below shows list first, then list within markdown block:

![image](https://user-images.githubusercontent.com/678199/152183511-4276d03a-f953-425f-bbe3-e183496c6c70.png)

I assume this difference is acceptable (the appearance in V1 likely is yet slightly different anyway)?

**Comment by cbunicef** [comment]
@lauriemarkle I wouldn't anticipate this to be a problem, but what do you think?
