### ISSUE TITLE
Radio buttons in Forms are different sizes in browsers on iOS

### ISSUE THREAD

**Issue by cbunicef** [unicef/iogt#1089]
![image](https://user-images.githubusercontent.com/30042226/151953446-cdd60aff-af87-4fa1-9fe4-13250a303c6e.png)

I've viewed this in Safari and Firefox, but I think this would be the same for all browsers on iOS as Apple requires rendering with Webkit

https://developer.apple.com/app-store/review/guidelines/
![image](https://user-images.githubusercontent.com/30042226/151953762-2f18e22b-449e-48c5-9655-eeb00132336c.png)

The text of the radio buttons is still clickable so functionality isn't broken.

**Comment by cbunicef** [comment]
This is not an issue visible in any PC-based browser I've tried including when viewing at narrow screen width. @lauriemarkle could you check in Safari on your Mac?

**Comment by sheralim012** [comment]
I have tried but couldn't reproduce this on the following devices
- MacBook Pro: chrome, brave, safari, firefox
- iPhone: chrome, brave, safari
- iPad: chrome, safari

all had the latest versions

also, I noticed we haven't specified the min-width for the checkbox and radio and simply specifying that will mitigate this shrinking of these inputs

**Comment by cbunicef** [comment]
Strange, I'm still seeing it, but not in all locations. Here are some examples where I see it:

https://global.iogt.site/en/sections/youth/climate-change/take-the-plastic-challenge/make-the-plastic-tide-turners-pledge/
https://global.iogt.site/en/sections/youth/your-health/mental-health/understanding-mental-health/mental-health-trivia/ (in later questions)
