### ISSUE TITLE
Registration survey submissions not displayed

### ISSUE THREAD

**Issue by geoo89** [unicef/iogt#1097]
It appears when the main site language is not English, the migrated V1 registration survey form data is not displayed in the form data tab (instead, it is filled with None for each field), e.g. https://ec.iogt.site/admin/forms/submissions/165/

The data is still available however: When exporting users, the last column contains the registration survey data.

I checked that the admin labels in the survey questions are matching the stored data, so I'm not sure what causes this.

**Comment by cbunicef** [comment]
I recommend that we close this issue due to #1102
