### ISSUE TITLE
RapidPro setup is tricky

### ISSUE THREAD

**Issue by istride** [unicef/iogt#1109]
The [current process for setting up the RapidPro integration][1] is a little bit cumbersome as it requires:

- setting username and password for the RapidPro chatbot user as environment variables
- running a script to create the chatbot user, using the env vars
- setting the user id of the chatbot user as an environment variable, so the app can identify the chatbot user

One suggestion would be to use user groups to designate the RapidPro chatbot user. The set up would then consist of running a setup script. The script itself would do the following:

- create group 'iogt_rapidpro_chatbot'
- create user (with auto-generated username & password)
- add user to group

Then, to identify the chatbot user, the app would get all users in the chatbot group, sorted by name, and take the top result (just in case there are multiple).

This would eliminate the need for env vars, making the setup process less prone to human error and possible for an app admin to do as there would be no need to set the designated chatbot user id as an env var (which can only be done by a system / infrastructure admin)

[1]: https://github.com/unicef/iogt/blob/develop/messaging/README.md#technical-set-up

**Comment by ehmadzubair** [comment]
I'm working on this

**Comment by sheralim012** [comment]
@istride if we hardcode the rapidpro username and use that single user to communicate with rapidpro server then we wouldn't have to create group and manage multiple rapidpro users, is it ok?

**Comment by istride** [comment]
The script should make it convenient for a RapidPro bot user to be created when we create a new site, but I don't want it to be the only way that such a user could be created. I think it would be beneficial for a wagtail admin to be able to set up the chat bot user manually, if necessary, rather than wait for someone to run the script again.

Perhaps there is a better way to designate the chat bot user than using a group, this is merely my suggestion. I think the group helps wagtail admins to more easily identify the chat bot user and allows any user to become the chat bot - so it is more like a role that users may have - and we don't need to care about which username is used. Currently, we only want to allow one chat bot user, so we would have to find a way to enforce that.

I am assuming that this would not be a difficult thing to achieve, that it would be worth doing for the reasons above, and would give us an option in the future to support multiple chat bot users (whatever that is worth). If this is incorrect, then we don't have to do this now.

**Comment by sheralim012** [comment]
@istride I have updated the PR for this task with your suggestions, could you review it
