### ISSUE TITLE
Separate pt_BR and pt_MZ locales

### ISSUE THREAD

**Issue by cbunicef** [unicef/iogt#1111]
Is there a reason we put them together when moving from V1?

**Comment by geoo89** [comment]
The official translation sheet we received from UNICEF for V2 strings has only one one column per language. In that sheet, the territory associated with Portuguese is MZ (so this is also what I'm using in the registration survey).

**Comment by cbunicef** [comment]
Could we designate the translation as specifically pt_MZ, and use that locale when we migrate Mozambique? And then leave pt and pt_BR undefined for now?

**Comment by cbunicef** [comment]
- [ ] Change registration survey strings to be pt version rather than pt_MZ
