### ISSUE TITLE
makemessages doesn't work with UTF-8

### ISSUE THREAD

**Issue by geoo89** [unicef/iogt#1122]
When running manage.py makemessages, the resulting PO file has unicode characters stripped from it. (The pot file is fine, however).
The following error message occurs during makemessages:

```
./iogt/locale/django.pot:853: warning: The following msgid contains non-ASCII characters.
                                       This will cause problems to translators who use a character encoding
                                       different from yours. Consider using a pure ASCII msgid instead.
                                       © The Internet of Good Things
```

For now, this only affects the string "© The Internet of Good Things" and so I've been fixing it manually, but it'd be good to track down the cause and fix it. Could also be a system specific issue, though @edmoss94 has the same issue I believe.

**Comment by cbunicef** [comment]
This affects emojis, does it also affect non-roman character sets? If it affects eg Arabic then this is a priority issue @geoo89

**Comment by geoo89** [comment]
This only affects the translation source strings (English), not the translations themselves. In practice, the only string affected right now is "(C) Internet of Good Things" at the bottom of the page, for which I implemented a workaround.

**Comment by cbunicef** [comment]
Oh this is just for site interface strings? Then yes it's not a concern. We can change the © symbol to (c) temporarily if it's easier.

**Comment by geoo89** [comment]
A cleaner fix for this (using the current pipeline for translations) is to invoke `makemessages` with the `--keep-pot` option, and then process the resulting .pot file rather than a .po file, which appears to not have the unicode issue.

Even with this fix, we should keep this issue in mind once we move to a different system that explicitly uses makemessages (e.g. if we use crowdin for translations, and source the .po files for crowdin directly from `makemessages`).
