### ISSUE TITLE
Survey's Questions Preview 

### ISSUE THREAD

**Issue by micheladegiusti** [unicef/iogt#1123]
Added to a survey questions that required date of birth and email address. When looking at the preview, before publishing the content, the questions won't display. Only when the page is published the questions will display.

![image](https://user-images.githubusercontent.com/98154212/152679362-052a18a8-2ebb-4b6b-a720-2869492f2524.png)

**Comment by Alihassanc5** [comment]
- This problem has been fixed in wagtail version v2.15 LTS. 
- Once this PR #1369 is merge, it will be fixed.
