### ISSUE TITLE
Make it impossible to bypass Custom Registration questions

### ISSUE THREAD

**Issue by ehmadzubair** [unicef/iogt#113]
The registration questions' data is very important for the countries hosting IOGT. The questions are essentially part of the registration process and no user should be able to register to the platform without completing the questionnaire. 

The custom questions need to be customisable by the editors and show up right after setting up the username password. If the user exits the website at this point, they should be 'locked out' of IoGT until they fill the survey form. They shouldn't even be able to access the public content that i accessible otherwise.

cc: @dannyparsons

**Comment by ehmadzubair** [comment]
I'm picking this ticket

**Comment by cbunicef** [comment]
@ehmadzubair Thank you for the quick work on this. Not sure how exactly this was implemented in the pull request but just to clarify - this should be a feature that an admin can enable or disable for their deployment, so that we can accommodate a broad set of use cases.

**Comment by dannyparsons** [comment]
@cbunicef Yes the additional questions will be fully customisable by the CMS editors, including having no questions if desired. And of course the site is still accessible without login as normal.
