### ISSUE TITLE
Import Tool Bugs

### ISSUE THREAD

**Issue by lauriemarkle** [unicef/iogt#1141]
- Testing confirms successful transfer via only a single page at a time.
- If an article has a child survey which is embedded in the parent article, it cannot transfer. 
- If an article is transferred and contains an embedded survey from another section, the page transfers without the survey embedded. 
- Testing allows content to migrate from Sandbox to IDEMS but not IDEMS to Sandbox.

The ability to transfer multiple pages + parent articles with child surveys, polls, or quizzes, is critical to the migration process and the release of the Your Health content package. As an example, note https://global.iogt.site/admin/pages/1317/ with multiple articles containing children articles and survey tools.

**Comment by cbunicef** [comment]
**Critical**
- Ability to transfer a Page tree without references

**Quick follow if it's easy**
- Outputs as documented in the PPT slide

**Final**
- Automate everything
