### ISSUE TITLE
Slight issue with "would you like to download audio/video" text

### ISSUE THREAD

**Issue by cbunicef** [unicef/iogt#1143]
![image](https://user-images.githubusercontent.com/30042226/153560347-67d98544-745d-4c64-916a-06f60c5c49ee.png)

Extra space and period, at least in English. This is from ec.iogt.site.

**Comment by geoo89** [comment]
This was fixed here, but hasn't been pushed to EC yet. https://github.com/unicef/iogt/commit/bcd0ec040fad64f37076ddac83a81c9628c7a022
