### ISSUE TITLE
<title> seems to append " - default"?

### ISSUE THREAD

**Issue by cbunicef** [unicef/iogt#1144]
![image](https://user-images.githubusercontent.com/30042226/153560636-15951462-1a00-4680-a8b9-44ec1abc338d.png)

This one confuses me. Seems to be consistent but only on ec.iogt.site.

**Comment by geoo89** [comment]
This string is taken from the setting in https://ec.iogt.site/admin/sites/

I believe the `create_default_site` management command that we use during overwrites the site name that was set during the migration with `default` -- This should be fixed.

**Comment by cbunicef** [comment]
Thanks, yes I made the change in Sites and it fixed the issue.
