### ISSUE TITLE
Leaving/Replying to Comments

### ISSUE THREAD

**Issue by micheladegiusti** [unicef/iogt#1145]
When I submit a comment, or reply to a comment, for instance on these pages, but it happens also for other pages, this page opens saying: Example Domain. 

https://idems.iogt.site/en/sections/emergency-information/about-covid-19/nutrition-tips-during-covid-19/; http://example.com/en/sections/connect-smart/be-good-digital-citizen/#c24;
http://example.com/en/sections/connect-smart/stop-hacker/#c25
http://example.com/en/sections/healthy-living/healthy-eating/healthy-breakfast-ideas/#c23

Only when I open the page again the comment is displayed.

http://example.com/en/sections/healthy-living/healthy-eating/#c44
![image](https://user-images.githubusercontent.com/98154212/153626988-23560939-2a6e-46aa-a624-9fff3d019bf8.png)

**Comment by cbunicef** [comment]
It appears this is fixed in the most recent version, in sandbox

https://sandbox.iogt.site/en/sections/emergency-information/about-covid-19/nutrition-tips-during-covid-19/#c18

**Comment by geoo89** [comment]
This is a configuration issue. It looks like we didn't run `create_initial_site` for idems.iogt.site. I fixed it manually now.

Please have another look now.
