### ISSUE TITLE
"Sandbox" section

### ISSUE THREAD

**Issue by cbunicef** [unicef/iogt#1154]
Hide Sandbox section from search
Only allow wagtail-transfer destination in Sandbox section
Add empty Sandbox section during migration and new platform launch

**Comment by cbunicef** [comment]
Should Sandbox sit under the homepage, or under Sections?

**Comment by sheralim012** [comment]
1st and 3rd points are addressed in #1160 PR, and could you elaborate 2nd point 
like do we want to restrict actions for sandbox and its descendents

**Comment by cbunicef** [comment]
Yes for the immediate situation. Right now when importing content it is published if published on the source. So it should be imported to a location where it can be reviewed before being visible on the site.

Unless we anticipate issues?

**Comment by geoo89** [comment]
> 1st and 3rd points are addressed in #1160 PR, and could you elaborate 2nd point like do we want to restrict actions for sandbox and its descendents

Let's add a warning in red above the destination page selector saying "We strongly recommend choosing a destination within the sandbox, to allow checking the transferred content for errors before going live. You can then move the content to the desired final destination."
