### ISSUE TITLE
Medium-size video file upload fails, eg 4MB

### ISSUE THREAD

**Issue by cbunicef** [unicef/iogt#1168]
In the media upload dialogue this gives an HTTP error:

<img width="349" alt="image" src="https://user-images.githubusercontent.com/30042226/154933057-0e846127-7a8e-4d5d-b21b-532b18da3000.png">

While trying to upload as a document I get this error:

<img width="761" alt="image" src="https://user-images.githubusercontent.com/30042226/154933188-aba2bc2e-9863-4ed0-8f43-5d9e57261d2e.png">

This issue is documented on DevOps as well: https://dev.azure.com/unicef/ICTD-IOGT/_boards/board/t/ICTD-IOGT%20Team/Stories/?workitem=111040

**Comment by ChrisMarsh82** [comment]
Resolved on the deployment side
