### ISSUE TITLE
Survey Migration Failure

### ISSUE THREAD

**Issue by lauriemarkle** [unicef/iogt#1185]
[2 Surveys appearing on ke.goodinternet.org](https://ke.goodinternet.org/sections/emergency-information/) - at the bottom of linked page - did not correctly migrate to 2.0. Only the titles transferred, but questions (i.e. form fields) did not. 

Survey 1:
[v1.0](https://ke.goodinternet.org/admin/pages/824/edit/)
[v2.0](https://ke.iogt.site/admin/pages/553/edit/)

Survey 2: 
[v1.0](https://ke.goodinternet.org/admin/pages/823/edit/)
[v2.0](https://ke.iogt.site/admin/pages/552/edit/)

**Comment by cbunicef** [comment]
@ChrisMarsh82 Not sure were to put this in our Projects, but this is something we should look at in the migration workstream

**Comment by sheralim012** [comment]
just ran the migration locally and both surveys and their questions were successfully migrated
@istride could you share the post-migration report, maybe it has some info about these non-migrated survey questions

**Comment by geoo89** [comment]
This was fixed a while ago, but I believe we haven't re-migrated the KE site since the fix. @istride You can close this issue once you've re-migrated KE.

**Comment by istride** [comment]
Re-migrated with version 2.0.12 and the two surveys look much better now.
