### ISSUE TITLE
In surveys (possibly polls/quizzes) the help text for non-required questions is "optional" rather than the intended help text eg "check all that apply"

### ISSUE THREAD

**Issue by cbunicef** [unicef/iogt#1191]
"Optional" should show below the label and above the help text. It can be part of the help text block, with a newline between "optional" and the help text.

**Comment by geoo89** [comment]
The label is currently below the help text, so I don't fully understand the proposal here.
Is #1211 acceptable?

**Comment by cbunicef** [comment]
Here's a more clear explanation:

Survey Title

Question 1 of 10
Label
Optional (if applicable, don't show Required)
Help Text
Option 1
Option 2

Optional and Help Text are in a single text block, separated by a newline. To the left of the block, vertically centered, there is the (i) icon.

Is that more clear? "Question 1 of 10" will be shown once that feature is fixed.
