### ISSUE TITLE
As a CMS editor, I can modify the site's logo with an image upload from my gallery

### ISSUE THREAD

**Issue by lauriemarkle** [unicef/iogt#12]
Image size specifications should be noted in the CMS as an information box / hover .

**Comment by dannyparsons** [comment]
Logo is chosen in Site Settings similarly to v1:

![image](https://user-images.githubusercontent.com/11214914/122749102-d8380c80-d284-11eb-9b89-c2ba0c1dfe2f.png)

**Comment by sheralim012** [comment]
@ChrisMarsh82 this isn't implemented yet.
