### ISSUE TITLE
Chat Bot Epic

### ISSUE THREAD

**Issue by ehmadzubair** [unicef/iogt#121]
This Epic has tickets related to the chat bot functionality for IoGT. Significant work for the functionality has been done by @geoo89 and he should be the contact point for any questions/queries.

Here is a list of features that need to be done as a part of this epic:
- Review `messaging.models` - Use managers where applicable
- Refactor messaging app to be more django-esque
- Replace `urllib.request` with `requests` package
- Update existing test cases to use Django Test framework (contrary to DjangoTestPlus)
- Add Model Factories for `messaging` Test Cases
- Complete skipped test cases
- Use [rapidpro-python](https://github.com/rapidpro/rapidpro-python) or write custom client for communication with RapidPro server
- Decide on async/sync communication with RapidPro server
- Refactor the RapidPro webhook to use DRF
- Refactor Test Cases
- Stitch longer messages to single message on the IoGT website
- Make quick replies "clickable" so the user doesn't have to type them
- Preview image links to show images (not a file)
- Give the editor an option to start a chat with the chosen bot based on a button
- Add Chatbot settings to Wagtail Admin

Additionally, once the above functionality is working, we'd have to look into the following problems:
- The communication from IoGT to RapidPro isn't secure because there is no authentication layer. We need to figure out a way to make this communication secure.
- Test the integration on a newer version of IoGT
- Figure out a way to auto update the screen or intimate the user that their latest messages will be shown only when they update the page

**Comment by ehmadzubair** [comment]
@dannyparsons @geoo89 can you proofread this and add something I might have missed?

**Comment by geoo89** [comment]
Thanks, this looks great! A few minor comments:

> Use [rapidpro-python](https://github.com/rapidpro/rapidpro-python) or write custom client for communication with RapidPro server
I believe (but please double check) rapidpro-python is just a wrapper for [this API](https://rapidpro.io/api/v2/), which allows you to access the content on the server (e.g. defined flows, contacts, etc), but is not for sending messages back and forth.

> Stitch longer messages to single message on the IoGT website
You can identify messages that belong together in that they have the same rapid_pro_message_id. I don't think we can easily recover the correct order for stitching together though if the requests arrive in the wrong order.

> Preview image links to show images (not a file)
Attachments can be of various media types (image, video, etc); RapidPro does store the media type of a file, but unfortunately doesn't transmit it via the External API channel. Attachment URLs are currently part of the message body. (I defined an attachments field, but it's not being populated yet, which needs to be done.)

> Give the editor an option to start a chat with the chosen bot based on a button
Each button should probably have a bot and a trigger message associated to it (different triggers can start different chat flows within the same bot).

**Comment by sheralim012** [comment]
@dannyparsons Could you please confirm the following:

- Can an article have more than one **chat with bot** buttons?
- Do we want to dictate the order of contents and  **chat with bot** button e.g., some content then **chat with bot** button, and then again some content... or chat with bot button will always appear at the same place?

**Comment by dannyparsons** [comment]
It would be good to have the chat with bot button as an element of the body which could be placed anywhere within the contents.

It would be good not to be restricted to one button only in an article.
