### ISSUE TITLE
Unknown language code wo

### ISSUE THREAD

**Issue by istride** [unicef/iogt#1214]
The Senegal site is not working due to internal server errors on pretty much every page (inc. admin). The pertinent error message is "KeyError: 'Unknown language code wo.'". An extract of the logs has been provided below.

The code 'wo' corresponds to [Wolof][1].

[unknown-language-code.txt](https://github.com/unicef/iogt/files/8287622/unknown-language-code.txt)

[1]: https://en.wikipedia.org/wiki/Wolof_language

**Comment by geoo89** [comment]
Wolof was never on the list of languages to support that was given to us. I assume adding Wolof is straight-forward (and would at least get rid of this error), but also the translation speadsheet we got doesn't have Wolof, so we cannot localize any IoGT site strings in Wolof.

**Comment by cbunicef** [comment]
Can we delete the Wolof information from V2 to fix the bug? There is no Wolof content on the site that I can find. We may want to Wolof later but we don't need it now.

**Comment by sheralim012** [comment]
Should I add wolof in supported languages list? 
as deleting wolof would be difficult because admin site is not working 
and we would have to delete locale from database directly (not recommended)

**Comment by cbunicef** [comment]
This would be OK for me:
- Add Wolof to supported languages as "Wolof (Not Yet Translated)
- Use English strings (or possibly just leave Wolof string empty if empty strings default to English automatically?)
- Once the sn.goodinternet.org Admin Panel is accessible we can delete the Wolof locale for that site
