### ISSUE TITLE
Confusion among multiple languages on sa.iogt.site

### ISSUE THREAD

**Issue by cbunicef** [unicef/iogt#1232]
Accessing https://sa.iogt.site redirects properly to /en/

Once on the English homepage:
- The logo clicks to /en/None/
- Selecting BN language leads to /en/bn/
- Selecting other languages afterward leads to unpredictable results eg I am now on /en/bn/bn/None

@istride @sheralim012 can you please look into this?

**Comment by sheralim012** [comment]
The Bengali language wasn't supported in the current codebase so created a PR to add it
