### ISSUE TITLE
Better "Choose a page" navigation when using multiple languages

### ISSUE THREAD

**Issue by dannyparsons** [unicef/iogt#125]
When multiple languages are used the page selector in standard Wagtail e.g. page link or related articles, shows all language trees but it doesn't indicate which language is for which tree or have the ability to filter by language.

![image](https://user-images.githubusercontent.com/11214914/123083687-347f6580-d418-11eb-8329-c5eec0bd0b95.png)

An immediate solution is to use a standard naming convention for the Homepages as below, which avoids the confusion.

![image](https://user-images.githubusercontent.com/11214914/123083888-74464d00-d418-11eb-8778-7bfb9d37cb32.png)

This avoids the confusion when navigating, but a better solution would be having a filter option to restrict to a certain language to avoid potential confusion. I believe this PR in Wagtail is intended to do this https://github.com/wagtail/wagtail/pull/6489

**Comment by ChrisMarsh82** [comment]
duplicate
