### ISSUE TITLE
Abilty to delete all user data

### ISSUE THREAD

**Issue by ChrisMarsh82** [unicef/iogt#1252]
This option should only be available at the deployment level.

Need the ability to be able to take a backup from an existing database (i.e. Central) and use that to create a new deployment. We will then need the ability to remove all user data. Showing a single admin user as creating all the content.

**Comment by sheralim012** [comment]
following user data will be cleared
- users and users' profiles
- questionnaires submissions
- comment flags

@ChrisMarsh82 could you confirm the above-mentioned list 
also do we want to delete comments too?

**Comment by ChrisMarsh82** [comment]
@sheralim012 - Yes, we want to delete comments too. Anything that is not content that would be created in the Admin area.

**Comment by sheralim012** [comment]
got it,
added comments and chats too
