### ISSUE TITLE
Content migration incomplete (South Asia)

### ISSUE THREAD

**Issue by istride** [unicef/iogt#1258]
The content migration has been re-run on the South Asia site (with latest code, v2.0.15), but the logs show that the migration was not complete, for example, surveys not translated or even saved. See log, below.

Please investigate each issue in the migration report and suggest fixes or workarounds for each. Let me know if a copy of the V1 database is required.

[load_v1_db_sa.log](https://github.com/unicef/iogt/files/8531761/load_v1_db_sa.log)

**Comment by cbunicef** [comment]
Maybe we should manually re-create these Pages on V2? If this seems like a one-off issue,
