### ISSUE TITLE
In survey/poll/quiz, remove (i) icon if unnecessary

### ISSUE THREAD

**Issue by cbunicef** [unicef/iogt#1267]
If a question is required, doesn't have a standard help text (eg single line text), and no custom help text is provided - the (i) is still shown.

<img width="432" alt="image" src="https://user-images.githubusercontent.com/30042226/166667029-20d83ef0-51b1-4852-88b7-b15a898473ff.png">

It shouldn't appear if there is no help text to be shown.

**Comment by Alihassanc5** [comment]
This issue has been resolved already.
