### ISSUE TITLE
During migration, remove Index description from Articles

### ISSUE THREAD

**Issue by cbunicef** [unicef/iogt#1268]
The log can appear the same way as for Sections, ie link along with the original description text.

**Comment by cbunicef** [comment]
@ChrisMarsh82 if this is an easy add let's prioritize it, this will save us a lot of time during migrations.

**Comment by geoo89** [comment]
Just for clarification, the is referring to the index page description of articles, which is taken from the article subtitle in V1, correct?

The aim is to not take the subtitle of the V1 article as index page description in V2, and instead issue a warning during the report?
