### ISSUE TITLE
Error when translating a page - MultipleObjectsReturned, TranslationSource

### ISSUE THREAD

**Issue by istride** [unicef/iogt#1290]
To reproduce this bug:

1) Create a site with at least 1 page, in the English locale
1) Add a locale (L1), don't synchronise
1) Add another locale (L2), don't synchronise
1) Translate the English page into L1
1) Translate the L1 page to L2
1) Boom!

There is a [very similar issue][1] logged in the wagtail-localize project. Potentially, this problem will not be resolved until it is resolved in wagtail_localize. Nevertheless, we would still want to know what can be done to recover from this bug if/when it happens, and to prevent it from happening in the first place.

Stacktrace:
```
Traceback (most recent call last):
  File "/blah/blah/iogt/lib/python3.10/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/blah/blah/iogt/lib/python3.10/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/blah/blah/iogt/lib/python3.10/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/blah/blah/iogt/lib/python3.10/site-packages/wagtail/admin/urls/__init__.py", line 127, in wrapper
    return view_func(request, *args, **kwargs)
  File "/blah/blah/iogt/lib/python3.10/site-packages/wagtail/admin/auth.py", line 172, in decorated_view
    response = view_func(request, *args, **kwargs)
  File "/blah/blah/iogt/lib/python3.10/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/blah/blah/iogt/lib/python3.10/site-packages/wagtail/admin/views/pages/edit.py", line 114, in dispatch
    response = self.run_hook('before_edit_page', self.request, self.page)
  File "/blah/blah/iogt/lib/python3.10/site-packages/wagtail/admin/views/generic.py", line 60, in run_hook
    result = fn(*args, **kwargs)
  File "/blah/blah/iogt/lib/python3.10/site-packages/wagtail_localize/wagtail_hooks.py", line 259, in before_edit_page
    return edit_translation.edit_translation(request, translation, page)
  File "/blah/blah/iogt/lib/python3.10/site-packages/wagtail_localize/views/edit_translation.py", line 819, in edit_translation
    locale_id=TranslationSource.objects.get(
  File "/blah/blah/iogt/lib/python3.10/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/blah/blah/iogt/lib/python3.10/site-packages/django/db/models/query.py", line 433, in get
    raise self.model.MultipleObjectsReturned(

Exception Type: MultipleObjectsReturned at /admin/pages/39/edit/
Exception Value: get() returned more than one TranslationSource -- it returned 2!
```

[1]: https://github.com/wagtail/wagtail-localize/issues/547

**Comment by ChrisMarsh82** [comment]
@sheralim012 can you help look for a workaround for this issue. We can't wait for this to be fixed in wagtail-localize, we need to make sure the problem cannot happen on a live site

**Comment by istride** [comment]
@sheralim012 I would like to know more information before deploying this on sandbox.

- Did you manage to reproduce this issue locally?
- What is the nature of the change that you made to wagtail-localize?
- Has this been tested locally, after you made those changes?

**Comment by sheralim012** [comment]
> @sheralim012 I would like to know more information before deploying this on sandbox.
> 
> * Did you manage to reproduce this issue locally?

yes, I followed the steps you mentioned and reproduced the issue locally.

> * What is the nature of the change that you made to wagtail-localize?

instead of creating multiple objects, it updates the existing object.

> * Has this been tested locally, after you made those changes?

yes, I have tested it locally and it's working, also I wrote a new test case in wagtail-localize for this scenario, and all test cases are passing after the change.

**Comment by istride** [comment]
I had to review the changes in your fork of wagtail-localize to understand what is going on.

It seems like the bug is fixed, which is great. My only problem with the fix is that it's based on code that is between releases. It would be better to branch from v1.1.1 (current version in the app) or perhaps v1.1.2. Although v1.2 has just been released, it seems that quite a lot has changed, so we would have to make sure it is safe to upgrade.

@sheralim012 If you base the fix on v1.1.1 or v1.1.2, I think we can then test the fix on sandbox. I think you should also prepare a PR to fix issue 587 in the wagtail-localize project. If accepted, we can then look into upgrading to whatever version includes your fix, and stop using a fork.

**Comment by sheralim012** [comment]
@istride I have used v1.1.2 as base now, you can deploy on sandbox and test.

**Comment by istride** [comment]
I've noticed that [wagtail-localize v1.2.1](https://github.com/wagtail/wagtail-localize/releases/tag/v1.2.1) includes your fix (congratulations!). I think we should try to upgrade to this version rather than mess around with a fork. It would be a minor version upgrade, so it should be ok, but we would have to test it thoroughly, of course.

@sheralim012 Would you create a new PR for the upgrade, and begin testing?

**Comment by sheralim012** [comment]
@istride I have tried the wagtail-localize v1.2.1 but it has some header style changes for the edit translation page which aren't compatible with the wagtail v2.11.* we are using
<img width="1846" alt="Screenshot 2022-06-29 at 4 25 12 PM" src="https://user-images.githubusercontent.com/49383675/176426939-dd66c012-dad6-4b01-99a6-a7329b990b05.png">
then I tried wagtail v2.12.* and onwards to v2.15.* (LTS) and the style issue isn't occurring 

Should we update the wagtail version too as this issue #1263 also requires it?
I know it will require extensive testing and if we don't want to update wagtail then we can go with the fork solution
Let me know if you have any other ideas

**Comment by istride** [comment]
I think it makes sense to upgrade rather than introduce forks, and it seems we have to upgrade Wagtail anyway - better to do it sooner rather than later.

@ChrisMarsh82 @cbunicef Just want to be sure you don't have any major objections to this.

**Comment by istride** [comment]
@sheralim012 I would prefer creating a new issue as I consider the original issue to have been fixed and see this as a different (though very similar) problem. I think it would be a good idea to mention this issue in the new one.
