### ISSUE TITLE
As the CMS editor, I can select the color scheme for my site using HEX codes

### ISSUE THREAD

**Issue by lauriemarkle** [unicef/iogt#13]
CMS editors can override the default color scheme for IoGT in the settings tab by selecting the default colors for various features and replacing them with a HEX code.

**Comment by ehmadzubair** [comment]
@ChrisMarsh82 can you have someone send in the design with a different theme color? That'll help us understand where all this change needs to be done.

cc: @azahid89

**Comment by ChrisMarsh82** [comment]
David to speak to Ehmad explaining what is required here.

**Comment by ehmadzubair** [comment]
This is a much wider change that the theme. Colors needs to be customisable as much as possible. Ideally there should be a very detailed theme file which specifies the colors throughout the website. This needs to be set from the admin.

**Comment by ehmadzubair** [comment]
As part of this ticket, do the following:

- [ ] Fix website-wide structure of components so that paddings are predictable
- [ ] List down all the UI components that can be moved to theme
- [ ] Create an admin page where the theme can be set (preferably add images/screenshots in that screen)

cc: @azahid89

**Comment by ehmadzubair** [comment]
Thank you @azahid89

Let's start with the following changes
- [ ] Have uniform spacing throughout the website
- [ ] Create a themed button which can be used throughout the platform
- [ ] Create a themed anchor tag which can be used throughout the website
- [ ] Create a theme settings page on the admin panel where the styles can be added from
