### ISSUE TITLE
"Survey" label on embedded surveys don't appear to be translated

### ISSUE THREAD

**Issue by cbunicef** [unicef/iogt#1304]
Example from mg.goodinternet.org:

<img width="439" alt="image" src="https://user-images.githubusercontent.com/30042226/171186411-a58aa3b0-3844-4770-9732-81391932e425.png">

**Comment by Alihassanc5** [comment]
The translation for "SURVEY" needs to be added.

**Comment by cbunicef** [comment]
Thanks @Alihassanc5, is this only a missing translation issue and not an interface issue? If so please go ahead to close

**Comment by sheralim012** [comment]
Checked on sandbox by adding translated string for Arabic and looks alright, so closing it.
<img width="529" alt="Screenshot 2023-02-08 at 9 53 47 PM" src="https://user-images.githubusercontent.com/49383675/217597914-9dbe0c5b-1e1f-499d-ad00-248a79f8ab1d.png">
