### ISSUE TITLE
Bengali language - site interface uses a Bengali-compatible font, but content is not 

### ISSUE THREAD

**Issue by cbunicef** [unicef/iogt#1310]
<img width="667" alt="image" src="https://user-images.githubusercontent.com/30042226/172599860-03765379-5321-4cec-9c86-643eefb38a9e.png">

The right box should have Bengali script.

This is also the case in the Admin Panel, which prevents editing of Bengali content.

**Comment by ChrisMarsh82** [comment]
@cbunicef which site is this on? I checked https://sa.iogt.site/admin/pages/919/view_draft/ and it looks ok. Is there something I am missing?

**Comment by cbunicef** [comment]
This may be an issue related to the original reporter's computer, looking into it

**Comment by cbunicef** [comment]
Investigation points to mismatching configurations between computers, rather than an issue with IoGT. We are working on our side to resolve, if we can then I will close the issue.

**Comment by sheralim012** [comment]
@cbunicef any update on this?

**Comment by cbunicef** [comment]
No issues at this point, closing the issue
