### ISSUE TITLE
Page link page's which are external links not appearing on site

### ISSUE THREAD

**Issue by edmoss345** [unicef/iogt#1312]
Created a page link page directly linking to an external link. Page shows up in admin area but then does not appear on live site. For example, created a footer called 'Direct External Link', but when viewing the site the footer is not visible.

![image](https://user-images.githubusercontent.com/69303397/173476984-8615535f-5798-4680-b5bf-551004b1a599.png)

![image](https://user-images.githubusercontent.com/69303397/173477060-dfe23d56-ef6d-406d-9eb4-bd2fcb4bf6e1.png)

**Comment by sheralim012** [comment]
@ChrisMarsh82 Do we want to render page link page (to external site) as section child too?

**Comment by sheralim012** [comment]
I thought that we could render it as a section or article card
Yes, we never had this functionality, but I just wanted to make sure
