### ISSUE TITLE
Disable all media pre-fetch

### ISSUE THREAD

**Issue by cbunicef** [unicef/iogt#1314]
Please disable any pre-fetching of audio or video content.

**Comment by sheralim012** [comment]
got it, 
- I have updated the PR and added media URLs back in the sitemap for offline access
- I have stopped pre-loading of audio/video assets on page load
- audio/video assets wouldn't be downloaded until user clicks on the play button
- thumbnail will still show for the video assets

**Comment by cbunicef** [comment]
Amazing, thanks a lot Sher.
