### ISSUE TITLE
Poll creation doesn't include "Answer Options" section

### ISSUE THREAD

**Issue by cbunicef** [unicef/iogt#1322]
Current Poll creation

<img width="523" alt="image" src="https://user-images.githubusercontent.com/30042226/176165566-27841a9b-4844-43d6-a018-411d60d2f7b4.png">

Current Survey creation

<img width="501" alt="image" src="https://user-images.githubusercontent.com/30042226/176165696-1bee9dc2-5880-4091-a0d1-5f0d2918c81c.png">

Existing Polls work because the Answer Options were already populated, but new Polls cannot successfully be created. Polls can be Published but they give a server error when opened. For example: 

https://eg.iogt.site/admin/pages/114/edit/
https://eg.iogt.site/en/sections/test-section/positive-parenting-age-0-5/unit-1-introduction-the-first-1000-days/%D8%A7%D9%84%D8%AA%D9%85%D8%B1%D9%8A%D9%86-%D8%A7%D9%84%D8%A3%D9%88%D9%84/%D8%AA%D9%85%D8%B1%D9%8A%D9%86/

**Comment by sheralim012** [comment]
fixes via #1331 
<img width="1026" alt="Screenshot 2022-08-03 at 11 35 17 PM" src="https://user-images.githubusercontent.com/49383675/182684101-95ccb1d1-0fef-47fc-8fa9-6f364db5af61.png">
<img width="588" alt="Screenshot 2022-08-03 at 11 35 31 PM" src="https://user-images.githubusercontent.com/49383675/182684114-166abe67-67b1-4d2b-8105-65c6a74ee5ed.png">
