### ISSUE TITLE
At least some URL parameters are not passed to Google Analytics

### ISSUE THREAD

**Issue by cbunicef** [unicef/iogt#1330]
To replicate error in V2

1. Go to https://www.internetofgoodthings.org/en/?test
2. In [Google Analytics Realtime > Overview](https://analytics.google.com/analytics/web/#/realtime/rt-overview/a88936714w116819520p122182821/), note that the URL which appears is /en/ and not /en/?test

To see behavior in V1

1. Go to https://ci.goodinternet.org/?test
2. In [Google Analytics Realtime > Overview](https://analytics.google.com/analytics/web/#/realtime/rt-overview/a104378100w145476574p150206335/), note that the URL which appears is /?test=

`?test=` is also not ideal, as it should really be `?test`

I noticed that in the page source for V2 the GA call doesn't include the parameters:

URL I used:

`https://www.internetofgoodthings.org/en/?test`

From page source:

```
<img src="/en/djga/google-analytics/?&amp;p=%2Fen%2F&amp;tracking_code=UA-69353247-43" width="0" height="0" />
<img src="/en/djga/google-analytics/?&amp;p=%2Fen%2F&amp;tracking_code=UA-88936714-1" width="0" height="0" />
```

And from the djga repo, it looks like the path that is sent to Google Analytics is from that "p" parameter in the URL to the tracking pixel:

```
    # get the path from the referer header
    path = path or request.GET.get('p', '/')
```

https://github.com/praekeltfoundation/django-google-analytics/blob/ad5a0515575042058ed602af8d3f6d2def0ef608/google_analytics/utils.py#L75

```
    # build the parameter collection
    params = {
        'v': VERSION,
        'z': str(random.randint(0, 0x7fffffff)),
        'dh': domain,
        'sr': '',
        'dr': referer,
        'dp': quote(path.encode('utf-8')),
        'tid': account,
        'cid': visitor_id,
        'uip': custom_uip or client_ip,
        'ni': ni,
    }
```

https://github.com/praekeltfoundation/django-google-analytics/blob/ad5a0515575042058ed602af8d3f6d2def0ef608/google_analytics/utils.py#L94

Why doesn't this bug appear in V1? Maybe the middleware implementation somehow doesn't have the issue.

**Comment by sheralim012** [comment]
this issue exists in the package for both approaches pixel tracking and middleware + celery

The reason it's working in V1 is that V1 is using a custom middleware which basically fixes this issue  https://github.com/praekeltfoundation/molo/blob/develop/molo/core/middleware.py#L120

we can either use the custom middleware (with celery) or fix the pixel tracking by forking it
both aren't trivial tasks and will take time
