### ISSUE TITLE
In surveys, help text is not appearing for single-line and multi-line text

### ISSUE THREAD

**Issue by cbunicef** [unicef/iogt#1336]

**Comment by cbunicef** [comment]
@ChrisMarsh82 this seems like an easy one to solve, if so let's get it out of the way.

**Comment by ChrisMarsh82** [comment]
@edmoss345 please can you look into this

**Comment by sheralim012** [comment]
current logic for help text

- if a question is **not required** then only show "OPTIONAL" as help text
- if help text is given for **radio/dropdown/checkboxes/checkbox/date/datetime** then show it
- if no help text is given for **radio/dropdown** then show "Select one"
- if no help text is given for **checkboxes** then show "Check all that apply"
- if no help text is given for **checkbox** then show "Check if applies"

questions:
- for non-required questions, should we show the given help text alongside "Optional"?

proposed solution:
- if a question is **not required** then show "OPTIONAL" as help text
- if help text is given for a question then show it (in case of non-required question append it to OPTIONAL)
- if no help text is given for **radio/dropdown** then show "Select one"
- if no help text is given for **checkboxes** then show "Check all that apply"
- if no help text is given for **checkbox** then show "Check if applies"

CC: @ChrisMarsh82

**Comment by cbunicef** [comment]
Thanks @sheralim012, your solution is great. Please put "Optional" above the help text eg "Select one".
