### ISSUE TITLE
Permissions to "Add/Change Users" allow for privilege escalation without warning

### ISSUE THREAD

**Issue by cbunicef** [unicef/iogt#1347]
As noted on the Wagtail repo, the Add/Change Users permission allows a user to escalate their own privilege to Admin: https://github.com/wagtail/wagtail/issues/5188

As a PLATFORM ADMIN I want permissions to be easily understood, and I want to be extremely aware if my users can escalate their own privileges.

The suggestion from the issue on Wagtail repo is to add a helptext to the Add/Change user setting, but that requires an API overhaul.

What are our alternatives? Could we 
1. create a group, eg "Manage Users - Trusted Admins Only" which gives that permission
2. remove the Add/Change Users permission from the list so that it cannot be given to users

Any other suggestions?

We need to do something to address this ASAP, but it can be the bare minimum.

@ChrisMarsh82 @istride

**Comment by ChrisMarsh82** [comment]
We will need to remove 'User' and 'Group' from the group permissions section. Meaning only Admin has access to these 2 areas.
