### ISSUE TITLE
Footer pages do not translate

### ISSUE THREAD

**Issue by dannyparsons** [unicef/iogt#136]
When trying to create a translated version of a footer page in a new language I get the following error:

![image](https://user-images.githubusercontent.com/11214914/123421071-4ac22880-d5b4-11eb-8d1b-c29c880054df.png)

ValueError at /admin/localize/submit/page/14/
Cannot add [] (<class 'modelcluster.queryset.FakeQuerySet'>). Expected <class 'django.db.models.base.ModelBase'> or str.
Request Method:	POST
Request URL:	http://127.0.0.1:8000/admin/localize/submit/page/14/?next=%2Fadmin%2Fpages%2F13%2F
Django Version:	3.1.12
Exception Type:	ValueError
Exception Value:	
Cannot add [] (<class 'modelcluster.queryset.FakeQuerySet'>). Expected <class 'django.db.models.base.ModelBase'> or str.
Exception Location:	C:\Users\Danny\source\repos\iogt\env\lib\site-packages\taggit\managers.py, line 208, in _to_tag_model_instances
Python Executable:	C:\Users\Danny\source\repos\iogt\env\Scripts\python.exe
Python Version:	3.8.0
Python Path:	
['c:\\Users\\Danny\\source\\repos\\iogt',
 'C:\\Users\\Danny\\AppData\\Local\\Programs\\Python\\Python38\\python38.zip',
 'C:\\Users\\Danny\\AppData\\Local\\Programs\\Python\\Python38\\DLLs',
 'C:\\Users\\Danny\\AppData\\Local\\Programs\\Python\\Python38\\lib',
 'C:\\Users\\Danny\\AppData\\Local\\Programs\\Python\\Python38',
 'C:\\Users\\Danny\\source\\repos\\iogt\\env',
 'C:\\Users\\Danny\\source\\repos\\iogt\\env\\lib\\site-packages']
Server time:	Fri, 25 Jun 2021 09:58:17 +0000

**Comment by sheralim012** [comment]
I'm working on this.
