### ISSUE TITLE
Determine how to define the main menu for each language

### ISSUE THREAD

**Issue by dannyparsons** [unicef/iogt#137]
The main menu can be defined at Settings > Main Menu. There doesn't seem to be built in support for the main menu to be aware of the different site language. Hence we either need to:

- Modify Main Menu such that it automatically translates page links to the correct language (external links remain). This could be done automatically or through making Main Menu translatable. Workarounds are discussed here https://github.com/rkhleics/wagtailmenus/issues/242
- Use Flat Menus which allows for defining additional menus. We could have one flat menu for each language which would have a specific format for the handle so that the language could be detected - this solution is workable now, or language could be added an explicit property. The disadvantage of this is that it requires creating the menu for each language. A possible advantage (or disadvantage) is that the menu could be different in different languages.

The first task is to investigate potential options for modifying Main Menu or Flat Menus to better support languages.

**Comment by dannyparsons** [comment]
We've agreed to use Flat Menus for v2 and have a different flat menu for each language. This is desirable as different menus for different language sites is useful in some cases.

We will use the handle format "en_menu_live" for defining the menu for each language. This format will need to be detected by the front end to display the menu correctly.

**Comment by dannyparsons** [comment]
For v2.1 we should investigate better support for menus and languages e.g. adding a language field to flat menu. We also suggest adding a Live or Active field to flat menus to define which menu is the live menu for a specific language.

It would also be useful to have a way of previewing how a menu will look before making it live on the site.

**Comment by sheralim012** [comment]
@ChrisMarsh82 is it still relevant?

CC: @dannyparsons

**Comment by ChrisMarsh82** [comment]
Should be completed. To be checked. Will be done in 2.0

**Comment by geoo89** [comment]
This is working as described in previous comments. I will close this and make a new issue for possible future improvements.

**Comment by ChrisMarsh82** [comment]
Completed
