### ISSUE TITLE
Enable Brotli and GZIP compression

### ISSUE THREAD

**Issue by cbunicef** [unicef/iogt#1382]
This seems like a quick implementation on nginx.

**Comment by istride** [comment]
This is a deployment concern which has been addressed for UNICEF's deployments. There is nothing to do within the app, so I suggest that this issue be closed.

**Comment by cbunicef** [comment]
Great, it looks like the HTML is compressed:

![image](https://user-images.githubusercontent.com/30042226/212712269-e6a98136-3bd8-4107-869f-0d571936d993.png)

I think the JS and CSS files are not getting compressed:

![image](https://user-images.githubusercontent.com/30042226/212712027-392d7815-a7b1-46c2-9b80-c4afcf5bc594.png)

![image](https://user-images.githubusercontent.com/30042226/212712101-854d7938-aa99-4b69-9858-48132331e7f5.png)

Maybe those MIME types need to be specified? https://stackoverflow.com/questions/5131916/how-to-deflate-js-file-in-nginx#5132440

**Comment by istride** [comment]
I have raised an issue in the DevOps board to continue the work on this. Closing this issue.
