### ISSUE TITLE
In API submissions endpoint, change to JSON format

### ISSUE THREAD

**Issue by cbunicef** [unicef/iogt#1385]
I believe this is reverting back to an earlier format, that I asked us to change to the current format. Sorry for that, although the current format looks good for reading, it doesn't load easily into Power BI.

Current format:

```
			"submission": [
				{
					"age": {
						"clean_name": "how_old_are_you",
						"user_answer": "35+"
					}
				},

```
Desired format:

```
			"submission": [
				{
						"admin_label": "age",
						"clean_name": "how_old_are_you",
						"user_answer": "35+"
				},
```

**Comment by cbunicef** [comment]
@sheralim012 Thanks for your help and sorry for having to revert

**Comment by istride** [comment]
On the issue of whether to introduce a new API version, it looks like there is not widespread usage of the API across UNICEF deployments, so it is tempting not to increment the version number.

If it is generally agreed that v1 should be considered stable, and we're confident that this (breaking) change should also be considered stable, then we should increment the version number.

If v1 is considered unstable, my opinion is that we don't have to increment the version number - we only increment when the api is stable.

If we have doubts about whether this change will stick, then it might be worth considering the creation of an 'unstable' api for experimental features i.e. there would always be a stable and unstable version of the api.
