### ISSUE TITLE
Ukrainian Font Bug

### ISSUE THREAD

**Issue by lauriemarkle** [unicef/iogt#1399]
When testing Ukrainian on IoGT, English language text mixed in with the font appears oversized. 
https://www.internetofgoodthings.org/en/sandbox/ukraine-copy-paste-test/

**Comment by cbunicef** [comment]
For this one we probably need to choose better fonts for languages with non-latin character sets.

Here is an example of a nicer font for Ukrainian: https://spilnoinpl.org/

**Comment by cbunicef** [comment]
Open Sans looks like a good solution for some non-latin languages that are not in Poppins.

Ukrainian in Poppins:

<img width="440" alt="image" src="https://user-images.githubusercontent.com/30042226/193598492-05dc9f7a-9f73-4cde-b676-5c3ed9ed9dc2.png">

Ukrainian in Open Sans:

<img width="446" alt="image" src="https://user-images.githubusercontent.com/30042226/193598646-87bf9eed-4e76-414b-a50f-8df235b96dd5.png">

It looks like we could use Open Sans for

Russian
Ukrainian
Karakalpak

We may need to increase the font size slightly, eg from 10 to 11 on a Word processor.
