### ISSUE TITLE
Attachments from RapidPro

### ISSUE THREAD

**Issue by ehmadzubair** [unicef/iogt#140]
Significant amount of work related to RapidPro Bot is done in #130. Attachments from RapidPro however are tricky. There are mainly two issues with attachments right now:
## 1. Attachments aren't parsed 'out' from the message body
Attachments need to be parsed from the message's body and show up as preview-able content for (Image, Video and Audio files)

## 2. Attachments do not live on the IoGT Server
IoGT is intended to be free-to-use for all users. However, data charges are incurred for any external links/resources. To mitigate this, we have to come up with a strategy to download attachments on the IoGT server and replace external links with internal ones. Other ideas are welcome too.

**Comment by ehmadzubair** [comment]
cc: @dannyparsons @geoo89

**Comment by dannyparsons** [comment]
Thanks, yes agree with the approach for 2.

**Comment by ehmadzubair** [comment]
I think we can close this ticket. There is another ticket which is related to the bugs from the RapidPro bot.

cc: @geoo89
