### ISSUE TITLE
IoGT Kenya is not tracking traffic on Google Analytics

### ISSUE THREAD

**Issue by lenkada** [unicef/iogt#1406]
Problem:  Data collection for the IoGT Kenya site stopped around the time v2.0 launched. 
Context:  Historically, when analytics drops, this is fixed with a server refresh.

Reported by:  @lauriemarkle 
@istride kindly take a look:

![image](https://user-images.githubusercontent.com/113142748/190432461-3fbced21-05e7-44d7-bb06-7c34de610da0.png)

**Comment by istride** [comment]
I have not been able to find anything obviously wrong with the tracking. Everything seems to be working as expected insofar as the app appears to be sending data to Google, and it is being accepted.

@lauriemarkle Would you confirm that the tracking code is set correctly in _Site Settings_?

Other things to consider are:

- Is there a similar drop-off of tracking on other sites that have been migrated to v2?
- Tracking is also occurring under a 'global' tracking code; is this being affected too?

**Comment by lauriemarkle** [comment]
Hi @istride - I've done some further digging. A few discoveries that might help: 

- Analytics stopped capturing on July 20, 2022, the same day that Kenya launched 2.0
- No other site that has migrated to v2.0 has this same problem. 
- In the site GA TRACKING CODE SETTINGS, the Kenya site was set to track a different code that wasn't listed in Analytics. I'm not sure where this old number came from, but was obviously formed during the initial launch (recall that Kenya was the first 2.0 launch). I've updated settings on the Kenya site and now see data coming through.
-
<img width="297" alt="image" src="https://user-images.githubusercontent.com/74552270/190698156-0709e49c-9e98-4679-9fbc-b605ff6d0154.png">
<img width="1216" alt="image" src="https://user-images.githubusercontent.com/74552270/190698718-87af979e-ab02-429a-a1a9-1277fc5990e6.png">
