### ISSUE TITLE
Ability to customize resizing of images across platform

### ISSUE THREAD

**Issue by cbunicef** [unicef/iogt#1453]
As a PLATFORM ADMINISTRATOR I would like more control over how images are resized on my platform. For example, I might want all my images to show at a high resolution if I am publishing content to be read by users who have strong internet connections, or I am publishing content with small visual details that are important.

Suggested implementation - a setting in Site Settings where the default maximum width of images can be customized, which replaces the current default of 360px.

**Comment by Alihassanc5** [comment]
@cbunicef there is a special case,
In Section Listing other than first content then the width of image is 180px. 

Possible Solutions:
- Divide the maximum width of image by 2. (e.g, first-content: 360px; other-content: 180px)
- Another setting to set the width of other images.

**Comment by cbunicef** [comment]
The size of that image as it's shown to the user is tied to the CSS. If it's not too complicated, it would be better to have the CSS code decide the resized width of the image. Ie the CSS code says the image is 50% width, so the image is resized to 50% width of the standard width ie 360px -> 180px

However, to me that does sound complicated. The other good option is letting the user manually set that width and giving the help text

"On Section Pages each of the sub-Pages are listed with their title alongside their Lead Image. By default the Lead Image is 50% of the width of the page, so normally you can set this image size to half of the width for full images. For example if your full image width is 360px then this can be set to 180px. If you are using a custom CSS you might need to set this to another size."
