### ISSUE TITLE
Questionnaire field type "Drop Down" defaults to the first Option provided

### ISSUE THREAD

**Issue by cbunicef** [unicef/iogt#1457]
When a user opens a questionnaire, the Drop Down fields are initially set to the first Option provided in the Questionnaire setup.

This is a problem because users may look past those fields and press submit, and their submission will reflect an answer they didn't give. It's also a problem because users aren't able to give NO answer on those questions, because there is no blank value.

The first option in a Drop Down field should be a blank option, that doesn't need to be set up in the Admin Panel. It appears in the Drop Down field when the user loads the page, and it is also a selectable option in the Drop Down field list.

If the user doesn't select anything, or selects the blank option, within the response appears in the data the same as on a Radio Button field where nothing is selected.

If the field is required, and the user doesn't select anything or selects the blank option, the user should be required to give a response that is NOT blank.

**Comment by cbunicef** [comment]
@sheralim012 This is slightly different than we discussed. We should have a blank option in the Drop Down so that users could change their response to be blank if the field is optional and they previously selected a non-blank option.

**Comment by Alihassanc5** [comment]
@cbunicef currently it is showing stats for radio buttons If the user doesn't select anything, or selects the blank option.
![image](https://user-images.githubusercontent.com/62539376/201069557-9fccbae6-f1d3-4fac-872e-28ba2c46f91e.png)

Do you want the same response for drop down?

**Comment by cbunicef** [comment]
@Alihassanc5 Thanks for uncovering this, this would be a bug. I will add a separate issue
