### ISSUE TITLE
In Section Page, if a listed Page doesn't have a Lead Image then the Title text should be extended across the column

### ISSUE THREAD

**Issue by cbunicef** [unicef/iogt#1469]
As a USER, it looks strange seeing a list of Pages (which have no Lead Image) with the Titles only appearing in the left half of the column and the right half of the column blank. It would look better to extend the Title text across the column when there is no Lead Image for a Page.

**Comment by cbunicef** [comment]
Per convo, thanks for the quick work on this @sheralim012 and @istride 

Current:
![image](https://user-images.githubusercontent.com/30042226/214579251-fd479c27-df85-4018-96cf-6d812d342805.png)

Desired:
![image](https://user-images.githubusercontent.com/30042226/214579770-855a71b5-d911-413b-8f1e-d5aa024eb032.png)

**Comment by sheralim012** [comment]
The same thing is true for the homepage's featured content - Articles.
