### ISSUE TITLE
Cannot create survey with skip logic

### ISSUE THREAD

**Issue by edmoss345** [unicef/iogt#1489]
Trying to create a survey with some skip logic. When I try and make the page I get the warning message around validation errors, but there is no prompt in the form below saying where the error is coming from.

I believe I have set everything up correctly for the skip logic, @sheralim012 am I missing something obvious?

![image](https://user-images.githubusercontent.com/69303397/207625220-41afd73e-7640-4778-be90-a7c1c5e92699.png)

**Comment by edmoss345** [comment]
Reading the user manual I found what I had been doing wrong, I had a default question in there as one I could potentially skip. So skip logic is working fine, it's just that we need some validation messages to let the user know (me in this case) what they're doing wrong!

**Comment by sheralim012** [comment]
This has been introduced due to the wagtail version upgrade,
It seems like the streamfield/streamblock error mechanism has been changed,
Woking on the fix.
