### ISSUE TITLE
"Live" button when editing a translated page goes to wrong URL

### ISSUE THREAD

**Issue by dannyparsons** [unicef/iogt#149]
When editing a translated page in translation mode the "Live" button in the top right always goes to `localhost/...` 
e.g. `http://localhost/fr/emergency-information/dans-covid-19/nutrition-tips-during-covid-19/` 

even on a deployed site where the link should be 

`https://iogt.site/fr/emergency-information/dans-covid-19/nutrition-tips-during-covid-19/`

When you choose "Stop translating" the "Live" button now goes to the correct link.
![image](https://user-images.githubusercontent.com/11214914/123469118-8e378980-d5ea-11eb-96f5-82742cd8b710.png)

**Comment by sheralim012** [comment]
@ChrisMarsh82 this is done, you can close it.

**Comment by geoo89** [comment]
Confirmed this is fixed.
