### ISSUE TITLE
In Wagtail 2.15.6, the Admin Panel Pages sort button is missing

### ISSUE THREAD

**Issue by cbunicef** [unicef/iogt#1496]
In Wagtail 2.11.9

![image](https://user-images.githubusercontent.com/30042226/209716748-29968153-0d7a-4ba4-a60e-e458d5b22dc4.png)

In Wagtail 2.15.6

![image](https://user-images.githubusercontent.com/30042226/209716691-6cc06533-dccf-43f1-b64a-328bf42d7c0f.png)

**Comment by cbunicef** [comment]
@sheralim012 Calling you attention to this since we're not meeting this week

**Comment by sheralim012** [comment]
In newer versions, wagtail has changed the way this functionality is presented and used,

Click on the "MORE" menu item 
<img width="490" alt="Screenshot 2022-12-28 at 3 52 24 PM" src="https://user-images.githubusercontent.com/49383675/209802319-0eb99499-3b42-4189-8c97-539e791ffa5e.png">

"SORT" functionality is available now
<img width="489" alt="Screenshot 2022-12-28 at 3 53 13 PM" src="https://user-images.githubusercontent.com/49383675/209802362-6878dcb4-00d7-408f-8259-b70703d54393.png">

Click on "SORT" column header to close the functionality
<img width="495" alt="Screenshot 2022-12-28 at 3 53 39 PM" src="https://user-images.githubusercontent.com/49383675/209802398-5537bc21-1a8b-4adc-ad29-226bbfd6ff26.png">

**Comment by cbunicef** [comment]
Thanks @sheralim012 I see it there as well.

I feel pretty strongly that it's not obvious for Sort to be included in that menu, since the other menu options (Delete, Move, Unpublish, Translate)
- all affect about the Page itself
- are all actions, rather than Sort which is an interface toggle

"Sort menu order" is also a pretty bad name.

Could we restore the Sort function as it was, alongside the multi-select which is think is pretty useful? I'm fine to keep it in the menu as well. If we can't restore that function, maybe we can add a button with the same function as the menu item?

![image](https://user-images.githubusercontent.com/30042226/209827813-cfa8a0be-85d4-467f-82e4-546b0ae74c02.png)
