### ISSUE TITLE
In Wagtail 2.15.6, "Recommended Content" is not an option in Admin Panel when editing Articles

### ISSUE THREAD

**Issue by cbunicef** [unicef/iogt#1497]
In Wagtail 2.11.9

![image](https://user-images.githubusercontent.com/30042226/209717388-5ee8cd52-4907-4059-90de-612169ab5bf8.png)

In Wagtail 2.15.6

![image](https://user-images.githubusercontent.com/30042226/209717356-4823cdb4-6fc8-48b4-8db1-833f31a801e8.png)

**Comment by cbunicef** [comment]
@sheralim012 Calling you attention to this since we're not meeting this week

**Comment by sheralim012** [comment]
looking into it
