### ISSUE TITLE
As the CMS editor, I can create at least 4 children sections and support orphaned content.

### ISSUE THREAD

**Issue by lauriemarkle** [unicef/iogt#15]
The CMS should allow for Section > Sub-section > Sub-sub section > Sub-sub-sub section > article/poll/survey/quiz. Content can appear within any of the aforementioned parent sub-sections. Content can also be orphaned such that select pages are only accessible through direct link.

**Comment by dannyparsons** [comment]
Section and any number of sub sections with content at any position is available.

@lauriemarkle Could you explain how the process of how you currently "orphan" content e.g. an article such that it's not associated to any section? Would this just be a child of the Home page directly?

**Comment by dannyparsons** [comment]
This is done by creating a draft section called "Orphaned" and adding articles as children to the draft section. It's important that this feature is still available.

**Comment by dannyparsons** [comment]
Section and subsections can be defined as needed. Orphaned articles can be defined as was possible in v1
