### ISSUE TITLE
#menu anchor on Homepage is missing in 2.15.6

### ISSUE THREAD

**Issue by cbunicef** [unicef/iogt#1506]
The default flat menu setup which is default for sites includes a link to the anchor, these seem to be universally not working now.

**Comment by cbunicef** [comment]
@ChrisMarsh82 @istride @sheralim012 This is an urgent priority affecting all sites, how quickly can we address this?

**Comment by ChrisMarsh82** [comment]
@cbunicef We aim to deploy this Monday and will let you know if there are any issues.

**Comment by ChrisMarsh82** [comment]
@cbunicef this fix is now on Sandbox
