### ISSUE TITLE
Questionnaire editor not giving feedback when form is invalid

### ISSUE THREAD

**Issue by cbunicef** [unicef/iogt#1528]
I created a survey which included skip logic.

I forgot to remove the Required setting from questions that could be skipped.

I received a popup "Cannot be saved because of invalid format", but there was no indication of what was invalid - as I would usually expect there to be a red color help text highlighting the error.

**Comment by Alihassanc5** [comment]
@cbunicef It's already pointed out in #1489, it will be fixed by #1495.
