### ISSUE TITLE
Enable data API pagination by default

### ISSUE THREAD

**Issue by cbunicef** [unicef/iogt#1537]
The data API should be paginated by default at an appropriate number - let's say 15, same as the Admin Panel. There should be the optional URL argument 'page_size' where the user can specify a huge number to essentially turn off pagination (already in place).

This applies to the questionnaires list and submissions list endpoints, and to future endpoints which are lists.

@istride @sheralim012 This seems like it may be very important for the current response.

**Comment by ChrisMarsh82** [comment]
Max page size and default page size to be configurable on the deployment.

**Comment by ChrisMarsh82** [comment]
Default 15, Max 100
