### ISSUE TITLE
Remove the Add Survey and Add Poll button from Survey and Poll admin pages

### ISSUE THREAD

**Issue by dannyparsons** [unicef/iogt#155]
Surveys and Polls will be added directly from the Pages section. The "Add Survey" and "Add Poll" buttons on the Survey and Poll pages which has radio buttons for the parent section is not very user friendly and not needed so these buttons should be removed.

**Comment by sheralim012** [comment]
@ChrisMarsh82 this isn't done yet.

**Comment by ehmadzubair** [comment]
Removing the "Add" button from Quizzes as well
