### ISSUE TITLE
Lead Images don't get featured when sharing on WhatsApp, Telegram

### ISSUE THREAD

**Issue by cbunicef** [unicef/iogt#1552]
Not sure if this is an issue across digital messengers, but when a Page is shared there is only a URL, or only a URL and a title. 

Some alternate examples, Reddit example is ideal for when we have a Lead Image, Gizmodo is ideal for when we do not:

![image](https://user-images.githubusercontent.com/30042226/220170583-fc2eada1-31fd-4ccb-b260-89d22747170b.png)

This is the behavior pressing the Share button within Firefox on an iPhone.

**Comment by cbunicef** [comment]
Here are platforms to consider for now:

- WhatsApp
- Facebook / Facebook Messenger
- Instagram

For a second round:
- TikTok
- Snapchat

**Comment by istride** [comment]
We should probably be making use of the fields that appear in the 'Promote' tab for each page, namely 'Title tag', 'Meta description', and possibly 'Tags' ('metadata' section) - see screenshot below. My suggestion is that we should use the values here first, then have a sequence of fallbacks, for example:

- Title: (Promote) title tag, (Content) title
- Description: (Promote) meta description, \<derive from body text\>, site name (?)

At the moment, the current PR uses the page title only as the title, and uses 'Internet of Good Things' (hard-coded) as the description, which I think is too limiting and misses an opportunity to use the promotional features of IoGT.

![Screen Shot 2023-04-25 at 12 21 46](https://user-images.githubusercontent.com/553684/234266630-fdd62aa3-6a2f-4dcd-bd3e-ec29a11857d6.png)

**Comment by istride** [comment]
@cbunicef do you agree with my suggestion, above?

**Comment by cbunicef** [comment]
Yes this is fine, let's just please make sure to update the description of the relevant Promote tab fields so it's clear they are used when sharing on social media as well.

**Comment by cbunicef** [comment]
Title Tag: "The name of the page displayed on search engine results as the clickable headline, and automatically loaded as a title into shares on social media eg Facebook Posts or shared links in WhatsApp."

Meta description: "The descriptive text displayed underneath a headline in search engine results, and automatically loaded as a description into shares on social media eg Facebook Posts or shared links in WhatsApp."
