### ISSUE TITLE
Features to add to Polls

### ISSUE THREAD

**Issue by dannyparsons** [unicef/iogt#157]
Frontend:
- [x] Bugfix: Checkboxes options are not displayed.
- [x] Bugfix: Radio button options are not clickable.
- [x] Bugfix: Display custom description that was set in admin backend 
- [x] Bugfix: Display custom thank you message that was set in admin backend rather than generic "THANK YOU FOR YOUR 
RESPONSE!" message
- [x] If a poll has the option set to display totals rather than percentages, don't put a '%'-sign after the totals.
- Support for "(single) Checkbox" fields. They currently crash the page upon submitting. Now in #339
- [x] When input type "checkbox" is set as "required" in the backend, when submitting, the error message "This field is required." is displayed regardless of whether it is checked or not, making it impossible to complete the survey.
- [x] When input type "checkbox" is set as "required" in the backend, the info text is "CHECK ALL THAT APPLY".
- [x] Radio buttons have "1.", "2.", etc displayed in front of the options. Should be removed.

Backend:
- Now #360
- [x] Support for anonymous submission (if specified in the backend).

**Comment by geoo89** [comment]
Everything remaining is part of a new issue now.
