### ISSUE TITLE
RapidPro chatbot channel - 500 from IoGT when RapidPro sends message

### ISSUE THREAD

**Issue by sheralim012** [unicef/iogt#1575]
Currently, we are using "IntegerField" for rapidpro_message_id in the Message model, it can only hold numbers between this range -2,147,483,647 to 2,147,483,647.
An error is raised when we try to put a value outside this range.
Use "BigIntegerField" instead which has a lot more range -9223372036854775808 to +9223372036854775807. And this is the default in newer versions of Django for primary keys.

**Comment by istride** [comment]
The message IDs that RapidPro sends back to IoGT are much larger than can fit in the IoGT database. The solution is to migrate the message ID field from `IntegerField` to `BigIntegerField`.
