### ISSUE TITLE
Paging through Images not working in popup dialogue

### ISSUE THREAD

**Issue by cbunicef** [unicef/iogt#1583]
When editing a Flat Menu: https://kindweb.org/admin/wagtailmenus/flatmenu/edit/4/

I click on Image Icon: Choose an image

I click on the Next button in the dialogue to continue to the next page of images

![image](https://user-images.githubusercontent.com/30042226/226168918-8138fc94-ddf2-4a90-9cf0-9770cb98d09d.png)

But nothing happens.

**Comment by Alihassanc5** [comment]
@cbunicef This issue will be resolved after upgrading the version of Wagtail.

**Comment by cbunicef** [comment]
@istride I received a report today from a user that this is still an issue
