### ISSUE TITLE
submit_time format changed on API

### ISSUE THREAD

**Issue by cbunicef** [unicef/iogt#1599]
Previously submit_time was in 

2023-04-26T09:18:51.987000Z

format, but now appears in this format

2023-04-26T11:10:28.369727+02:00

For example on https://ss.goodinternet.org/api/v1/questionnaires/293/submissions/?page=2&page_size=100

I'm not sure if the new format is more accurate? But it isn't recognized by Power BI as a datetime, which causes problems.

**Comment by cbunicef** [comment]
@sheralim012 @istride flagging this as it affects outside systems

**Comment by istride** [comment]
The intention is for timestamps to be in UTC in all API responses i.e. let's get it back to what it used to be.

**Comment by cbunicef** [comment]
FYI, if helpful, this was first identified during an automated refresh of a Power BI report on 3 May at 4PM CET.

**Comment by cbunicef** [comment]
Thinking again - right before this issue happened, someone accidentally unpublished all the content on the site. I then re-published the content, including the survey where the submit_time changed. Maybe un-publish and re-publish has something to do with it?
