### ISSUE TITLE
As the CMS editor, I can set pages & sections to public, private to select user groups, or password-protected.

### ISSUE THREAD

**Issue by lauriemarkle** [unicef/iogt#16]
In the current CMS, editors can set any section, sub-section, article, survey other content's view permissions as follows: 
![image](https://user-images.githubusercontent.com/74552270/108702697-aacb9400-751a-11eb-86b6-ae7c817a36e2.png)
This feature is used frequently and should remain. It is an important part of our 'proofing' which allows us to have content on the site under review by the Ministry without public visibility.

**Comment by istride** [comment]
Wagtail feature on all `Page` objects, which remains unchanged in the latest LTS version.

**Comment by dannyparsons** [comment]
Tested and working in current development version.
