### ISSUE TITLE
When translating a page - MultipleObjectsReturned

### ISSUE THREAD

**Issue by Alihassanc5** [unicef/iogt#1604]
## Steps to reproduce the issue
- create locales L1, L2, L3
- create a page P1 in locale L1
- translate page P1 to locale L2 (let's say the newly translated page is P1')
- translate page P1' to locale L3 (let's say the newly translated page is P1'')
- delete page P1''
- translation P1 to locale L3
- you will be redirected to edit page with error `MultipleObjectsReturned - get() returned more than one TranslationSource -- it returned 2!`

## Solution
- Currently we have wagtail-localize: 1.2.1 and Django: 3.1.14
- It will be fixed in newer version of wagtail-localize: 1.3.3 and Django: 3.2

**Comment by istride** [comment]
- Upgrade packages (ensuring compatibility with Wagtail)
- Create a script/management command to detect this issue and report instances for a particular site

Current thinking is that any problems that exist before this fix will need to be cleaned manually.
