### ISSUE TITLE
Missing migrations for release 2.3.6

### ISSUE THREAD

**Issue by istride** [unicef/iogt#1616]
Logs in production show that there are missing migrations in the latest release.

```
Running migrations:
  No migrations to apply.
  Your models have changes that are not yet reflected in a migration, and so won't be applied.
  Run 'manage.py makemigrations' to make new migrations, and then re-run 'manage.py migrate' to apply them.
```

This must be addressed before the next release.

How can we avoid this happening again?

**Comment by Alihassanc5** [comment]
The issue is caused by incremented package version of django-translation-manager 1.3.0 which is incompatible with our current django version 3.1.*

**Comment by Alihassanc5** [comment]
It would be fix in the next release because we are using Django 3.2.* now, additionally we will lock the dependencies using pip-tools to avoid this issue in future.
