### ISSUE TITLE
Pip-tools for efficient package dependency management

### ISSUE THREAD

**Issue by Alihassanc5** [unicef/iogt#1618]
The integration of Pip-tools offers several advantages, including automatic resolution of package version conflicts, easy management of pinned package versions, and the ability to generate hashed package requirements for improved security.

**Comment by Alihassanc5** [comment]
@istride Do we need to update the package versions or should we proceed with the current versions?

**Comment by istride** [comment]
Let's just lock the current versions first, then we can manage any upgrades going forward.
