### ISSUE TITLE
Incompatibility of wagtailmenus with Django 3.2

### ISSUE THREAD

**Issue by Alihassanc5** [unicef/iogt#1619]
The current version of wagtailmenus (3.1.3) is not compatible with Django 3.2. This compatibility issue is causing the generation of migration files that could potentially create problems in the future.

**Comment by Alihassanc5** [comment]
@istride, I have been considering the idea of forking wagtailmenus to 3.1.3 and incorporating the necessary modifications to make it compatible with our project.

**Comment by istride** [comment]
I think the quickest and most manageable thing to do would be to:

- undo the most recent db migrations that haven't been released yet
- set `DEFAULT_AUTO_FIELD = 'django.db.models.AutoField'`
- optionally, upgrade to BigAutoField on per-app basis

https://dev.to/weplayinternet/upgrading-to-django-3-2-and-fixing-defaultautofield-warnings-518n

**Comment by Alihassanc5** [comment]
For this we need to downgrade our django and wagtail-localize versions back to 3.1.* and 1.2.1 respectively.
