### ISSUE TITLE
Page link block in body of article should have editable link text

### ISSUE THREAD

**Issue by dannyparsons** [unicef/iogt#164]
When inserting a page link as a block in the body of an article the link text should be editable - default as the page name.

The field should also be renamed to "Page Button" as it will be displayed as a button.

**Comment by sheralim012** [comment]
@dannyparsons setting default link text as page name in wagtail CMS would require us to override article edit template and use some javascript to manually add page name in field

an easier solution would be to override block rendering template and if the link text is empty then just use page name.

Let me know with which option you want me to implement

**Comment by dannyparsons** [comment]
The second sounds like a sensible solution to this. Thanks.
