### ISSUE TITLE
Markdown block in Article Page editor has invisible icons

### ISSUE THREAD

**Issue by cbunicef** [unicef/iogt#1683]
This appears to have become an issue at some point during our upgrades:

![image](https://github.com/unicef/iogt/assets/30042226/9829158d-e6f3-4bea-b604-e45fecf1124e)

**Comment by istride** [comment]
The Content Security Policy is preventing the browser from downloading the component that provides the icons (Font Awesome). There is [a fix](https://github.com/torchbox/wagtail-markdown?tab=readme-ov-file#custom-fontawesome-configuration---autodownload_fontawesome) that requires some minor customisation of the Wagtail admin.
