### ISSUE TITLE
Server error when using Import tool

### ISSUE THREAD

**Issue by cbunicef** [unicef/iogt#1684]
Receiving an generic Internal server error when trying to import from the global site

Root > English homepage > Sandbox > IIPC Training Package

to sa.goodinternet.org

Root > English homepage > Sandbox

So that it ends up in the sa.goodinternet.org Sandbox.

**Comment by istride** [comment]
The logs on the global site show an error message that is related to the upgrade to Wagtail 3. Specifically, one of the Wagtail settings was renamed from `BASE_URL` to `WAGTAIL_BASE_URL` in v3. The Wagtail Transfer component has not been upgraded yet, and it uses `BASE_URL`, which is now no longer available.

Later versions of Wagtail Transfer have compensated for this change, so we need to upgrade to a version ([0.8.5](https://github.com/wagtail/wagtail-transfer/releases/tag/v0.8.5)) than is compatible with Wagtail v3 while maintaining the [customisations](https://github.com/wagtail/wagtail-transfer/compare/main...IDEMSInternational:wagtail-transfer:enh/show-error-for-unimported-referenced-pages) we have made for IoGT.
