### ISSUE TITLE
Features to Drop in New CMS

### ISSUE THREAD

**Issue by lauriemarkle** [unicef/iogt#17]
Pages > Personae
Settings > Site Permissions

**Comment by usodhi** [comment]
Note: the features in the original issue (personae and site permissions) probably shouldn't be removed yet - addressed in #44 

Features to definitely drop: 
Settings > Timezone object
Article > Promote > Common page configuration

Features to probably drop unless we figure anything out about them (and don't seem to be high priority):
CMS landing page > Personalised pages - couldn't find anything about it, my best guess is it's something to do with segmentation
Article > Tags for navigation - it looks like we can attach tag pages that were defined in the Pages > Tags subsection, but I don't really know what it does
Article > Social media - no idea what this does
Article > Reaction question - like tags, requires a link to a reaction question page, but doesn't seem to do anything
Article > Promote > Topic of the day - didn't seem to produce any visual change anywhere
Article > Promote > Featuring in latest - same as above

**Comment by ehmadzubair** [comment]
@ChrisMarsh82 can we do a discussion on this some time?

**Comment by dannyparsons** [comment]
@ehmadzubair I believe it was sensible to drop these features. They appear to all be non-functional features in v1. I have added separate issues to discuss personae, segmentation, tags and reaction questions in case they need to be discussed still.

Is there anything else here you think should be discussed before closing this issue?

**Comment by ehmadzubair** [comment]
Nope :)

**Comment by ChrisMarsh82** [comment]
All issues captured else where
