### ISSUE TITLE
As a CMS editor, I can load banner images such that content is promoted / featured on the IoGT homepage.

### ISSUE THREAD

**Issue by lauriemarkle** [unicef/iogt#2]
Examples of current sites relying on banners include: 
ec.goodinternet.org
zw.goodinternet.org
sa.goodinternet.org
pacific.goodinternet.org

In the CMS, a banner section allows the editor to add, remove, & reorganize banners. Current banner upload screen is pasted below. All fields remain. 

Adding subtitle text results in the appearance of text at the bottom of the rotating banner on java-enabled sites. 

Features to drop include: 
Settings > Show in Menu
Settings > Search Description
Promote

![image](https://user-images.githubusercontent.com/74552270/108394055-575cfb80-7225-11eb-94dd-95641415e6ab.png)

**Comment by dannyparsons** [comment]
@lauriemarkle Do you have ideas of how banners might look on larger devices e.g. desktop? I would think banners going across the full width of a large screen might not look great.

We could discuss this in our meetings next week. We also have a designer on board who could come up with some design ideas if that would be useful.

**Comment by dannyparsons** [comment]
Rotating banners is one option.

**Comment by dannyparsons** [comment]
Banners can be created from the Banner Index Page:
![image](https://user-images.githubusercontent.com/11214914/122745030-7ecdde80-d280-11eb-86aa-de4db08ac432.png)
![image](https://user-images.githubusercontent.com/11214914/122745129-960ccc00-d280-11eb-9f24-1336b155ece5.png)

The homepage has a Banners section where banners to appear on the homepage can be chosen and ordered:
![image](https://user-images.githubusercontent.com/11214914/122745407-dff5b200-d280-11eb-83aa-82cdbdc4334a.png)
