### ISSUE TITLE
As CMS Editor I can move content pieces (sub-sections, articles, polls, surveys, quizzes) on the site

### ISSUE THREAD

**Issue by lauriemarkle** [unicef/iogt#20]
The current reorganization feature in the CMS works well. CMS editors can select any content from the site and move it and all subordinate pages: 
![image](https://user-images.githubusercontent.com/74552270/108708075-02213280-7522-11eb-87dc-20cf42729c56.png)
When "Move" is selected, you're taken to a page where you can navigate to the parent section or sub-section that you want to move content to. 

It might be better, however, to have a master site heirarchy that allows editors to drag-and-drop sub-sections around. This would be easier for site managers at country office level to manage independently.

**Comment by dannyparsons** [comment]
Tested and the current dev version has the same functionalities as described for v1.

An improved drag-and-drop interface could also be investigated as an enhancement to this.

**Comment by dannyparsons** [comment]
Moving this to v2.1 milestone where potential drag-and-drop interface could be investigated.

**Comment by dannyparsons** [comment]
Closing this as main Move feature is available and created new issue for possible drag-and-drop improvement in #123
