### ISSUE TITLE
Tag static front end text for translation

### ISSUE THREAD

**Issue by dannyparsons** [unicef/iogt#217]
Any hard-coded text in the front-end needs to be tagged so that it will be translated when viewing the site in different langauges.

There are two cases:

- in HTML templates text should be tagged with `{% trans %}` template tag e.g. `{% trans "Login by signing in below." %}`
- in Python code (including models.py, views.py and elsewhere). Use the following:

```python
from django.utils.translation import gettext as _
my_text = _("Welcome")
```

This should display as the original string currently until the translation files have been added.

**Comment by sheralim012** [comment]
@ChrisMarsh82 I think @geoo89 can comment on this better.

**Comment by geoo89** [comment]
Note: Initial work on this was done in PR #250
