### ISSUE TITLE
Implementation of analytics

### ISSUE THREAD

**Issue by isedwards** [unicef/iogt#22]
Implement Google Analytics and/or investigate a suitable alternative.

Currently access to Google Analytics is not giving updated/full information.

Some results are not currently appearing in Google Analytics and are being manually added to data studio.

- Frequently visited sections
- Types device
- User time on site
- Bounce rate

RapidPro is is using PowerBI.

There is a Google Analytics -> PBI plugin.

Poll and survey data analytics

**Comment by dannyparsons** [comment]
Agreed with Laurie that we will stick with Google Analytics for v2 and investigate and look at introducing PowerBI from v2.1.

**Comment by isedwards** [comment]
@lauriemarkle - The old IoGT sites use Google's original Universal Analytics (UA).  Are you happy for us to swtich over to the new version 4 of Google Analytics instead?  The latest version takes a modified approach, so the metrics are not identical - but now seems like a very good time to switch over.

Version 4 tracks all events for each user on the website instead of creating a summary for a user's session. It has fewer fixed/default reports, but has a more powerful way to perform analysis of the user's interactions with the sites.

Also - are you using Facebook tracking?

**Comment by lauriemarkle** [comment]
Hi Ian,
Yes, let's make the switch. I agree that now is the right time. The
challenge will be the loss of CO dashboards, but I think there's a remedy.

We get access to a Facebook Partners Portal for Free Basics. It incorrectly
tracks traffic, so I don't use it for this purpose. It only is used to map
IoGT CO URLs with Free Basics portals globally. This should not be
impacted.

**Comment by mikowhy** [comment]
GA settings [implemented here](https://github.com/unicef/iogt/issues/32)
