### ISSUE TITLE
As CMS editor, I can add / edit / save to draft / publish articles with robust features for promotion. 

### ISSUE THREAD

**Issue by lauriemarkle** [unicef/iogt#25]
As CMS editor, 
I can add articles to any parent section or sub-section. **Article features which currently exist and should remain include:** 
- [x] Title
- [x] Feature Image
- [ ] Tags
- [x] Body (with pre-formatted features for lists, numbered lists, text, images, media, and page links)
- [x] Commenting Settings
- [ ] Recommended Articles
- ~~[ ] Recommended Section~~ (Edit by @dannyparsons: Not needed, see response from Laurie: Better to have a single recommendation and the editor can pick whether the link takes the user to a section or article)
- ~~[ ] Featuring in Homepage~~ (Edit by Danny: in discussion with Laurie agreed that this moves to a setting on the homepage instead of setting on each article)
- [x] Status (Publish, Draft, Unpublished)
- [x] Privacy
- [x] Edit Lock
- [x] Go Live Date Time / Unpublish Date Time

**Features which should be removed include:** 
- [x] Article > Content > Subtitle
- [x] Article > Promote > Feature in Latest
- [x] Article > Promote > Featuring in Section

**TBD Existing Features with Unknown Functionality**
-Social Media
-Tags for navigation
-Reaction Questions
- Article > Promote > Topic of the Day
- Article > Promote > Metadata
- Article > Promote > Common Page Configuration > Show in Menus
- Article > Promote > Common Page Configuration > Search Description
-
**Features which should be enhanced include:** 
- [ ] Style code should be able to be overwritten in the body 
- [x] Additional formatting options for body text including multiple header formats (right now, there's only H1 which makes text bold)
- [x] Adding a video or audio file should include an upload option, like as in images. Right now, you have to first load the files in the media section and then they can be accessed when editing pages)
- [x] Hyperlinking text to internal or external pages. Right now, inserting a page link results in the page title appearing. This is not editable. The editor should be able to link text such as "Learn more about vaccines." and link to the page "About Vaccines."
- [ ] The CMS editor should be able to insert an image and have the image appear as a hyperlink. 

**New Features Include:** 
- [ ] Add a body feature to embed a survey directly on the page - not necessarily at the bottom. 

**Nice to have Features (v3.0 beyond) include:** 
- [ ] Explore multi-column formatting for desktop view

**Comment by ehmadzubair** [comment]
@istride do you have some background on this ticket? If yes, can we get on a call to discuss this?

**Comment by dannyparsons** [comment]
@ehmadzubair I can go through this with you from the CMS editor perspective and @istride may follow up with technical details.

**Comment by dannyparsons** [comment]
@lauriemarkle Could you give an example of _Style code should be able to be overwritten in the body_? Does this just mean you can override the style of text in the body with HTML?

**Comment by dannyparsons** [comment]
@lauriemarkle Are Recommended Sections currently used and if so, it is desirable to be separate from Recommended Articles or would a single "Recommended Content" field that allows articles and sections in any order be preferable?

**Comment by dannyparsons** [comment]
Response from Laurie: 

> Better to have a single recommendation and the editor can pick whether the link takes the user to a section or article

**Comment by dannyparsons** [comment]
A use for article tags is that recent article tags could be used as the shortcut things to search by. So good to have these in place.

**Comment by istride** [comment]
@dannyparsons does that mean that tags will be an admin-only feature? do we need to consider their use by visitors of the site?

**Comment by dannyparsons** [comment]
The tags for articles would be set by the CMS admin. When a new article is published one idea is that the tags for that page appear as "Trending terms" when a user does a search that could be selected, like below. The idea being that it makes new articles easier to search for. It's just an idea at this stage but I think there will be uses for tags in some way so good to keep this feature in v2.

![image](https://user-images.githubusercontent.com/11214914/120364079-b7733b80-c304-11eb-8900-1f119b9845f3.png)

**Comment by dannyparsons** [comment]
TODO:
- [ ] Remove Featured Sections
- [ ] Be able to insert an image which is a hyperlink
