### ISSUE TITLE
As CMS Editor I can reorganize site content

### ISSUE THREAD

**Issue by lauriemarkle** [unicef/iogt#26]
This includes both the reorganization of articles, sub-sections, banners, and footers to appear in a specific order (currently done via drag-and-drop within the parent section) AND also includes moving content from one section or sub-section to another. Content moving is fine as-is, but in v3.0 and beyond it would be good to see a content hierarchy or tree within the CMS that allows for easier drag-and-drop reorganization.

**Comment by dannyparsons** [comment]
Reordering and moving content is described in #20. Banners are now selected and ordered on the homepage (#2) and footers are defined and ordered on a Footer Index Page (#19, #95).

The drag-and-drop improvement for v3 is documented in a new issue #123
