### ISSUE TITLE
Features to add to Quizzes.

### ISSUE THREAD

**Issue by geoo89** [unicef/iogt#272]
Front-end:
- [x] Support for text/number/etc input fields. Currently, they don't appear
- [x] On the landing page, when getting the answer correct for a multiple choice type question (radio, checkboxes, dropdown, multiple select), all answer options are highlighted in green, not just the correct one.
- [x] Landing page crashes when a text input type is present
- [x] Landing page crashes when a checkbox input type is present
- [x] For multi-page quizzes, on the second page, question numbering starts from 1 again (e.g. with 2 questions, one per page, on page two it displays "1 of 2 questions")
- [x] When input type "checkbox" is set as "required" in the backend, when submitting, the error message "This field is required." is displayed regardless of whether it is checked or not, making it impossible to complete the quiz.
- [x] "Replay Quiz" button does nothing.
- [x] "Back to Article" brings you back to the quiz itself after quiz completion
- "Back" button should take you to the article/section that the quiz is part of if you haven't started the quiz (currently takes you to '/'). Moved to #359
- [x] When input type "checkbox" is set as "required" in the backend, the info text is "CHECK ALL THAT APPLY". 

Backend:
- [x] Some way to indicate the correct answers for a "checkboxes" input field (which would be a list of choices, rather than a single choice)
- [x] Specify how to indicate the correct answer for a "checkbox" input field (would be true or false)
- Disable skip logic for quizzes in the backend as a temp fix for it not working in the front-end (see #292 for implementation issue) Now part of #358
- #361

Also refer to Issue #156 for backend issues common to surveys & quizzes.

**Comment by sheralim012** [comment]
@volloholic @ChrisMarsh82 confirm 6th requirement, 

What should be the behavior for the following cases
- when the quiz is a child of homepage/section/article
- when the quiz is embedded in an article

and the current behavior is to go back to where the quiz was started in all cases

**Comment by ChrisMarsh82** [comment]
The back button should take you back to the start of the quiz if already started.
If a quiz is not started it should take you back to the article or previous page.

**Comment by sheralim012** [comment]
> Front-end:
> 
> * [ ]  When input type "checkbox" is set as "required" in the backend, the info text is "CHECK ALL THAT APPLY".

#322 fixes this issue.
Also, if a checkbox field is required then users can't submit as unchecked.

> 
> Backend:
> 
> * [ ]  Some way to indicate the correct answers for a "checkboxes" input field (which would be a list of choices, rather than a single choice)

use a comma-separated list for multi-value fields.

> * [ ]  Specify how to indicate the correct answer for a "checkbox" input field (would be true or false)

use "on" or "off" as the correct answer.
#322 addresses this issue.

**Comment by geoo89** [comment]
> > * [ ]   "Back to Article" brings you back to the quiz itself, not the article/section that the quiz is part of. (TODO: double check intended behavior)
> 
> #322 addresses this issue, according to the above comment
The back link at the beginning of the page still takes you to the home page '/' though.
