### ISSUE TITLE
Render the link to download video/audio when the video/audio tag is not supported

### ISSUE THREAD

**Issue by Kishokanth-netizen** [unicef/iogt#286]
Hey @ehmadzubair in the feature phone, audio and video tags are not rendered due to a lack of support. We therefore need to give the users the ability to download these. So the ideal implementation would be - if either/both tags are not supported, we give the user a link through which they can download the content

**Comment by ehmadzubair** [comment]
I'm struggling with deciding if it should be on the backend or the frontend. Here's a [SO answer](https://stackoverflow.com/questions/3570502/how-to-check-for-html5-video-support/3577155) that shows how we can check if the video/audio tags are supported. 


@istride can you weigh in on this?

**Comment by geoo89** [comment]
Got addressed in PR #306: https://github.com/unicef/iogt/pull/306/commits/ce350a689a738e588b350563f7c078da28a5259a
Please check if this is satisfactory.

**Comment by geoo89** [comment]
Message with download link is displayed either way. I tested this on desktop with noscript, and the download links are still displayed.
