### ISSUE TITLE
As a CMS editor, I can add, edit and remove an individual user

### ISSUE THREAD

**Issue by lauriemarkle** [unicef/iogt#29]
All existing features remain. 
![image](https://user-images.githubusercontent.com/74552270/108993108-29573b80-76ab-11eb-883e-076e27d2f0f8.png)
In v3.0 and beyond it would be great to see information links next to each user group that provides a summary of the user group for the CMS editor to quickly understand user permissions assigned. 
![image](https://user-images.githubusercontent.com/74552270/108993188-468c0a00-76ab-11eb-9524-e608d8bc68d0.png)

**Comment by sheralim012** [comment]
@ChrisMarsh82 this is done and you can close this.
