### ISSUE TITLE
As a CMS editor, I can bulk upload images and organize them with folders or tags.

### ISSUE THREAD

**Issue by lauriemarkle** [unicef/iogt#3]
As CMS editor, I can visit the "Images" gallery in the CMS and bulk upload images. The image gallery currently only alllows for tags to be added _after_ images are loaded and tags must be added 1 at a time. Tags should be bulk-added as part of the upload process. If possible, it would be ideal to have better organization options for images. The bulk upload feature works well right now, but navigating through images when you want to add them onto an article is more complicated. 

![image](https://user-images.githubusercontent.com/74552270/108395063-7314d180-7226-11eb-81bb-9646217d4aed.png)

As an example, when I edit an article and attempt to add an image to the body or as a feature image, I must manually scroll through the entire library to find the image unless tags have been added to filter results. Improved navigation through this image gallery would be ideal. 

![image](https://user-images.githubusercontent.com/74552270/108394961-57a9c680-7226-11eb-98f4-0ac1b2966c2d.png)

**Comment by dannyparsons** [comment]
The images gallery allows for multiple upload of images as in v1.

The proposed solution for improved image organisation is through defining Collections. Collections allow for defining a folder structure which can be used for images, media and documents. The suggestion will be for CMS editors to first define their Collections and then add images/media/documents to those folders directly during upload as shown below.
![image](https://user-images.githubusercontent.com/11214914/122746767-416a5080-d282-11eb-92f4-a9cdbb97e150.png)

**Comment by dannyparsons** [comment]
Tags are also still available to be used if needed for organisation and search purposes, but this should be more efficient for CMS Editors through Collections.
