### ISSUE TITLE
Can report comment multiple times

### ISSUE THREAD

**Issue by geoo89** [unicef/iogt#308]
- [x] #521
- [x] #522
- [x] Double check the text to be displayed for reported comments: For moderators, `{% blocktrans count counter=item.flagged_count %}A user has flagged this comment as inappropriate. {% plural %}{{ counter }} users have flagged this comment as inappropriate.{% endblocktrans %}` or `Reported by {{ item.flagged_count }}` (the latter is currently used)? For users, `This is a reported comment` is the current text.
- [ ] #523

**Comment by ehmadzubair** [comment]
Number 2 and 3 have been addressed however, doing number 1 is a little more complicated. Do we want to defer it to v 2.0.1?

@ChrisMarsh82 @dannyparsons
