### ISSUE TITLE
Sections: Rename "Sort" column to "reorder"

### ISSUE THREAD

**Issue by pranavavva** [unicef/iogt#328]
When viewing a section page on the backend, one of the table columns is labelled "sort" but the actual functionality is to provide "grips" to reorder the child pages. It would be more clear if the "sort" column is renamed to "reorder" or similar.

<img width="481" alt="Screen Shot 2021-07-22 at 12 43 09 PM" src="https://user-images.githubusercontent.com/23485492/126676574-51e4def0-70fe-48e4-8de3-7c1fb6ad46e0.png">

**Comment by ChrisMarsh82** [comment]
This is a wagtail issue. It would be a lot of work to change

**Comment by cbunicef** [comment]
This is not critical, especially if it's a lot of work.

**Comment by ChrisMarsh82** [comment]
As this is in wagtail we will not change this
