### ISSUE TITLE
Add validation to Questionnaires for Direct Display

### ISSUE THREAD

**Issue by ehmadzubair** [unicef/iogt#329]
Direct display support is added for Questionnaires in #326. While all other questionnaires work as expected, multistep forms in particular break when they are rendered elsewhere.

We should have a validation step that prohibits editors to enable direct display in multi-step forms

**Comment by geoo89** [comment]
#6 suggests: "I assume if the survey is embedded within an article the page breaks are ignored."

**Comment by cbunicef** [comment]
We decided that after the page break the user would go to another page of the survey. So

P1 - embedded
P2 - separate page
P3 - separate page

etc
