### ISSUE TITLE
Language select menu does nothing

### ISSUE THREAD

**Issue by geoo89** [unicef/iogt#333]
- [x] The language select button the top left does not change the language.
![image](https://user-images.githubusercontent.com/678199/126847296-ab31ecb0-8215-4c3b-a3e4-08c0e2b48293.png)

Expected behavior:
- redirect to currently open page, but in the selected locale
  - e.g. if /en/users/profile/ is open and French gets selected, redirect to /fr/users/profile/
  - if that URL doesn't exist (e.g. because of different slug in different language, or page wasn't translated), redirect to home (e.g. /fr/)?

- [x] Also, should only the locales that were enabled in the admin view (Settings -> Locales) be available in the dropdown here?

**Comment by dannyparsons** [comment]
Language selection now functional. Further improvements are discussed in #372
