### ISSUE TITLE
Highlighting correct and wrong answers in quizzes

### ISSUE THREAD

**Issue by geoo89** [unicef/iogt#338]
Current scheme:
- Green tick: You picked and it was correct. 
- Red cross: You picked and it was wrong, OR you didn't pick but it was correct.
- Grey: You didn't pick it and it was incorrect
![image](https://user-images.githubusercontent.com/678199/126913402-ed190801-1249-40bb-828e-ada1653740e0.png)
Thus from the results page you cannot infer which answers are correct without knowing what you picked. 

I assume the emphasis should be on what the correct answers are, rather than on what you did wrong.

Proposal (for discussion):
Use the checkbox to indicate what was picked and color to indicate the correct answers:
- Green tick: correct and you picked it
- Green empty: correct but you missed it
- Red cross: incorrect but you picked it
- Grey: incorrect and you didn't pick it

**Comment by cbunicef** [comment]
Unfortunately for accessibility reasons we can't rely on coding the answers via colors eg red/green. I think we discussed this, but we might have missed the "Correct but you missed it" category.

**Comment by cbunicef** [comment]
Can we make this simpler by making it more clear? I feel a bit good about this format:

You chose:

> 
> right_answer_1 [check icon, alt-text "this was correct"] (item highlighted green)
> wrong_answer_1 [X icon, alt-text "this was incorrect"] (no highlight)
> 
> These other answers were correct (multi-select)/This other answer was correct (single-select):
> right_answer_2 (no highlight)
> 
> These other answers were incorrect (maybe we do or don't want this):
> wrong_answer_2 (no highlight)

I'm getting feedback on accessibility for screen reader users.

**Comment by ChrisMarsh82** [comment]
icon alt text to give further explanation. Different icon for each option.

Options:
selected and right  (highlighted and coloured tick)
selected and wrong (highlighted and coloured cross)
not selected and should be (not highlighted and clear tick)
not selected and could be (not highlighted and clear tick)
not selected and shouldn't be (not highlighted and clear cross)

**Comment by geoo89** [comment]
The answers are now highlighted like this, in accordance with the specification above:
![image](https://user-images.githubusercontent.com/678199/148676119-925e6c73-b23b-473d-accc-b4b4cd2318d7.png)

> icon alt text to give further explanation. Different icon for each option.

Can we clarify this? An alt text should be displayed when hovering over the tick/cross symbol? What should this text say, and I assume we will have to add it to the translation manager?

**Comment by geoo89** [comment]
Reopening to discuss the above question @cbunicef

**Comment by cbunicef** [comment]
C1 - "Checkbox with tick, indicating correct and selected"
C2 - "Checkbox with X, indicating incorrected and not selected"
C3 - "Checkbox with tick, indicating correct but not selected"
C4 - "Checkbox with X, indicating incorrect and not selected"
C5 - "Checkbox with X, indicating incorrect and selected"

**Comment by geoo89** [comment]
Please add alt-texts to the tick/X icons that display when hovering over and for screen reader users.

selected and right (green highlighted and coloured tick) - "Checkbox with tick, indicating correct and selected"
selected and wrong (red highlighted and coloured cross) - "Checkbox with X, indicating incorrect and selected"
not selected and should be (not highlighted and clear tick) - "Checkbox with tick, indicating correct but not selected"
not selected and could be (not highlighted and clear tick) - "Checkbox with tick, indicating correct but not selected"
not selected and shouldn't be (not highlighted and clear cross) -  "Checkbox with X, indicating incorrect and not selected"
