### ISSUE TITLE
Disable skip logic except for dropdown/radio in multi-step surveys

### ISSUE THREAD

**Issue by geoo89** [unicef/iogt#365]
Skip logic (i.e. choosing to end the survey or go to a specific question) should only apply for (1) radio/dropdown input types in (2) surveys with (3) multi-step enabled.

For other input types, for quizzes, and for surveys without multi-step enabled the skip logic dropdown (as part of the choices) should ideally be disabled/not shown, but at least be ignored. If only ignored, there should be a hint/note that it only works for radio/dropdown input types in multi-step surveys.

**Comment by sheralim012** [comment]
we can add help text for skip logic field, e.g.,

This is used to add choices for field type radio, checkbox, checkboxes, and dropdown only. This can be used to skip questions and skipping is only allowed for radio and dropdown.

something like this can be added as help text

**Comment by cbunicef** [comment]
I think we had said that skip logic will force multi-step on feature phone, but on smart phone multi-step is not required for skip logic. Or maybe I’m misremembering?

We should also have it possible for checkbox (single)




Christopher Brooks
Internet of Good Things<https://unicef.sharepoint.com/teams/PD-IGT/> – Global Lead

Email: ***@***.***

________________________________
From: Georg Os. ***@***.***>
Sent: Tuesday, July 27, 2021 4:42:33 PM
To: unicef/iogt ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [unicef/iogt] Disable skip logic except for dropdown/radio in multi-step surveys (#365)


Skip logic (i.e. choosing to end the survey or go to a specific question) should only apply for (1) radio/dropdown input types in (2) surveys with (3) multi-step enabled.

For other input types, for quizzes, and for surveys without multi-step enabled the skip logic dropdown (as part of the choices) should ideally be disabled/not shown, but at least be ignored. If only ignored, there should be a hint/note that it only works for radio/dropdown input types in multi-step surveys.
