### ISSUE TITLE
Community Moderator user group allows enrolled front-end users to assist with comment moderation.

### ISSUE THREAD

**Issue by lauriemarkle** [unicef/iogt#37]
They will have the ability to delete or respond to users with canned responses (developed by CMS editors on backend). In their profile, they can view the total number of comments moderated (total and in the last week).

**Comment by ehmadzubair** [comment]
This functionality is done already. The only thing probably left in this is to create a user group for community moderators. @ChrisMarsh82 can you close this ticket and create one for Community Moderator user group which only has access to the comments section on the admin side bar?

**Comment by ChrisMarsh82** [comment]
Community moderator - no access to the back end - moderate comments only
Moderator - as is
Editor - as is

**Comment by ehmadzubair** [comment]
@ChrisMarsh82 I think the requirements for this are a little conflicting. Laurie mentioned that moderators can respond with canned responses (developed by editors on backend). The also have the ability to view their moderated comments. Would it make sense to give them limited access to the admin panel?

**Comment by cbunicef** [comment]
The challenge is that the admin panel is not feature phone-friendly unfortunately.


[Icon  Description automatically generated]Christopher Brooks
Internet of Good Things<https://unicef.sharepoint.com/teams/PD-IGT/> – Global Lead
Email: ***@***.******@***.***>

**Comment by ChrisMarsh82** [comment]
Community Moderator needs to do admin through the front end, this should be feature phone friendly.

**Comment by geoo89** [comment]
A first draft of this has been implemented, ready for external review.

There are two levels of permissions here:
- Deleting comments in the front-end: enabled via: Object Permissions > Comment > Delete
- Add canned responses in the front-end: other Permissions > Can Moderate Comments

A community moderator group can be created and have permissions for either of both of these, without having access to the admin panel. 
Additional permissions are needed for viewing/moderating comments via the admin panel, e.g. for a full Moderator group).

Any user can report comments (no permissions needed).

**Comment by cbunicef** [comment]
Peer moderators should not have the power to "delete" comments, but rather simultaneously "hide" and "flag".
