### ISSUE TITLE
Update list of available locales

### ISSUE THREAD

**Issue by geoo89** [unicef/iogt#373]
We should have:

English
Spanish (Latin America) - es
French (West African, DRC) - fr-CG
Portuguese (Angola, Mozambique) - pt-MZ
Arabic (Morocco) - ar-MA
Swahili (Kenya) - sw-KE
Chichewa (Malawi, Zambia) - ny-MW
Kinyarwanda (Rwanda) - rw-RW
Ndebele (Zimbabwe) - nr-ZW
Shona (Zimbabwe) - sn-ZW
Kirundi (Burundi) - rn-BI
Malagasy (Madagascar) - mg-MG
Nepali (Nepal) - ne-NP
Urdu (Pakistan) - ur-PK
Kichwa/Quichua (Ecuador) - qu-EC
Russian (Russia) - ru-RU
Zulu (South Africa) - zu-ZA
Tigrinya (Ethiopia) - ti-ET
Tajik (Tajikistan) - tg-TJ
Kurdish (Sorani) - ku
Khmer (Cambodia) km-KH
Uzbek (Uzbekistan) - uz-UZ
Karakalpak (Karakalpakstan) - kaa
~~Indonesian (Indonesia) - id~~

Edit: We don't need Indonesian as this site is not being migrated to v2.

**Comment by ehmadzubair** [comment]
@geoo89 I presume this should be in progress now?
