### ISSUE TITLE
Wrong text colour when hovering on some buttons

### ISSUE THREAD

**Issue by dannyparsons** [unicef/iogt#381]
For some buttons e.g. the "Create your account" button on the login page, when you hover on it the button colour changes to black and if the text is also black the text is no longer visible. I've noticed this on two buttons which have a white background (also on the "Login" button on the Create your account page.

I suggest that for buttons with white background and black text where the button colour changes to black the text colour should change to white.

Before hover:
![image](https://user-images.githubusercontent.com/11214914/127536813-f9f8597e-e403-4138-a4a8-7b4be01cd92c.png)

During over:
![image](https://user-images.githubusercontent.com/11214914/127536669-0ec9140a-cef0-476b-ab1c-89507d2d16b9.png)

**Comment by ehmadzubair** [comment]
@adnanzahid89 can you look into this?

**Comment by ehmadzubair** [comment]
@azahid89 can you look into this?

**Comment by AdnanZahid89** [comment]
> @azahid89 can you look into this?

Sure let me

**Comment by azahid89** [comment]
> @azahid89 can you look into this?

Sure let me check this
