### ISSUE TITLE
Required fields when skipping to end of survey/quiz

### ISSUE THREAD

**Issue by geoo89** [unicef/iogt#383]
When a question with a required field is skipped using skip logic, and the end of survey/quiz is reached, rather than the responses being submitted, the user is presented with all input fields and a validation error below those fields that were required but got skipped.

If possible, the "required" should be ignored in this case.

If not, a temp solution could be that no required fields are allowed if there is non-trivial skip logic somewhere.

**Comment by ChrisMarsh82** [comment]
use a temporary solution for 2.0, revisit for 2.0.1
