### ISSUE TITLE
No description visible when embedding quiz

### ISSUE THREAD

**Issue by cbunicef** [unicef/iogt#386]
Did we decide against including the description when the quiz is embedded? I'm forgetting the details of this conversation.

**Comment by cbunicef** [comment]
Also question labels are not appearing:

![image](https://user-images.githubusercontent.com/30042226/127698879-972a389c-27f9-4475-9ea1-4bf50e90009c.png)

**Comment by geoo89** [comment]
This is already fixed in dev, the description and labels are there for embedded quizzes now.
