### ISSUE TITLE
Text on quiz is too small

### ISSUE THREAD

**Issue by cbunicef** [unicef/iogt#388]
![image](https://user-images.githubusercontent.com/30042226/127699740-b3c02781-923d-42ab-9857-86ad45301e35.png)

Users with vision difficulties will have a hard time reading this.

Can we please try increasing to the size of normal article text and see if that causes any problems?

**Comment by ChrisMarsh82** [comment]
Check on the style sheet. Move to 2.0.1 if not

**Comment by ChrisMarsh82** [comment]
https://www.figma.com/file/4QtqewQnYxgFcjVcWd0OgR/UI-Design-(Main)?node-id=490%3A4237

**Comment by ehmadzubair** [comment]
@azahid89

**Comment by geoo89** [comment]
PR #398 increases the size of the text within the selection options:
![image](https://user-images.githubusercontent.com/678199/128849745-ec5db0f8-ab0f-403f-b266-b858fa92b8c6.png)

I assume we also want to increase the text size of the prompt?

**Comment by geoo89** [comment]
Fixed by #454
