### ISSUE TITLE
Header content block text is not larger than paragraph content block text

### ISSUE THREAD

**Issue by cbunicef** [unicef/iogt#390]
Input

![image](https://user-images.githubusercontent.com/30042226/127705754-89f04ba0-8bb6-4db8-a213-cf2562a841dc.png)

Live article

![image](https://user-images.githubusercontent.com/30042226/127705725-6ec2fb95-6f98-4ded-9f79-698b7706b424.png)

**Comment by ChrisMarsh82** [comment]
These should be specified on the style sheet. If not will need to be moved to 2.0.1

**Comment by geoo89** [comment]
Now looks like this: 
![image](https://user-images.githubusercontent.com/678199/128991705-4f1081bf-95c5-49ae-b916-b8c6c2d94208.png)
