### ISSUE TITLE
Migrate users from v1 to v2

### ISSUE THREAD

**Issue by geoo89** [unicef/iogt#397]
Details and timeline TBD

**Comment by ehmadzubair** [comment]
What all do we need to migrate for users?
- User Comments
- User comments feedback
- User Poll attempts
- User Survey attempts
- User profile information
- User read/unread articles

We should also converge on the flow to reset password as part of this ticket.

**Comment by ehmadzubair** [comment]
@dannyparsons @geoo89 @ChrisMarsh82

**Comment by ehmadzubair** [comment]
@cbunicef @geoo89 

Do we set the value of `has_filled_registration_survey` as `True` for all migrated users? This would mean that they wouldn't have to fill the survey if there is one.

**Comment by geoo89** [comment]
Any user data that's in the v1 DBs should be saved in some shape or form.
So this should in particular include data from the v1 registration survey, even if we just store it in a table and don't do anything with it for now. (The registration survey in v1 is basically always defined as a subset of a set of available questions; if it contains e-mails, it might be worthwhile already transferring them into our user model. While we currently don't need to support password resets, and not all user have or will have e-mail addresses, e-mail will be the way to reset passwords in the future for those who provide one.)

**Comment by ehmadzubair** [comment]
Data to port over specific to users:

- [ ] User Group Memberships
- [ ] User Group Permissions
- [ ] User Comments
- [ ] User Comment reports (flagged)
- [ ] User Poll Submissions
- [ ] User Survey Submissions
- [ ] User Profile Details
- [ ] User Wagtail Profile Details
- [ ] User Profile Settings

**Comment by ChrisMarsh82** [comment]
Admin should be able to decide whether users with V1 registration need to complete the registration survey. This can be done at migration at a user group level.

**Comment by geoo89** [comment]
Undone accidental merge undone.
