### ISSUE TITLE
Anchors are removed from URLs when using External Links

### ISSUE THREAD

**Issue by cbunicef** [unicef/iogt#421]
Created an external link to 

http://central.iogt.site/en/sections/your-health/mental-health/keeping-mentally-healthy-self-care-tips/#its-going-to-be-alright

After the "Leaving site" warning, the destination URL is

http://central.iogt.site/en/sections/your-health/mental-health/keeping-mentally-healthy-self-care-tips/

**Comment by geoo89** [comment]
Fixed by #444
