### ISSUE TITLE
Localization for site redirection page

### ISSUE THREAD

**Issue by geoo89** [unicef/iogt#429]
When leaving the IoGT site to an external link, the user is presented with a page that reads:

"You are leaving the <b>Internet of Good Things</b> to visit an external website and standard data charges by your network provider might apply
[Continue to external site] [Back]"

We don't have translations for this string nor the "Continue to external site".
In v1, this text was embedded in a (custom?) image.

Options:
- Make this editable from Wagtail so that site admins can customize this message/page. This may be desirable for added flexibility.

I don't see any other options at this points than variations of the above.

**Comment by ChrisMarsh82** [comment]
Create an editable page.

**Comment by geoo89** [comment]
Closing this, details about the next steps in #317
