### ISSUE TITLE
Partially translated strings from Wagtail/Django

### ISSUE THREAD

**Issue by geoo89** [unicef/iogt#431]
Django and Wagtail come with strings that are available in a variety of languages (see [here](https://github.com/django/django/tree/main/django/conf/locale)), but not all the languages we aim to support:

These strings we don't have translations for nor anything close.
- [x] **A** _Sign Out_
- [x] **B** _Are you sure you want to sign out?_
- [x] **C** _You have signed out._
- [x] **D** _This field is required._: Validation error for forms (e.g. survey, quiz)
- [x] **E** _Remember me_: During login: option to stay logged in.
- [x] **F** _Enter a valid username. This value may contain only letters, numbers, and @/./+/-/_ characters._: Validation error during signup
- [x] **G** _This password is too short. It must contain at least 4 characters._: Validation error during signup
- [x] **H** _[Each language name in its respective language]_: Language dropdown menu

The most important one for site navigation is probably "Sign Out". This could possibly be replaced with a symbol.
For the others, at this stage it is probably the most sensible option to leave them as they are, i.e. in English for those languages not supported by Wagtail/Django.

There are a few more such strings. The ones we're currently aware of are validation error messages when submitting a survey/quiz/poll, and appear in small red text below the field where an invalid entry was made. These are:
- Enter a valid date/time.
- Enter a valid date.
- Enter a valid URL.
- Enter a valid email address.
- Enter a valid integer.
- Ensure this value is greater than or equal to %(limit_value)s.

A small red error message indicating where an invalid entry was made is likely still helpful, so leaving these in English for now (for the less common locales not included in django) is probably an acceptable temporary solution.

**Comment by geoo89** [comment]
Most of these solved via translation manager. What about translating each language name in the respective languages?

**Comment by ChrisMarsh82** [comment]
Complete
