### ISSUE TITLE
Features to Keep in New CMS

### ISSUE THREAD

**Issue by usodhi** [unicef/iogt#44]
**Definitely keep**:
- [x] Settings > Redirect - you can redirect paths to specific sites or pages (e.g. redirect /new to a specific poll) https://docs.wagtail.io/en/stable/editor_manual/managing_redirects.html
- [ ] Settings > Site permissions - looks like you can modify access for users to the sites specified in Settings > Sites (mentioned below), looks similar to #16. Feature mentioned in #17 
- [ ] Settings > Segment user groups - looks like a really bad UI for creating a group of used (which can later be used in segments) - could be very useful (hopefully with a change in UI if possible)
- [x] Settings > Collections - can create collections of images, documents etc. and limit access to users or groups of users – would likely be useful in conjunction with the above
https://docs.wagtail.io/en/stable/editor_manual/documents_images_snippets/collections.html

- [ ] Pages > Security questions - shows up at account registration time, we should keep it
- [x] Pages > Tags - looks like there's a way to use these tags on the backend, but I'm not sure whether it refers to these tag pages or just tags that you type in elsewhere. It seems like it could be very useful if we figure out how to use it
https://docs.wagtail.io/en/v2.0/reference/pages/model_recipes.html#tagging
https://learnwagtail.com/tutorials/adding-tags-to-wagtail-cms-pages/

- [ ] CMS landing page > Segments - looks like a way to segment users into groups based on criteria like the time or day they visit the website or the number of visits to a page of the website – data from here could be quite useful, so we should keep it
https://wagtail-personalisation.readthedocs.io/en/latest/editor_guide/segments_dashboard.html

- [x] Article > Promote > Metadata - looks like tags again using which we can do interesting things on the backend, so we should keep this
- [x] Article > Promote > Featuring in section - looks like it shows up along with the main section picture and description. For me the article I was testing on appeared in the main page with its parent page

**Maybe keep**:
- [x] Settings > Sites - I believe this may allow one to test locally and modify the site that the [LIVE] box goes to – it may be worth keeping if we can figure out how to use it
- [ ] Settings > Persona - this may be a way to collect data about what subsets of users are looking at. If that's the case, this would probably be worth keeping 
https://pypi.org/project/molo.usermetadata/

**Comment by ehmadzubair** [comment]
@ChrisMarsh82 can you help break this down into simpler tickets?

**Comment by ChrisMarsh82** [comment]
@dannyparsons  will check issues and create separate issues if needed

**Comment by dannyparsons** [comment]
Added new issues #445, #446, #447, #448 for anything unresolved here.
