### ISSUE TITLE
Security questions at login for password reset

### ISSUE THREAD

**Issue by dannyparsons** [unicef/iogt#446]
v1 has a "SECURITY QUESTION SETTINGS" under Settings > User Profile Settings. This appears to be for enabling an option to add security question(s) when a user registers on the site, which is intended to be used for allowing users to reset a forgotten password.

Am I not sure exactly how this feature works in v1 and if it is functional. It may be a useful feature for v2. It relates to the discussion here https://github.com/unicef/iogt/issues/27#issuecomment-842254447

![image](https://user-images.githubusercontent.com/11214914/128864434-222851ae-ca5f-4303-a93b-8702a371a2e1.png)

**Comment by ChrisMarsh82** [comment]
duplicate #27
