### ISSUE TITLE
Tag pages in v1

### ISSUE THREAD

**Issue by dannyparsons** [unicef/iogt#449]
v1 sites have a "Tag" page type, which can be linked to from articles. It is not clear what tag pages are for and what this feature does. It does not appear to have any visual change on v1 sites.

Is this something that is needed at all for v2?

**Comment by ChrisMarsh82** [comment]
Make sure the data isn't lost in the migration process. Don't add the functionality.

**Comment by ChrisMarsh82** [comment]
Back up all tables not being used under another prefix.

**Comment by ehmadzubair** [comment]
Rather than backing up the tables with another prefix, we will retaining the legacy database in the infrastructure as mentioned in #518 

Closing this ticket
