### ISSUE TITLE
Specify font sizes for titles, headings and paragraph subheadings

### ISSUE THREAD

**Issue by geoo89** [unicef/iogt#464]
Currently, article titles, headings, as well as H2 blocks within a paragraph all have the same size:
![image](https://user-images.githubusercontent.com/678199/129040035-c462ce1f-5200-4d32-91ce-16abaf11d8ec.png)

Is this what we want?

(From what I see in the page source, the title is H1, the heading is a custom div, and a H2 in a paragraph is a H2, so at least in principle there shouldn't be an issue giving each a different size.)

**Comment by ChrisMarsh82** [comment]
@azahid89  Make title bigger, leave H2, H3, H4 the same. Heading same as H2
