### ISSUE TITLE
Display of survey/poll/quiz if submission is prevented

### ISSUE THREAD

**Issue by dannyparsons** [unicef/iogt#471]
There are different cases this can happen and need to have the correct display:

1. If a survey does not allow multiple submissions and a submission has already been made then when you go to the page it should show the title, the description and the text "You have already completed this survey". See v1 implementation below.

![image](https://user-images.githubusercontent.com/11214914/129382849-3c38e9d5-3db6-4bcf-8f86-5f9e1d054b70.png)

2. If a poll or quiz does not allow multiple submissions and a submission has already been made then when you go to the page it should _additionally_ show the results page for that poll/quiz. (For the poll only if the option "Show results" is enabled in Wagtail.)

3. If a survey/poll/quiz requires a login and a user is not logged in then when you go to the page it should show the title, the description and a button which says "Log in to participate" which takes the user to the login page. Once logged in, the user is redirected back to the page. See v1 implementation below.

![image](https://user-images.githubusercontent.com/11214914/129382906-6ae2fb47-1a06-4886-976b-0c0a18799ca0.png)

In each case, ideally the same display should be shown when the survey/poll/quiz is embedded within an article.

**Comment by geoo89** [comment]
For reference, currently, in either case you are simply presented with the poll title and a submit button:
![image](https://user-images.githubusercontent.com/678199/129386489-f109af74-c3c1-4b0c-9932-5abc6757a0c3.png)

When embedded however, you still see the poll, but after submitting you're directed to a page that looks like the above.

I set up these polls for testing: http://iogt-django-dev.idems.international/en/sections/questionnaire-testing/anonymousmultiple-submissions/

**Comment by ChrisMarsh82** [comment]
Quiz results can be completed in a separate ticket
