### ISSUE TITLE
After deleting a section content, browser returns to the same URL which now gives a 404

### ISSUE THREAD

**Issue by cbunicef** [unicef/iogt#515]
Error:

<html>
<body>
<div id="summary" style="padding: 10px 20px; margin: 0px; border-bottom: 1px solid rgb(221, 221, 221); background: rgb(255, 255, 204); color: rgb(0, 0, 0); font-family: sans-serif; font-size: small; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><h1 style="padding: 0px; margin: 0px 0px 0.4em; font-weight: normal;">Page not found<span> </span><span style="padding: 0px; margin: 0px; font-size: 15.6px; color: rgb(102, 102, 102); font-weight: normal;">(404)</span></h1>

Request Method: | GET
-- | --
http://central.iogt.site/en/admin/pages/994/
wagtail.core.views.serve

</div><div id="info" style="padding: 10px 20px; margin: 0px; border-bottom: 1px solid rgb(221, 221, 221); background: rgb(246, 246, 246); color: rgb(0, 0, 0); font-family: sans-serif; font-size: small; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><p style="padding: 0px; margin: 0px;">Using the URLconf defined in<span> </span><code style="padding: 0px; margin: 0px;">iogt.urls</code>, Django tried these URL patterns, in this order:</p><ol style="padding: 0px; margin: 0.5em 4em;"><li style="padding: 0px; margin: 0px; font-family: monospace;">django-admin/</li><li style="padding: 0px; margin: 0px; font-family: monospace;">admin/</li><li style="padding: 0px; margin: 0px; font-family: monospace;">documents/</li><li style="padding: 0px; margin: 0px; font-family: monospace;">en/ logout_hack_view [name='logout_redirect']</li><li style="padding: 0px; margin: 0px; font-family: monospace;">en/ search/ [name='search']</li><li style="padding: 0px; margin: 0px; font-family: monospace;">en/ users/</li><li style="padding: 0px; margin: 0px; font-family: monospace;">en/ accounts/</li><li style="padding: 0px; margin: 0px; font-family: monospace;">en/ comments/</li><li style="padding: 0px; margin: 0px; font-family: monospace;">sw.js [name='sw.js']</li><li style="padding: 0px; margin: 0px; font-family: monospace;">en/ external-link/ [name='external-link']</li><li style="padding: 0px; margin: 0px; font-family: monospace;">en/ messaging/</li><li style="padding: 0px; margin: 0px; font-family: monospace;">wagtail-transfer/</li><li style="padding: 0px; margin: 0px; font-family: monospace;">sitemap/ [name='sitemap']</li><li style="padding: 0px; margin: 0px; font-family: monospace;">manifest.webmanifest [name='manifest']</li><li style="padding: 0px; margin: 0px; font-family: monospace;">^static/(?P&lt;path&gt;.*)$</li><li style="padding: 0px; margin: 0px; font-family: monospace;">^media/(?P&lt;path&gt;.*)$</li><li style="padding: 0px; margin: 0px; font-family: monospace;">__debug__/</li><li style="padding: 0px; margin: 0px; font-family: monospace;">en/ _util/authenticate_with_password/&lt;int:page_view_restriction_id&gt;/&lt;int:page_id&gt;/ [name='wagtailcore_authenticate_with_password']</li><li style="padding: 0px; margin: 0px; font-family: monospace;">en/ _util/login/ [name='wagtailcore_login']</li><li style="padding: 0px; margin: 0px; font-family: monospace;">en/ ^((?:[\w\-]+/)*)$ [name='wagtail_serve']</li></ol><p style="padding: 0px; margin: 0px;">The current path,<span> </span><code style="padding: 0px; margin: 0px;">en/admin/pages/994/</code>, matched the last one.</p></div><div id="explanation" style="padding: 10px 20px; margin: 0px; border-bottom: 0px none; background: rgb(238, 238, 238); color: rgb(0, 0, 0); font-family: sans-serif; font-size: small; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><p style="padding: 0px; margin: 0px;">You’re seeing this error because you have<span> </span><code style="padding: 0px; margin: 0px;">DEBUG = True</code><span> </span>in your Django settings file. Change that to<span> </span><code style="padding: 0px; margin: 0px;">False</code>, and Django will display a standard 404 page.</p></div>
</body>
</html>

**Comment by sheralim012** [comment]
@cbunicef could you list down steps to reproduce this issue

- as far as I understand, deleting section will redirect to parent listing page
- also accessing page which doesn't exist (deleted) will give 404

let me know if I'm missing something

CC: @geoo89

**Comment by cbunicef** [comment]
1. Create Subsection Z within Section A
2. Create Article 1 within Subsection Z
3. Navigate to Subsection Z list of content including Article 1
4. In "More" dropdown select "Delete"
5. Confirm
6. Returns to deleted URL, with 404 message
