### ISSUE TITLE
Create sqlite dump as part of load_v1_db

### ISSUE THREAD

**Issue by geoo89** [unicef/iogt#518]
load_v1_db should create a sqlite dump of the v1 DB. This can then be included in the docker images of the respective site, so that still have access to v1 data should it be needed.

Or: Find alternative way to bundle v1 db inside the respective docker image to allows to access it later.

**Comment by ehmadzubair** [comment]
I think the best way to do this would be to just load/store the legacy postgres db in the postgres container that has the V2 data. This way, we'll be able to easily access them both.
