### ISSUE TITLE
Warning when adding content incompatible with Facebook Free Basics

### ISSUE THREAD

**Issue by cbunicef** [unicef/iogt#542]
As a PLATFORM ADMINISTRATOR I want to be reminded when content I'm adding to the site is outside of Facebook Free Basics specifications.

This can be
1. Video
2. Large images (> 200KB)
3. Documents (which will be linked)

Should be a small notification, eg helptext, in red.

Full guidelines are here:
https://developers.facebook.com/docs/internet-org/platform-technical-guidelines
https://developers.facebook.com/docs/internet-org/how-to-submit

**Comment by geoo89** [comment]
The guidelines specify "We will not display video files and will also truncate resources larger than 200 KB."

From what I understand this means that documents (and audio) <200 KB are acceptable?
Should we give a warning for all documents, or only documents >200 KB?

**Comment by cbunicef** [comment]
This is under the "Video and large images" header, so we can assume that resources here refers to images.
