### ISSUE TITLE
User account registration / management

### ISSUE THREAD

**Issue by istride** [unicef/iogt#55]
Visitors of IoGT sites should be able to sign-up for an account to allow for personalisation and community involvement.

- Visitors should be able to create a user account for themselves.
- As part of the sign-up process visitors may be asked a set of questions, which may be different for each site, and may be optional or mandatory.
- Users should be able to change details of their account (name, username, password)
- Users should be able to initiate a password reset process.

**Comment by istride** [comment]
This issue covers #27 and #10

**Comment by isedwards** [comment]
This issue may also link to the need to implement surveys - Although user registration will implement a set of standard 'hard-coded' questions for all sites, but it would be useful for each site to be able to require a registration survey to be completed as part of the registration process where the survey questions are not hard-coded (see [form builder](https://docs.wagtail.io/en/stable/reference/contrib/forms/index.html))

**Comment by ehmadzubair** [comment]
Also, I don't feel very strongly about making the registration form a FormBuilder subclass. Perhaps having the post survey questions as an add-on step is a better approach. That way, there's separation of concern and we don't tweak the "standard" approach significantly. Thoughts?

**Comment by ehmadzubair** [comment]
Yes - @dannyparsons mentioned it. I did some research on registration packages. [django-registration](https://github.com/macropin/django-registration) and [django-allauth](https://github.com/pennersr/django-allauth) stood out.

Here are my findings:
- Both the packages are flexible for customisation
- Both the packages will fulfil our needs (even if we plan on adding two step registration with email verification)
- Both the packages are actively maintained
- Both the packages give support for specifying the success url (later used for registration form)

I feel django-all-auth would be the better fit for our case because it provides everything that django-registration does and also gives some extra features/views. For example: Social login, oAuth 2.0 support, password management, Reset password, Social connection management, Email management etc. 

It is however more "maintenance heavy" than django-registration. Here are the dependencies for django-allauth:
```
        "Django >= 2.0",
        "python3-openid >= 3.0.8",
        "requests-oauthlib >= 0.3.0",
        "requests",
        "pyjwt[crypto] >= 1.7",
```

**Comment by istride** [comment]
Let's proceed with djang-allauth, in that case. I think the extra features it provides is worth the additional dependencies it requires.

**Comment by ehmadzubair** [comment]
@istride @dannyparsons Okay to assume that we'll only be needing a one-step Sign Up? i.e No email verification?

**Comment by ehmadzubair** [comment]
There are a lot of other settings that can be done to tailor the registration/login behaviour. Can either one of you take a look [here](https://django-allauth.readthedocs.io/en/latest/configuration.html) and let me know if we need to edit something?

**Comment by dannyparsons** [comment]
@ehmadzubair Sorry for not replying before you got to implementing. The initial sign up form should have only: **username**, **display name**, **4-digit PIN**. Other information e.g. email may be part of the post-registration questions. So no email required, no verification etc.

See here for the previous version https://ke.goodinternet.org/profiles/register/ So the same fields as here except Gender is not included as a sign up question.

**Comment by ehmadzubair** [comment]
@dannyparsons No worries - I'll update the fields hopefully tomorrow.

**Comment by ehmadzubair** [comment]
@istride do you want to get on a call to discuss Post Registration form?

**Comment by ehmadzubair** [comment]
Updates from the meeting between me and @istride :
- Continue on the user registration and have a custom user
- Build mechanism for locking the user out to a screen (which hosts the survey) if their account isn't activated
- Add an Accept Terms & Conditions checkbox
- Assemble the knowledge around surveys and polls and then create a ticket for that
- Make post registration a special survey
- Use the post registration form to "activate" the user's account (using all-auth's hook for this)
- Changes to the form are going to introduce very complex use cases. Better to document them and do the due diligence before starting the surveys ticket
- Moving forward, write tests for non-trivial, non-obvious code

cc: @dannyparsons

**Comment by istride** [comment]
@ehmadzubair v1 IoGT code: https://github.com/unicef/molo-iogt
Code for the existing registration form: https://github.com/praekeltfoundation/molo/blob/develop/molo/profiles/forms.py#L127
