### ISSUE TITLE
Ensure that no resources are required from external domains

### ISSUE THREAD

**Issue by cbunicef** [unicef/iogt#581]
As a USER that doesn't have a data package, when I access IoGT for free through my MNO I don't want my experience to be disrupted when external resources don't load.

As a USER I want to be sure that I am not using up my data package if I've been told IoGT is free through my MNO.

Implications on external dependencies (as I understand them, please add)

Critical to address:

- [x] https://fonts.googleapis.com/icon?family=Material+Icons (I assume this is layout-breaking if it doesn't load)

Important to address:

- [ ] Google Analytics (replace with server-side tagging https://developers.google.com/tag-platform/tag-manager/server-side/intro)

Unknown:

- [ ] http://www.w3.org/2000/svg (unsure whether this xmlns tag actually calls the destination URL)

**Urgent tag only applies to Critical items.**

**Comment by sheralim012** [comment]
for google analytics to honor facebook free basics we will have to deploy google tagging server ourself, [here](https://developers.google.com/tag-manager/serverside/manual-setup-guide) are the steps to deploy it manually. After that we have to configure our django app to use it which can be found [here](https://developers.google.com/tag-platform/tag-manager/server-side/intro) and [here](https://stefanbschneider.github.io/blog/django-google-analytics).

**Comment by geoo89** [comment]
Reopening and removing the urgent tag to keep track of the less urgent items.

**Comment by cbunicef** [comment]
There are still fonts being pulled from Google domains:

![image](https://user-images.githubusercontent.com/30042226/146269939-6284c9e5-364b-4a1a-8774-261bf151c543.png)

**Comment by cbunicef** [comment]
Re-opening issue to track Google Analytics server-side - this is actually important to get in the next major release.

**Comment by cbunicef** [comment]
I was taking a look at #1186 and I just want to make sure that this solution works without Javascript and doesn't require calls from a user device to external servers. We need this for tracking to work on feature phones and Free Basics. For reference, the V1 GA solution doesn't have any GA-related code on the user-facing site from what I can see. Maybe this is an intermediary step?

@ChrisMarsh82 maybe we can catch up on this during our Monday meeting

**Comment by istride** [comment]
One of the problems with the server-side GTM container approach is that it still relies on javascript or iframe elements, both of which are [not allowed under Free Basics][4].

In V1, analytics is implemented via a combination of [django-google-analytics-app][1] and some custom middleware ([MoloGoogleAnalyticsMiddleware][2], [IogtMoloGoogleAnalyticsMiddleware][3]). I suggest we follow a similar approach.

@ChrisMarsh82 @sheralim012 

[1]: https://github.com/praekeltfoundation/django-google-analytics
[2]: https://github.com/praekeltfoundation/molo/blob/a46e6e63e5ae9525f077f3d548cc0b492f884b97/molo/core/middleware.py#L120
[3]: https://github.com/unicef/molo-iogt/blob/b0b36e713cd82dcd685c1733bcc6b41998f164d1/iogt/middleware.py#L77
[4]: https://developers.facebook.com/docs/internet-org/platform-technical-guidelines/

**Comment by cbunicef** [comment]
This is long resolved
