### ISSUE TITLE
Don't show None for index_page_description

### ISSUE THREAD

**Issue by geoo89** [unicef/iogt#598]
![image](https://user-images.githubusercontent.com/678199/136014380-7547b6ae-82ad-46c1-8d0d-805433853fa6.png)

![image](https://user-images.githubusercontent.com/678199/136014744-dc3970c3-b46f-4902-877e-7dda556dc658.png)

Either set the default value to "", or add an additional check to not display this if the value is None

**Comment by cbunicef** [comment]
Moving to urgent since this is breaking the interface
