### ISSUE TITLE
As a CMS editor, I can configure robust surveys to allow front-end users to share insights or learnings.

### ISSUE THREAD

**Issue by lauriemarkle** [unicef/iogt#6]
Surveys should allow for a feature image to appear of surveys. 
Surveys should allow for editable description to appear at the start of surveys. 
Surveys should allow for the following field options: 

- Single line text
- Multi line text
- Positive number
- Number
- Date
- Date / time
- Email
- Checkbox (i.e. 1 option, check to consent)
- Checkboxes (i.e. check all that apply)
- Radio buttons (multiple choice with only 1 answer)
- Drop Down (multiple choice with only 1 answer)

Positive number, radio buttons & drop down should provide options for skip logic within the survey configuration. 

- All fields should be marked as required or optional (with optional as the default). 
- All fields should have an associated "Admin Name" which relates to the CSV file header when exporting survey results. 
- All fields should have optional, editable information / help texts (e.g. "check all that apply") which appear on HTML view as italic, light gray text and in javascript enabled views as an "i" with a circle around it. Text will appear on hover. 

**Polls, surveys and quizzes should have** 

- All existing validation / error messages when surveys are saved and required fields are not met. Such as adding a field without an admin name or adding a multiple choice field but not assigning any options.
- Editable submit and homepage button text that edits either the button to select when beginning a survey or submitting a survey. By default these read "start" and "submit" - and should be incorporated in the translation solution to ensure that all features of the site are translated appropriately. 
- the option of sitting either within a parent section or sub-section or as a child to an article. The option to have a click-button to begin or direct display (either onto the body of the article as an optional content module or in the parent section or sub-section) should be available. 
- the option to require login or accept anonymous responses
- the option to allow multiple responses per user or not
- the ability to format the confirmation page to include text ,images, media, and links as an article. 
- Scheduled publishing options (post and expiry date)
-

**Comment by dannyparsons** [comment]
Allow anonymous submission should be the default.

**Comment by dannyparsons** [comment]
Surveys should also have page break options where a page break can be added after a question in order to display the survey on multiple pages. I assume if the survey is embedded within an article the page breaks are ignored.

**Comment by lauriemarkle** [comment]
That makes sense. Thanks, Danny.

**Comment by sheralim012** [comment]
* there is no feature image (lead image) for survey
* direct display option is there in wagtail admin but isn't implemented

all other seems fine.

**Comment by geoo89** [comment]
Most of this is done, one or two things remain and issues have been created.

Before I can close this, we need to discuss:

- "There should be start button to start the quiz (with custom text)". We have a different design: 
![image](https://user-images.githubusercontent.com/678199/127044139-d000943b-becc-4d1e-bad7-6cd994faa2f4.png)
No custom text, but the poll title instead.

- The option to have a click-button to begin or direct display (either onto the body of the article as an optional content module or in the parent section or sub-section) should be available. - Within a section, but embedded and direct display work. When part of an article, however, they are always embedded (a start button is not available)

- "Positive number, radio buttons & drop down should provide options for skip logic within the survey configuration." Does this also apply to quizzes? Currently, all input types show options for skip logic. I have to check for which types this actually works.

Also I'd like to do some more QA on:

- the option to require login or accept anonymous responses
- the option to allow multiple responses per user or not
