### ISSUE TITLE
Add information on ChatBot channel setup page

### ISSUE THREAD

**Issue by cbunicef** [unicef/iogt#606]
Please add:

"Authorization Header Value" - if this is secure to share in this interface.
Link to instructions on GitHub for setting up RapidPro channel.

**Comment by geoo89** [comment]
To be more specific:

In Chatbot > Chatbot Channels > New
- Display the Authorization header value somewhere (the same that is displayed when running `./manage.py get_rapidpro_authentication_header_value`), e.g. as a non-editable field
- Hint for Display Name: "Name for the bot that the user will see when interacting with it"
- Hint for "Request URL": "To set up a chatbot channel on your RapidPro server and get a request URL, follow the steps outline in the Section "Setting up a Chatbot channel" here: https://github.com/unicef/iogt/blob/develop/messaging/README.md" (We will edit the README to be more clear.)
