### ISSUE TITLE
During migration, in Section A there are empty Subsections B, C, D titled with the name of Section A

### ISSUE THREAD

**Issue by cbunicef** [unicef/iogt#624]
![image](https://user-images.githubusercontent.com/30042226/136395283-527c1dc6-6dce-4c05-bb48-e9f3ee493ff4.png)

**Comment by geoo89** [comment]
These sections do exist in the V1 global site, and seem to contain non-English articles when navigating the content in the CMS.

Should we not show sections if they do not contain any content in the selected language?

**Comment by geoo89** [comment]
Issue a warning for each section where the `description` fields is `null`.
This should include a link to the V2 page and the admin panel of this page.
