### ISSUE TITLE
Arabic text is left-aligned, should be right-aligned

### ISSUE THREAD

**Issue by cbunicef** [unicef/iogt#635]
Unsure whether this applies to other right-to-left languages as well.

**Comment by geoo89** [comment]
@cbunicef @karbab

Does this look sensible (disregarding the couple of missing Arabic site strings)?

![image](https://user-images.githubusercontent.com/678199/137211801-561c909f-726d-4c1b-b95d-4e9f5a386879.png)
![image](https://user-images.githubusercontent.com/678199/137212383-ff443d07-f829-4191-bf7c-9cbe14715b91.png)

**Comment by cbunicef** [comment]
This looks OK to me but of course I can't read it. The exception is "OF 1 QUESTION 1" which makes me wonder whether word order is getting confused in Arabic as well.
