### ISSUE TITLE
Design clean-up

### ISSUE THREAD

**Issue by istride** [unicef/iogt#65]
The existing markup and styling was copied over from Preact SPA that was developed by fairly inexperienced developers. Before further development of the front-end, it would be beneficial to review the existing markup and styles. Some deficiencies have been identified already:

* HTML duplicated to cater for different device types
* Inconsistent media queries, targeting slightly different device breakpoints
* CSS is not very well organised (might benefit from BEM methodology)

There may be other issues, and suggestions for improvement would be welcome for our consideration.

The app is designed to work primarily on low-end devices (feature phones and budget smartphones), but should support all devices. There is also a requirement for the app to be fully functional on devices/browsers that do not support JavaScript.

**Comment by dannyparsons** [comment]
Each 'app' could contain its own css and html templates. At the moment, the relevant paths are:

https://github.com/unicef/iogt/tree/develop/iogt/static/css
https://github.com/unicef/iogt/tree/develop/home/static/css
https://github.com/unicef/iogt/tree/develop/iogt/templates
https://github.com/unicef/iogt/tree/develop/home/templates
https://github.com/unicef/iogt/tree/develop/search/templates

Little to no knowledge of Python is required, and only the ability to follow the instructions to set up the Python project in the readme are necessary.

**Comment by dannyparsons** [comment]
Not needed as design team will work on this.
