### ISSUE TITLE
During migration, respect that some settings and fields in V1 are non-functional

### ISSUE THREAD

**Issue by cbunicef** [unicef/iogt#650]
This isn't a report on a particular field, but rather a reminder that there may be settings in V1 sites which are selected, and correspond to V2 settings, but will produce effects that aren't expected by the administrator.

The migration process should attempt to replicate the actual behavior of settings as displayed on the V1 site rather than the logical behavior of settings, with exceptions for all functions that are intentionally improved.

**Comment by ChrisMarsh82** [comment]
done
