### ISSUE TITLE
Prevent new user registration that differ only in capitalization.

### ISSUE THREAD

**Issue by geoo89** [unicef/iogt#654]
E.g. If a user 'admin' exists, it should be impossible to register as 'Admin' or 'ADMIN'.

Rationale: #627 and #631

**Comment by ehmadzubair** [comment]
This bug is related to an issue with AllAuth (https://github.com/pennersr/django-allauth/issues/1868)

**Comment by falsefruit** [comment]
I submitted PR #765 as a possible workaround. If it does not seem like a reasonable solution just let me know and I'll close it, thanks!
