### ISSUE TITLE
Questionnaires in footers

### ISSUE THREAD

**Issue by geoo89** [unicef/iogt#656]
In V1, any polls/surveys in their respective index page also appear as footers.

In V2, footers are a specific page type that is basically the same as articles, thus by default we cannot have questionnaires as footers.

The easiest would be to replicate the behavior from V1 by making any questionnaire that is in the poll/survey/quiz index page appear as a footer (which also makes them appear as featured content on the homepage).

However, it might make more sense to decouple homepage featured content and footer content by treating footers like a special version of featured content: Thus a footer would be a page reference (which could be an article, section or questionnaire), and in the homepage a list of such page references is specified as footers.

@cbunicef

**Comment by cbunicef** [comment]
To clarify just a bit on index page / homepage behavior:

In V1 polls in their index page are embedded on the homepage
In V1 surveys in their index page are embedded on the homepage if "Direct Display of Question" (name?) is checked

This causes some problems, eg if you would like a poll to be in footers across the site then it must also be embedded on the homepage.

I don't like making Poll/Survey/Quiz index page equal to adding to the footer - it doesn't make sense when we also have a Footers index page.

If it's possible, this makes the most sense to me:

* Homepage
  * Sections (Sections Index Page)
  * Footers (Section)
    * [Here users can add Article, Polls, Quiz, Survey, possible Footer Pages]
  * Banners (Banners Index Page)

Is the Footer Page type actually different than the Article Page type? From the Admin Panel side they seem the same.

For the Homepage, embedding Polls/Surveys/Quizzes can be done via "Home Feature Content" Content Blocks which already exist.
