### ISSUE TITLE
"Link" Page Type

### ISSUE THREAD

**Issue by cbunicef** [unicef/iogt#662]
Link to internal Pages or external URLs that is listed in Sections along side Articles.

Not sure why this doesn't exist yet in Wagtail, potentially there are good reasons.

**Comment by geoo89** [comment]
This is partially addressed in #664: A new PageLink page type is introduced that currently may only be used in the footer index page. It links to an internal page which is then displayed as a footer. Title and icon can be specified to override the title/icon of the page when displaying as a footer.

It cannot be used within regular sections yet, and does not support external links.

**Comment by geoo89** [comment]
PR #795 now implements this for internal site links.
