### ISSUE TITLE
Add a PageLink Page to Footer Index Page

### ISSUE THREAD

**Issue by ehmadzubair** [unicef/iogt#663]
Supported Pages:
  - Add Icon field to all questionnaire pages

Fields:
- Title
- Page (FK) - limited to [Section, Article, Survey, Poll, Quiz]

This page can only be the child of FooterIndexPage. Display these pages like FooterPage buttons on the frontend. The icon of the linked page will be used as the icon in the footer button. Update the implementation of the Footer section to fetch the buttons from the Footer index page so that they're sorted exactly like they are in the admin.

**Comment by geoo89** [comment]
Is the title field necessary for technical reasons, or can that be inferred from the linked page as well?

FooterIndexPage may now contain [Section, Article, Survey, Poll, Quiz, PageLink, (Footer)]. Footer only if necessary for legacy support; ideally convert all footers to articles as they are equivalent (as part of a migration or management command?)
