### ISSUE TITLE
During migration, Page translations are not truly "connected" as when creating new Pages in V2

### ISSUE THREAD

**Issue by cbunicef** [unicef/iogt#691]
Page translations which are migrated appear like this:

Main language

http://iogt-global-showcase.idems.international/admin/pages/283/edit/
![image](https://user-images.githubusercontent.com/30042226/138273859-ad43cd3b-0d97-4e29-bdf7-ffc450707469.png)

Translation

http://iogt-global-showcase.idems.international/admin/pages/633/edit/
![image](https://user-images.githubusercontent.com/30042226/138273894-9498a1b4-74b3-4399-8c39-d82449dc30fb.png)

Page translations which are created new in V2 appear like this:

Main language

http://iogt-global-showcase.idems.international/admin/pages/1271/edit/
![image](https://user-images.githubusercontent.com/30042226/138274053-7f0a3430-8170-42b4-b42a-ab41e7b17006.png)

Translation

http://iogt-global-showcase.idems.international/admin/pages/1273/edit/
![image](https://user-images.githubusercontent.com/30042226/138274175-acfa624a-0621-47a6-91ca-4704528045e1.png)

------------------

Since Page translations were stored separately in V1 (it seems), I'm assuming that it's not possible to make migrated Pages in V2 "connect" as new V2 Pages do.

**Comment by geoo89** [comment]
It is possible to 'disconnect' the V2 translations though by picking "Stop translation" from the menu.
I believe in order to translate questionnaire answer options, this might even be a necessary step.
