### ISSUE TITLE
Support for multiple webhooks in one platform when creating chatbots

### ISSUE THREAD

**Issue by cbunicef** [unicef/iogt#693]
As a PLATFORM ADMINISTRATOR I want to be able to include chatbots on my website that are hosted on different RapidPro workspaces.

**Comment by geoo89** [comment]
I think I understand what this issue is about now.

In the admin panel Chatbot > Chatbot Channels, after adding one channel, there is no button to add additional channels. This should be fixed. (The current workaround is using the django-admin interface.)

**Comment by cbunicef** [comment]
Exactly, thanks @geoo89
