### ISSUE TITLE
As a data analyst, I can export survey, poll and quiz data by form or by user as a CSV file or as an external API to PowerBI

### ISSUE THREAD

**Issue by lauriemarkle** [unicef/iogt#7]
As a data analyst, I can export survey, poll and quiz data by individual survey, poll or quiz. For example, I can export all results from a single survey in a CSV file. I can also export results from all three form types for a single user or user group.

**Comment by dannyparsons** [comment]
In the Surveys section of Wagtail ideally it displays the total number of responses at the top when viewing all responses.

**Comment by ChrisMarsh82** [comment]
Closing issue - see #520
