### ISSUE TITLE
After migration, some icons don't load properly (sometimes)

### ISSUE THREAD

**Issue by cbunicef** [unicef/iogt#705]
![image](https://user-images.githubusercontent.com/30042226/138446660-5dd54eba-b0fa-460a-9e15-efa4fd3ac198.png)

Icon 1 doesn't appear when logged out. (http://mena.iogt.site/media/svg-to-png-maps/svg-to-png_KjEfHoY.png)

Icon 2 doesn't appear.

**Comment by ChrisMarsh82** [comment]
complete
