### ISSUE TITLE
During migration, different IoGT V1 sites should migrate Pages order in Sections differently

### ISSUE THREAD

**Issue by cbunicef** [unicef/iogt#709]
Due to various versions of IoGT V1 currently in use at UNICEF, and outstanding bugs, there are two different ways that Pages were ordered in Sections:

Type 1:
kenya
tanzania
south africa
eucador
IOGT global

Pages in Sections were ordered by Creation Date. That order of Pages should be transferred to V2 during migration. eg

V1 newest creation date = V2 first item
V1 second newest creation date = V2 second item

Type 2:
All others

Pages in Section were ordered via user-selected order - which is NOT the same as order which appears by default in the Admin Panel interface. It is the order which appears after clicking the "Sort" button at the Section level. That order of Pages should be transferred to V2 during migration. eg

V1 first item when sorting Pages = V2 first item
V1 second item when sorting Pages = V2 second item

**Comment by cbunicef** [comment]
I think this is no longer Awaiting UNICEF correct?

**Comment by geoo89** [comment]
I thought you wanted to check back with Laurie how to deal with this, because (at least in global, so I assume this is for all of Type 1) the section preview shows the pages in the order from the CMS but when you view the section itself, it shows them by creation date.

**Comment by cbunicef** [comment]
For Type 1 sites - we will sort by creation date and output a warning in the migration report that the parent sections will appear in a different order.

**Comment by sheralim012** [comment]
@cbunicef 
Section page has sections, articles, polls, and surveys as children and for type 1 they all will be sorted by creation date, right?

also, there are a couple of datetime fields (`latest_revision_created_at`, `first_published_at`, `last_published_at`), and which should be used for sorting?

CC: @geoo89

**Comment by cbunicef** [comment]
> @cbunicef
Section page has sections, articles, polls, and surveys as children and for type 1 they all will be sorted by creation date, right?

Yes

> also, there are a couple of datetime fields (latest_revision_created_at, first_published_at, last_published_at), and which should be used for sorting?

We don't need to use any of those for sorting.

**Comment by geoo89** [comment]
I think the question was, which of these fields is the creation date? (There is no field called creation_date.)

It appears to me that it is in fact first_published_at; looking at the earliest entry of the revision history of a page, the date seems to match the first_published_at entry.

**Comment by cbunicef** [comment]
Ah I see, thanks. Yes first_published_at would seem to be the best.

**Comment by geoo89** [comment]
We implemented this specification, but now subsections are in the wrong order, while they appeared to be in the correct order before (e.g. see iogt-global-showcase). It appears that this sorting only applies to articles after all? Can you confirm @cbunicef 

I also finally realized that the 'related sections' field in articles does something after all: articles can appear in multiple sections, which mimics the proposed PageLink (see #662) functionality. However, it's not clear to me in which order they appear (both between them and relative to other elements of the section). Could we have a specification? Here's an example instance: https://www.internetofgoodthings.org/section/parents-caregivers/

**Comment by geoo89** [comment]
Content within a section is presented in the following order:
- articles
- articles added to the sections via 'related sections'
- subsections
- polls
- surveys

Subsections, surveys, polls are all shown in the order specified in the CMS.
Articles are shown sorted by first_published_at, with the newest articles first.
For related section articles, the order is not clear. If multiple related section articles come from the same section, then they are ordered in the order from the CMS. If they come from different sections, we don't know the order.
--> For each section containing related section articles, print a warning (Section title, section URL, section Admin URL) with the list of related section articles (Titles only) in that section, to indicate that these might be in the wrong order.
