### ISSUE TITLE
Featured Pages in Sections 

### ISSUE THREAD

**Issue by cbunicef** [unicef/iogt#710]
I see that this wasn't clearly defined in the V2 Figma, but here is how Featured Pages in sections should look.

Currently:
Section http://mena.iogt.site/en/sections/emergency-information/covid-19-parenting/
Featured Page http://mena.iogt.site/en/sections/emergency-information/about-covid-19/myths/
Design
![image](https://user-images.githubusercontent.com/30042226/138470723-496e7502-ce8a-46ee-af92-2fb1572d1022.png)

Desired:
![image](https://user-images.githubusercontent.com/30042226/138471742-b0d8a417-0a16-48ee-8b07-92bd413becff.png)

But, where does the icon here come from?

**Comment by geoo89** [comment]
> But, where does the icon here come from?

The icon is a static default icon. It can be overridden by setting an icon in the referenced article.

**Comment by geoo89** [comment]
Add the article image as in the second screenshot.

Ensure the entire area is clickable, not just the title text, as a link to the article.
