### ISSUE TITLE
Recreate V1 registration survey during migration

### ISSUE THREAD

**Issue by geoo89** [unicef/iogt#712]
V1 allows to ask for various fields during registration:

- Date of birth
- gender
- location
- level of education
- mobile number
- e-mail address

![image](https://user-images.githubusercontent.com/678199/138494452-00deff57-78cc-4ba4-9600-fab4ff18abb9.png)

The V1 DB table specifying which of these to ask for, and which to mark as required, is `profiles_userprofilessettings`.

We should create a registration survey from this as follows (featuring only those rows that are enabled):

|field | label | help text | input type | admin label|
|---|---|---|---|---|
|Date of birth | Select date of birth | Let us know your birthday to get access to exclusive content. | date| date_of_birth |
|gender | I identify my gender as: | Only you will see this | single line text| gender |
|location | Where do you live? | Only you will see this | single line text| location |
|level of education | What is your highest level of education? | Only you will see this | single line text| education_level |
|mobile number | Enter your mobile number | e.g. 0900000013 | single line text| mobile_number |
|e-mail address | Enter your email address | e.g. example@foo.com | e-mail| email |

For each field, the 'required' flag should be set iff it is set in `profiles_userprofilessettings`.

Ideally, this survey should be created for each of the enabled locales. (This can be a separate ticket.) Translations of the given strings can be found here (I can compile them into a csv): https://github.com/praekeltfoundation/molo-iogt/tree/a6e3f08681f12def6a9d14263786ee9a61de0035/locale
For those locales where the translations are incomplete, issue a warning during migration.

---

The table that stores these data for the users is `profiles_userprofile`.
Each row in this table should be converted into a survey response. (In lieu of any locale information, I assume for the English version of the survey?)

@cbunicef : Is the text "Let us know your birthday to get access to exclusive content." still applicable in V2?

**Comment by ehmadzubair** [comment]
@geoo89 Can you fill this [sheet](https://docs.google.com/spreadsheets/d/1S6nNhClgArVqFfRytjUhHiTR0F7eL1OoMHM8ayge4u4/edit?usp=sharing) for the translations of the registration survey?

**Comment by geoo89** [comment]
@ehmadzubair I don't have write access. I sent you the files privately.

**Comment by geoo89** [comment]
Fixed by #783
