### ISSUE TITLE
Some svg-to-png icons are too large

### ISSUE THREAD

**Issue by cbunicef** [unicef/iogt#719]
Example: http://mena.iogt.site/media/svg-to-png-maps/svg-to-png_PpUYBHA.png

![image](https://user-images.githubusercontent.com/30042226/138695566-51198b41-8dbb-4bf5-ac83-38a5ed4dd2b5.png)

Unnecessarily large PNG for an icon causing large file size.

Marking urgent because I think these PNGs are populated only once.

**Comment by ehmadzubair** [comment]
@mbilalhameed
