### ISSUE TITLE
Customisable homepage

### ISSUE THREAD

**Issue by dannyparsons** [unicef/iogt#75]
The homepage should be editable to be able to choose which articles/surveys/polls/quizzes appear on the homepage.

Currently this is done through editing the article by going to Promote > FEATURING IN HOMEPAGE

Instead, the desired functionality is for this to be done by editing the homepage and not by having to go to each individual article. Selecting items for the homepage should be done in a similar way as "Recommended Articles" are chosen where you can add articles/surveys/polls/quizzes through a search and be in a specific order.

**Comment by sheralim012** [comment]
I'll be working on this.

CC: @ehmadzubair

**Comment by dannyparsons** [comment]
@sheralim012 Thanks for taking this up. We agreed in a meeting today that the homepage needs the following fields:

1. Navigation items: a collection of articles/surveys/polls/quizzes to feature on the navigation bar (green bar below). The order can be determined. It would be good to have some way for this to be all top level sections by default. Possibly a checkbox for "All top level sections". If uchecked, then the CMS editor can choose their own collection.

![image](https://user-images.githubusercontent.com/11214914/119868478-fbd29600-bf16-11eb-95c0-4344d2bed2c0.png)

2. Banners: a collection of banners to appear at the top of the homepage (needs banner items implemented)

3. Featured content: a collection of articles/surveys/polls/quizzes to feature on the homepage i.e. the main things that the homepage will show.

4. Footers: A collection of footer items to appear at the bottom of the homepage.

There will probably be more than is also needed but let's start with this.

Someone else is thinking through how this will actually be displayed so the main thing is to have the structures in place first.

Happy to discuss details if needed.

**Comment by dannyparsons** [comment]
Update: Featured content should also include the ability to add Media.

**Comment by sheralim012** [comment]
@dannyparsons could you please add some details about banners implementation(as far as I know these will have images and links for the carousel). Also once media support PR gets merged I'll look into adding media as featured content.

**Comment by dannyparsons** [comment]
Yes banners are basically images that will appear at the top of the homepage with a link. So the banner definition needs:

- Title (not shown in the front end)
- Banner Image
- Link Page (choose a page to link to)
- External Link (enter a URL)

Only one of Link Page and External Link should be entered. This determines what you go when you click the banner.

see e.g. https://rke-iogt.unicef.io/admin/pages/1331/edit/ on a v1 site

They will appear differently on different devices - possibly carousel on desktops, column of images on feature phones. Our designers is working on this so don't worry about the display of banners yet.

**Comment by istride** [comment]
Are we sure we want all banners at the top of the homepage? In my mind, the featured content would be a single list that could include banners as well as articles and other pages, and it would be an editorial decision to keep all the banners at the top, or to intersperse them with other items on the homepage.

Another concern I have is that banners need to be subject to access control, so that an admin of one site cannot use the banners of another. However, we may need to allow copying banners from one site to another i.e. push from a 'central' site.

**Comment by dannyparsons** [comment]
We discussed both options of single featured content vs banners + featured content and Laurie felt banners + featured content was best to have to keep it simple for CMS editors and also didn't feel banners not at the top was that important.

Can we have access control with banners as snippets? Or should they be implemented another way? They also need to be translatable. I think all the same is true for footers. @istride Should they be implemented as a page type instead?

**Comment by dannyparsons** [comment]
We agreed on banners and footers being implemented as pages instead of snippets so that they can be defined for each site of the multisite.

**Comment by sheralim012** [comment]
@ChrisMarsh82 this is done and you can close this.
