### ISSUE TITLE
H2, H3, H4 styles are not larger than body font

### ISSUE THREAD

**Issue by cbunicef** [unicef/iogt#755]
![image](https://user-images.githubusercontent.com/30042226/139497766-51e108df-b4b9-4fbf-ab56-96e17042d8a8.png)

![image](https://user-images.githubusercontent.com/30042226/139497787-dc29a0ec-e840-4ad0-997c-ed5c35de2f42.png)

**Comment by ChrisMarsh82** [comment]
@ehmadzubair @azahid89  What are the current font sizes for Heading, Titlem H2, H3, H4 and body font?

**Comment by cbunicef** [comment]
If there isn't a large size difference between the headers we have the option to only provide eg H1 and H2 or H1 to H3.

**Comment by sheralim012** [comment]
- title is H1 with size 24px
- heading is div with size 16px
- H2 in paragraph is H2 with size 16px
- H3 in paragraph is H2 with size 14px
- H4 in paragraph is H2 with size 13px

**Comment by cbunicef** [comment]
It's important for accessibility that we have true H2, H3, H4 tags

**Comment by ChrisMarsh82** [comment]
Heading should be implemented as H2.
H4 should be larger than body text.

**Comment by sheralim012** [comment]
| tag | >= 360 (current) | < 360 (current) | >= 360 (proposed) | < 360 (proposed) |
|-----|--------|-------|--------------|-------------|
| h1  | 24px   | 22px  | 24px         | 18px        |
| h2  | 16px   | 16px  | 22px         | 16px        |
| h3  | 14px   | 14px  | 20px         | 14px        |
| h4  | 13px   | 13px  | 18px         | 12px        |
| p   | 16px   | 10px  | 16px         | 10px        |

heading in article body will use h2 tag

@ChrisMarsh82 could you review this and change/update if necessary

**Comment by geoo89** [comment]
@cbunicef This is what the proposal looks like:

![image](https://user-images.githubusercontent.com/678199/148675506-35a4f206-52cd-4050-931a-f3e14ea9cc79.png)

**Comment by cbunicef** [comment]
This looks good to me, thank you.
