### ISSUE TITLE
apple-touch-icon should not be hardcoded

### ISSUE THREAD

**Issue by cbunicef** [unicef/iogt#757]
Seen in homepage HTML:

`    <link rel="apple-touch-icon" href="/static/icons/unicef-logo.png">`

**Comment by ehmadzubair** [comment]
@mbilalhameed

**Comment by ehmadzubair** [comment]
Add to SiteSettings

**Comment by mbilalhameed** [comment]
@cbunicef are there specified dimensions for apple-touch-icon that should be used. According to apple's human interface guidelines, we should use different sizes for different devices. Here is the size chart provided by apple https://developer.apple.com/design/human-interface-guidelines/ios/icons-and-images/app-icon/. Currently, we are using fixed dimensions of 120px x 120px.

**Comment by cbunicef** [comment]
Should we make this match the manifest icon input as a short-term solution? Ie three sizes
