### ISSUE TITLE
Margins for article content should be reduced

### ISSUE THREAD

**Issue by cbunicef** [unicef/iogt#758]
By comparison nytimes.com, yahoo.com and many other websites are much thinner on the margins. I see this on mobile, obviously it's less obvious on desktop and tablet with the wider screen.

Was there a conscious decision behind having the wide margins?

**Comment by ChrisMarsh82** [comment]
Left-hand comments margin looks correct. Apply that to right hand side and articles. 
![image](https://user-images.githubusercontent.com/84872334/140718060-79f22821-1e66-4004-afd4-75a876871d10.png)

**Comment by geoo89** [comment]
To clarify:

- Article width should be the same as the width of the grey 'comments' block
- The margins around the grey 'comments' block should be symmetric, with the right margin (which is wider) to be adjusted to match the left margin (which looks good)

**Comment by cbunicef** [comment]
Should we go even wider than the current comments block? nytimes.com, yahoo.com, and google.com are all noticeably somewhat wider.

I would be fine matching text to the comments block and making both a little wider.

**Comment by ehmadzubair** [comment]
@azahid89

**Comment by cbunicef** [comment]
> Should we go even wider than the current comments block? nytimes.com, yahoo.com, and google.com are all noticeably somewhat wider.
> 
> I would be fine matching text to the comments block and making both a little wider.

Just realizing that I didn't write this clearly and it was implemented as "widening the margin". I was really hoping to widen the content.

I'm really looking to emulate other major sites and their narrower margin styles. I'm not sure if we are defining by pixels, % of page, or how but they can probably be 40% as wide as they are now.

**Comment by geoo89** [comment]
Proposal:
Regardless of whether we use feature phone/single column/multi-column view, the margins around the content in the central column should take up 3.7% of the total column width on the left and 3.7% of the total column width on the right.
