### ISSUE TITLE
If there's an error in installing IoGT as an app, the "Download" dialogue doesn't appear

### ISSUE THREAD

**Issue by cbunicef** [unicef/iogt#760]
If there is an error users are prompted to "Refresh and press Download button". The page automatically refreshed but the download dialogue doesn't appear again.

**Comment by ChrisMarsh82** [comment]
Need to discuss how this should be presented to the user.

**Comment by geoo89** [comment]
To clarify, according to David there was never a deep-dive into what is the best way to tell the user that the website is offline and offer to install the offline app, and thus the design of the dialogue should be revisited.

Considerations:
- Do not show on feature phones
- Shouldn't be intrusive to users who already installed the app?
- Users who declined to install the app the first time (or ran into technical issues) should still be able to do it later?

**Comment by ChrisMarsh82** [comment]
need a simple solution for now. can revisit later if needed.

**Comment by geoo89** [comment]
Short-term solution: Have a dedicated URL which can be referenced in e.g. articles or menus which initiates the installation process.

For the future: #792
