### ISSUE TITLE
Change maskable PNG size to 192x192?

### ISSUE THREAD

**Issue by cbunicef** [unicef/iogt#761]
Maskable.app outputs original dimensions and 192x192, but not 196x196. Is there a reason we use 196x196 instead of 192x192?

**Comment by mbilalhameed** [comment]
maskable icon size used in articles https://web.dev/maskable-icon-audit/ and https://web.dev/maskable-icon/ is 196x196

**Comment by ChrisMarsh82** [comment]
Change to 192

**Comment by geoo89** [comment]
...and test if that causes any issues.

**Comment by geoo89** [comment]
Also update `home/views.py` in the function `get_manifest`.

**Comment by geoo89** [comment]
Done in 275efb3.
