### ISSUE TITLE
In poll response display, include answer options that had 0 responses

### ISSUE THREAD

**Issue by cbunicef** [unicef/iogt#762]
Checkboxes question is missing all options which had no responses:

![image](https://user-images.githubusercontent.com/30042226/139833767-f1b27b59-a63d-44ba-a145-1f4891ae45d9.png)

**Comment by ChrisMarsh82** [comment]
Make an option to show all options or not.

**Comment by geoo89** [comment]
To clarify:
- In the CMS for polls, there should be an option "Display options with 0 votes in results" which is True by default.
- If this option is enabled, display all results regardless of how many votes they received. If not, only display those results that have at least one vote.

If adding this option takes a lot more time to implement (compared to always showing all results), make a separate issue for it (consider if a refactor could make adding such options easier in the future).
