### ISSUE TITLE
Adding group restriction to Page(s) results in an infinite loop

### ISSUE THREAD

**Issue by ehmadzubair** [unicef/iogt#78]
This issue is the result of an open bug https://github.com/wagtail/wagtail/issues/4297 in the Wagtail project. It's very strange how this hasn't been closed yet.

Thankfully, there is a workaround on the same link for this.

**Comment by ehmadzubair** [comment]
@dannyparsons I'm going to add the workaround in a PR. Do you think we should also 'not show' articles that are restricted to the user because of their group?

**Comment by dannyparsons** [comment]
What do you mean by 'not show'? I think links to articles that are visible to everyone is needed, because a user may not be logged in all the time but would have access if they login.

**Comment by istride** [comment]
@ehmadzubair have you managed to reproduce this issue in this project? There hasn't been any progress on the Wagtail issue for 2 years, so I wonder whether it is still a problem.

If it is still an issue, I wonder whether we ought to support the fix with some automated testing to make sure it does what we expect.

**Comment by ehmadzubair** [comment]
Yes - I was able to reproduce it. Let me add the test cases for this bug too.
