### ISSUE TITLE
Installing IoGT as an offline app

### ISSUE THREAD

**Issue by geoo89** [unicef/iogt#792]
Design a dedicated content block which looks like a page button, and its text depends on context:
- user is smart phone (text: something like "install the app")
- user is on a feature phone (text: something like "this feature is not available on your device")
- user is within the offline app (text: something like "you're already using the app right now")

So that this block cannot be used all over the site, make a dedicated page type which is the same as article but allows for this additional content block.

Allow this page type to be added only to a certain index page (Footer? some dedicated index page?)

**Comment by cbunicef** [comment]
Button is not appearing, for example: https://sandbox.iogt.site/en/miscellaneous/offline-access/
