### ISSUE TITLE
Option to hide locales from display in language selector

### ISSUE THREAD

**Issue by cbunicef** [unicef/iogt#798]
In the Locale settings, a checkbox (default: checked) labeled "Show this locale in the language selector".

If it's unchecked, the language will not appear in the selector but will be accessible at /[XX]/

**Comment by sheralim012** [comment]
we are using wagtail Locale model for locale/language management and there is no simple way to add new field in that for the following reasons
- we will miss any subsequent models changes from wagtail
- we will corrupt migration history of 3rd party package and any new migration will hinder/crash the site

one possible solution is, we manage a separate model (LocaleDetail) which will be connected to Wagtail Locale model with one-to-one relation and additional fields would be managed in this model.

Do we want to proceed with that?

**Comment by cbunicef** [comment]
I was imagining this hiding happening in the language selector widget, rather than in the locale model, but maybe they are inseparable?

**Comment by geoo89** [comment]
> one possible solution is, we manage a separate model (LocaleDetail) which will be connected to Wagtail Locale model with one-to-one relation and additional fields would be managed in this model.

Yes, let's do it this way.

Maybe this could also be used to configure the 'default' locale (see #799) that should be used if a URL has no locale code, and the page is not available in the locale of the user's browser?
