### ISSUE TITLE
Configurable default language

### ISSUE THREAD

**Issue by geoo89** [unicef/iogt#799]
Wagtail has its own notion of default language, but what we need here is the language that is shown when the user visits the page for the first time. For example, if the default language is English, a user visiting central.iogt.site is redirected to central.iogt.site/en/

In addition with #798 (which allows us to hide English from the page altogether if needed), these are the two behaviors we need to make another language than English the default language, without changing Wagtails' default language (which might have other unwanted implications).

**Comment by cbunicef** [comment]
Can this be done through slugs? ie in iogt-showcase currently here are the slug names for the homepages

English - home
Arabic - home-1
French - home-2

This also corresponds to the order of languages in the selector.

**Comment by sheralim012** [comment]
a couple of observations
- Wagtail (actually Django) allows changing primary language [here](https://docs.wagtail.io/en/stable/advanced_topics/i18n.html#changing-the-primary-language-of-your-wagtail-installation)
- when we open `central.iogt.site` (without locale), we are automatically redirected to the browser default locale version of the site [here](https://docs.wagtail.io/en/stable/advanced_topics/i18n.html#user-language-auto-detection), e.g., if browser default locale is Spanish and we open the `central.iogt.site`, we will be automatically redirected to `central.iogt.site/es/`,  if browser default locale is English and we open the `central.iogt.site`, we will be automatically redirected to `central.iogt.site/en/`
- we can change browser (chrome) locale from here
<img width="1311" alt="Screenshot 2021-12-22 at 12 09 49 PM" src="https://user-images.githubusercontent.com/49383675/147050563-364d53ca-082d-4d53-8cc4-d6818d41ec5a.png">

The potential workaround to this is to write a custom locale redirection middleware. Using that, we can specify a single locale (set in site settings) to redirect to whenever we receive a request without a locale in the URL. 

Do we want to proceed with that?

**Comment by cbunicef** [comment]
Thanks @sheralim012.

> * Wagtail (actually Django) allows changing primary language [here](https://docs.wagtail.io/en/stable/advanced_topics/i18n.html#changing-the-primary-language-of-your-wagtail-installation)

We don't necessarily want the language of the Admin Panel to change, it's a bit frustrating that the user and Admin Panel languages are tied.

> * when we open `central.iogt.site` (without locale), we are automatically redirected to the browser default locale version of the site [here](https://docs.wagtail.io/en/stable/advanced_topics/i18n.html#user-language-auto-detection), e.g., if browser default locale is Spanish and we open the `central.iogt.site`, we will be automatically redirected to `central.iogt.site/es/`,  if browser default locale is English and we open the `central.iogt.site`, we will be automatically redirected to `central.iogt.site/en/`

We do still want to keep this behavior.

> The potential workaround to this is to write a custom locale redirection middleware. Using that, we can specify a single locale (set in site settings) to redirect to whenever we receive a request without a locale in the URL.

Let's discuss how much work this is. The behavior we would want is:

- If there is a locale in the URL then direct to the Page in the locale
- If there is no locale in the URL and the Page is available in the user's browser locale, then direct to that Page in the browser locale
- If there is no locale in the URL and the Page is not available in the user's browser locale, then direct to the Page in the default locale

But - is there any scenario other than the homepage where a user will arrive on a Page where there is no locale in the URL? Right now I can only imagine this will happen if someone deliberately removes the locale from the URL.
