### ISSUE TITLE
As a CMS editor, I can upload multimedia files on the site for users to stream from the front end.

### ISSUE THREAD

**Issue by lauriemarkle** [unicef/iogt#8]
Multi-media files can be uploaded as MP3 & MP4 format. These files can then be accessed when editing articles and loaded as feature content. When file uploads exceed 6MB a warning sign appears that the format may not be accessible on low end devices. 

(bonus points: can the MP4 function as a banner on the homepage?)

**Comment by dannyparsons** [comment]
possible links to PWA/offline access #67 and implementation of banners #2

**Comment by dannyparsons** [comment]
@lauriemarkle Did we say we would have a file size limit that would be set in Site Settings? Possibly instead of/as well as the warning? I remember you gave an example of a country where they wanted to keep a fixed limit to comply with agreements with mobile network operators.

**Comment by lauriemarkle** [comment]
Just a warning message:
The file you have uploaded exceeds 9mb. This will prohibit access to the
file in a low bandwidth setting, may restrict feature phone access, or
violate your mobile network operator agreements. To reduce file size, try
resizing and compressing your file.

**Comment by dannyparsons** [comment]
@lauriemarkle Should the limit be 6MB or 9MB? I just noticed both 6MB and 9MB have been mentioned in different messages.

**Comment by lauriemarkle** [comment]
It's 9MB on the site, even though old docs say 6MB. Recall we aren't
capping the upload but we adding this message to the CMS:

Many low-end mobile devices will not support streaming from files greater
than 9MB. Before loading large files, consider your priority user groups
and existing mobile network operator agreements. To reduce file size,
resize videos to [Alex confirm new width / dimensions] and compress the
file. A free resource for these activities is available at
https://www.onlineconverter.com/resize-video and
https://www.onlineconverter.com/compress-video.

**Comment by dannyparsons** [comment]
Thanks Laurie. We'll update the CMS message with the new text too.
