### ISSUE TITLE
As a CMS Editor I can add a single featured content to a Section

### ISSUE THREAD

**Issue by dannyparsons** [unicef/iogt#82]
Sections should have a "Featured Content" field which allows for the selection of one page (article, survey, poll, quiz etc.) that is within that section. This is optional, a section doesn't have to have a featured content.

On the site, the featured content would then be displayed at the top of the section page before anything else (subsections, child articles).

**Comment by dannyparsons** [comment]
The section page should also have the following structure:

- 1 Featured Content (article, survey, poll, quiz) - if set in the CMS
- The list of sub-sections - clickable to go to those subsections
- The list of any direct child pages of the section

**Comment by dannyparsons** [comment]
Yes it's a similar idea. I believe Bartosz was assigned this task this morning, but I'm not sure when he plans to get to it.

**Comment by sheralim012** [comment]
@dannyparsons @istride currently there is no elegant way to limit page chooser options [[see-here](https://github.com/wagtail/wagtail/issues/1250)], 
the solution I was able to come up with wagtail-hooks is that we filter queryset based on the referer of request 
![Screenshot 2021-06-09 at 6 36 00 PM](https://user-images.githubusercontent.com/49383675/121365611-3c3c0600-c952-11eb-8600-be53b5243fb6.png)
here we will parse URL and get the id (4 in image) of the section and return children of the section only. And this solution seems overkill to me.

**Comment by dannyparsons** [comment]
Is it possible for the default to be for the page chooser to start at the section page instead of at the root? I think that would be fine even if there was no page restriction. I see that's also mentioned in the Wagtail issue you linked to but didn't see a solution.

**Comment by sheralim012** [comment]
@dannyparsons we can start at the section level by using the above-mentioned method but that would require some checks for traversal of descendants which would in result add some complexity.

**Comment by dannyparsons** [comment]
I think it's going to be a bit confusing for CMS users if there isn't either a restriction or the section as the default starting point.

I can't really comment on whether the hack is sensible to use. If it's quick to implement then I suggest you try something out and then @isedwards or @istride can give an opinion on the approach.
