### ISSUE TITLE
When you cannot take a quiz multiple times, the error message mentions a "survey"

### ISSUE THREAD

**Issue by cbunicef** [unicef/iogt#822]
Change to quiz. Check for polls as well.

**Comment by geoo89** [comment]
Adding "needs discussion" tag as "You have already completed this survey." is the only string we have translations for, and so this choice was deliberate. Alternative is adding the corresponding strings for poll/quiz and adding it to the translation manager for the country offices to provide translations for.

**Comment by cbunicef** [comment]
Yes, please add the corresponding strings but populate it in the translation manager (for now) with the original "survey" string.
