### ISSUE TITLE
Single/multi-line response in Quiz setup

### ISSUE THREAD

**Issue by cbunicef** [unicef/iogt#823]
This field type does not accept multiple correct answers separated by |, but there is no explanation of that in the area for specifying correct answers.

Add an explanation that open response does not allow this.

**Comment by ChrisMarsh82** [comment]
Need exact help text

**Comment by Alihassanc5** [comment]
Any update on this?

**Comment by cbunicef** [comment]
The current text is "For checkboxes, dropdown and radio: Pipe (|) separated list of choices."

That seems to work. Not sure if I overlooked that, or if it was fixed along the way. Closing this issue.
