### ISSUE TITLE
Posting comment redirects to example.com

### ISSUE THREAD

**Issue by geoo89** [unicef/iogt#836]
For instance, here: https://global.iogt.site/fr/sections/emergency-information/about-covid-19/about-coronavirus/

Site object is configured as global.iogt.site port 80. Also tried global.iogt.site:443, http://global.iogt.site:80, https://global.iogt.site:443, same result regardless.

**Comment by geoo89** [comment]
Also see #100 to investigate the cause of this.

**Comment by ehmadzubair** [comment]
There are two tables for setting the Site object:
1. `django_site` which can be modified using Django Admin
2. `wagtailcore_site` which can be modified using Wagtail Admin

My hunch is that you're using the latter. To fix this, we need to update the value from Django Admin

**Comment by geoo89** [comment]
Yes, I'm modifying the latter. So some site components use django_site, and some wagtailcore_site?
I assume we should fix this at some point so only one is used (or ideally none, as we're not using multi-tenant sites), but for now, can we create a management command that updates both with a given hostname and port? We will need this anyway once we change the domains of the sites when they go live.

Is this related to #189 as well?

**Comment by ehmadzubair** [comment]
The commenting components use the `django_site` (because that is a django package and not a wagtail package).

**Comment by cbunicef** [comment]
@geoo89 I see that on global.iogt.site all the comments are site="example.com". Will this be fixed at the final-step user/data re-migration?

**Comment by geoo89** [comment]
Should be fixed now. I think we migrated global before we integrated the management command that resolves this issue to the site setup pipeline, so I manually set the URL for the django site object now.
