### ISSUE TITLE
Exporting Users times out

### ISSUE THREAD

**Issue by cbunicef** [unicef/iogt#842]
For example on global.iogt.site

https://global.iogt.site/admin/iogt_users/user/

When using "Download XLXS" the site pauses and then gives a 504 error.

When using "Download CSV" the site begins to download the CSV file but then stops with a "network error".

Presumably there is so much data to collect that the server times out before the data collection is complete.

It's worth also noting that the site is inaccessible for users while downloading these files, and those page loads result in 504.

Does this also happen when there is a large Form Data download?

**Comment by geoo89** [comment]
The optimization from #844 fixes this particular instance, at least for global (and the corresponding amount of users).
As the deeper issue of certain actions timing out is tracked by #858, I'm closing this.
