### ISSUE TITLE
Comments - Related Features

### ISSUE THREAD

**Issue by ehmadzubair** [unicef/iogt#86]
This is a list of the features that were not a part of #81 because the PR was getting very lengthy:
- [ ] #37 
- [ ] Flagging for Moderators vs Users (if applicable) - See #56 
- [ ] #527
- [ ] #528

**Comment by sheralim012** [comment]
@ChrisMarsh82 flagging is done and the rest of the requirements need to be reprioratized

**Comment by geoo89** [comment]
Closing this as all the tasks have been split into separate issues.
