### ISSUE TITLE
Missing fields when translating articles after model update

### ISSUE THREAD

**Issue by geoo89** [unicef/iogt#868]
This is currently happening on global. Steps to reproduce:
- Create a locale without articles
- Navigate to some article in English
- More > Translate this page > [The new locale]
- We get a warning "The data model for 'Article' has been changed since the last translation sync. If any new fields have been added recently, these may not be visible until the next translation sync."
- Body content blocks are missing from the translation
- After "Stop translation", the body content is empty

This occurs for articles that were created as part of the content migration. Note that there has been a site upgrade on global since the migration, including, among other PRs, #768 . 
For newly created articles, this does not occur.

I tested this on iogt-django-dev, with a previously created page the last two steps didn't occur, however the warning is still issued. Again, for a newly created page this issue doesn't occur.

Is this related to updates to the Article or related models, with the translation models not being updated accordingly?

Needs investigation.

**Comment by geoo89** [comment]
Do we need to run `./manage.py sync_local_trees` as part of each site update?

**Comment by cbunicef** [comment]
Also occurs when translating content created in V1 to an existing locale where it didn't exist before.

**Comment by geoo89** [comment]
It appears that running `./manage.py sync_locale_trees` fixed the issue, at least I cannot reproduce it on global anymore.
So this step will have to be added to the update pipeline.

**Comment by geoo89** [comment]
Upon closer inspection, it does not appear to resolve the issue in all cases.
See for example the articles in this section: https://global.iogt.site/admin/pages/1788/

**Comment by geoo89** [comment]
It appears that this is fixed by going to the English version of a page, and select "Sync translations". Then the missing fields will appear in the translated pages. Sher is working on a management command that will apply this to all pages.

This command will have to be run after migration, and whenever we update any of the content models, i.e. whenever we push an update to the site.

**Comment by cbunicef** [comment]
Can we move forward testing migrating of a few initial sites before fully fixing this?
