### ISSUE TITLE
Access site in different languages through URL query

### ISSUE THREAD

**Issue by dannyparsons** [unicef/iogt#87]
Currently the site always opens in the default site language.

It would be useful for UNICEF staff to be able to send out links to a site in a specific language. I suggest this could easily be done through a URL query e.g.

https://ke.goodinternet.org/?lang=kiswahili to open in Kiswahili

relates to #21

**Comment by isedwards** [comment]
Django has this capability built-in, it should work with Wagtail. See:

https://docs.djangoproject.com/en/3.2/topics/i18n/translation/#language-prefix-in-url-patterns

**Comment by istride** [comment]
I thought Wagtail Localize would automatically provide a solution to this, but it does not. The [docs][1] recommend using the Django mechanisms. 

[1]: https://www.wagtail-localize.org/tutorial/2-configure-wagtail-localize/#urls

**Comment by mikowhy** [comment]
which url schema is expected:

`internetofgoodthings.org/en/article` or `internetofgoodthings.org/article?lang=en`

**Comment by mikowhy** [comment]
PR -> https://github.com/unicef/iogt/pull/120
