### ISSUE TITLE
Cannot automatically check if app is running

### ISSUE THREAD

**Issue by istride** [unicef/iogt#890]
When running the app in a production environment, it is common practice to perform upgrades by spinning up new instances of the app, checking that they're running ok, then killing the old app instances. The usual method of checking whether a web app is running or not is to provide a healthcheck URL within the app, that can be polled on a regular basis to make sure the app is actually running (or still running).

I don't think that such a healthcheck URL is available for IoGT, but I think it should be. I have seen a [plugin for django](https://pypi.org/project/django-health-check/) that would implement something like this, and maybe it would be worth using in this case.

**Comment by cbunicef** [comment]
Also related to #533
