### ISSUE TITLE
Allow images as well as SVGs for icons

### ISSUE THREAD

**Issue by cbunicef** [unicef/iogt#895]
This is important because sometimes we need to respect brand guidelines. For example this is relevant for Facebook and U-Report brands on mz.goodinternet.org

![image](https://user-images.githubusercontent.com/30042226/145846187-d007719b-ab33-4e32-b79f-a18a00a968e2.png)

These images should not change as theme settings change, eg color of text. To have an image that changes with text color, convert to SVG.

**Comment by ChrisMarsh82** [comment]
Anything that has an icon can also have a PNG/JPEG icon.
