### ISSUE TITLE
During migration, outstanding items observed on mz.iogt.site

### ISSUE THREAD

**Issue by cbunicef** [unicef/iogt#899]
Issues that require MZ migration re-run
- PT content migrated to EN
- "Date of birth" in registration survey is required for existing accounts before they can access any content, it was not required in V1
- "Submit" button is migrated in English, should instead be migrated in source language (this text should be available as it was hard coded in V1)

Issues to fix for future migrations
- Site logo is not migrated (may have happened after backup)
- "VISITA O WEBSITE DO UNICEF" link in Footer is not migrated, possibly this is hardcoded? Doesn't appear in footers section on V1
- English homepage has no "[English]" tag in title
- Some images which should be in the place of icons are migrated to Lead Images, eg https://mz.iogt.site/en/footers/about-internet-good-things/, see also #895

**Comment by geoo89** [comment]
> PT content migrated to EN

Have to figure out how the main language is indicated, and how to implement this in V2.

> "Date of birth" in registration survey is required for existing accounts before they can access any content, it was not required in V1

When registering a new user on V2 MZ, this field is optional, i.e. you can submit the survey without filling in the date. Existing users shouldn't be presented with the registration survey at all, so if they do, something must have gone wrong. Do you have the credentials of an existing user we can use to test this?

> "Submit" button is migrated in English, should instead be migrated in source language (this text should be available as it was hard coded in V1)

You mean the text "Register"? This is simple enough to change manually (Pages > Home > Surveys > Registration survey), but we can automate this.

> Site logo is not migrated (may have happened after backup)

We're not migrating the site logos/favicons etc currently, but instead using a default one. 

> "VISITA O WEBSITE DO UNICEF" link in Footer is not migrated, possibly this is hardcoded? Doesn't appear in footers section on V1

I looked into this, and found where this is stored in the DB:
`core_sitesettings > social_media_links_on_footer_page`

For example, for MZ the value is:
```[{"type": "social_media_site", "value": {"image": 178, "link": "http://www.unicef.org.mz", "title": "Visita o website do UNICEF"}}, {"type": "social_media_site", "value": {"image": 170, "link": "https://www.facebook.com/unicef.mozambique/", "title": "Segue o UNICEF no Facebook"}}]```

I assume we can issue a warning for now if this is populated. In the future, this seems to be a use case of adding external links to the PageLink page type, see: #662

> English homepage has no "[English]" tag in title

Have to investigate this.

> Some images which should be in the place of icons are migrated to Lead Images, eg https://mz.iogt.site/en/footers/about-internet-good-things/, see also #895 

It seems like unlike for articles, for footers the image_id serves as an icon and not as a lead image? So for footers, we should save the corresponding image as icon rather than lead image (once #895 is implemented, and until then issue a warning).

**Comment by cbunicef** [comment]
> > "Date of birth" in registration survey is required for existing accounts before they can access any content, it was not required in V1
> 
> When registering a new user on V2 MZ, this field is optional, i.e. you can submit the survey without filling in the date. Existing users shouldn't be presented with the registration survey at all, so if they do, something must have gone wrong. Do you have the credentials of an existing user we can use to test this? EDIT: I just spot checked a few users in the V2 DB of mz.iogt.site, and their has_filled_registration_survey flag is set to true, so I'd be surprised if existing users saw the registration survey again.
> 

Actually the issue here is that users cannot access the site until they complete the registration survey, but all questions on the registration survey are optional. So you are required to press "register" but you don't have to fill out any response. In V1 you didn't have to press register, you could just access the site.

> > "Submit" button is migrated in English, should instead be migrated in source language (this text should be available as it was hard coded in V1)
> 
> You mean the text "Register"? This is simple enough to change manually (Pages > Home > Surveys > Registration survey), but we can automate this.
> 

This relates to all surveys, eg also https://mz.iogt.site/admin/pages/207/edit/. This was fully Portuguese in V1, but in V2 we now have "Submit" in English.

> > Site logo is not migrated (may have happened after backup)
> 
> We're not migrating the site logos/favicons etc currently, but instead using a default one. EDIT: I'm not sure which fields determine this. In `core_sitesettings` there are `logo_id` which is null for MZ, but for RKE seems to match the site logo. I don't see the [image file](https://mz.goodinternet.org/media/images/boa_internet-03.original.png) or any file with a similar name appear in the DB nor the image backup. Similarly, I cannot find any favicon in the backup.
> 

It looks like this was probably added afterward to MZ V1. If we can migrate for future platforms as per RKE example that would be good.

I don't see a place to specify favicon in V1 so let's just add a warning in the report.

> > "VISITA O WEBSITE DO UNICEF" link in Footer is not migrated, possibly this is hardcoded? Doesn't appear in footers section on V1
> 
> I looked into this, and found where this is stored in the DB: `core_sitesettings > social_media_links_on_footer_page`
> 
> For example, for MZ the value is: `[{"type": "social_media_site", "value": {"image": 178, "link": "http://www.unicef.org.mz", "title": "Visita o website do UNICEF"}}, {"type": "social_media_site", "value": {"image": 170, "link": "https://www.facebook.com/unicef.mozambique/", "title": "Segue o UNICEF no Facebook"}}]`
> 
> I assume we can issue a warning for now if this is populated. In the future, this seems to be a use case of adding external links to the PageLink page type, see: #662
> 

Warning is great, thanks.

> > Some images which should be in the place of icons are migrated to Lead Images, eg https://mz.iogt.site/en/footers/about-internet-good-things/, see also #895
> 
> It seems like unlike for articles, for footers the image_id serves as an icon and not as a lead image? So for footers, we should save the corresponding image as icon rather than lead image (once #895 is implemented, and until then issue a warning).

Yes, please go ahead with this.

**Comment by geoo89** [comment]
> Actually the issue here is that users cannot access the site until they complete the registration survey, but all questions on the registration survey are optional. So you are required to press "register" but you don't have to fill out any response. In V1 you didn't have to press register, you could just access the site.

The difference is that in V1, registration was a one-step process while now it is a two-step process where you cannot bail out in the middle. In V1, if you didn't press register, you didn't create an account.
Should we try to embed the registration survey inside the main registration site? The tricky bit then is if we have certain usergroups who we want to re-do the survey, how to do that.

**Comment by geoo89** [comment]
Created issues for everything else

**Comment by cbunicef** [comment]
> The difference is that in V1, registration was a one-step process while now it is a two-step process where you cannot bail out in the middle. In V1, if you didn't press register, you didn't create an account. 

Actually in V1 creating the account was a separate page from answering the survey, at least for MZ. Try it: https://mz.goodinternet.org/profiles/register/

>Should we try to embed the registration survey inside the main registration site? The tricky bit then is if we have certain usergroups who we want to re-do the survey, how to do that.

To match V1, if there are no required fields in the survey then the user doesn't need to submit the survey before accessing the site. Is that possible?

**Comment by geoo89** [comment]
Closing this as all issues have been split out into separate issues now.
