### ISSUE TITLE
As a CMS editor, I can upload files to the IoGT site for front-end users to download to their device.

### ISSUE THREAD

**Issue by lauriemarkle** [unicef/iogt#9]
As with multi-media files, I can upload files to IoGT and host them on the server. These can be inserted into articles as hyperlinks within the body of the article for download. When documents are added as part of the body of a text, they appear as a button, rather than hyperlinked text.

**Comment by dannyparsons** [comment]
Document uploading and organisation is similar to images and multi-media files https://github.com/unicef/iogt/issues/3#issuecomment-864915779 - through the Documents panel and using Collections.

Displaying documents as buttons will be investigated as part of design implementation.

**Comment by sheralim012** [comment]
@ChrisMarsh82 documents added to part of body of text appear as button instead of hyperlink isn't implemented.
