### ISSUE TITLE
Multi-site support

### ISSUE THREAD

**Issue by ehmadzubair** [unicef/iogt#90]
Me and @sheralim012 did some research on the Multi-site support according to IOGT's requirements.

## Strategy 1
The first strategy is a ‘no-fork’ solution. Almost all of the wagtail ModelAdmins will have to be replaced with our own rendition of model admins. We will also have to create ‘hacks’ around how to link models to ‘Site’

For example, If we want to only filters groups for my site only to show up on the Groups admin screen, we will need to:
- Add our own GroupAdmin and inherit it from WagtailGroupAdmin (for future updates)
- Override get_queryset to fetch groups for the current site

There is no existing connection between these two entities and creating our own Group model wouldn’t suffice. We’ll have to either create a ‘through’ table between `Groups` and `Sites` or link them using a hack like have the `Group` name be `{site.name}.group`.

This is just one example of customization and this still doesn’t ensure that groups will be restricted in other parts of the admin or wagtail in general. For example if we use a third party library that uses groups, all the groups will show up.

## Strategy 2

The second strategy is to fork the wagtail repository, and then add multi-site support. We have gone through the codebase and know the touchpoints where code need to be modified. Doing a fork would of course add complexity in receiving future updates. This too will require a detailed walkthrough of the admin codebase and updating a lot of querysets along the way. We should also factor in the complexity of getting the ‘current site’ in the models/views (there are workarounds for that).

The Django documentation for [https://docs.djangoproject.com/en/3.2/ref/contrib/sites/](Sites) framework suggests that this should be done using the [https://docs.djangoproject.com/en/3.2/ref/contrib/sites/#the-currentsitemanager](CurrentSiteManager). This approach is a two pronged sword. While we’ll be adding multi-site support just by replacing ‘.objects’ with ‘.on_site’, this will have some implications on the infrastructure side of things as one app instance will only support one site ID. We’ll have to use Nginx as a reverse proxy to different app instances with different `SITE_ID`s.

Hope this was helpful. Happy to discuss it over a call @istride @dannyparsons

**Comment by dannyparsons** [comment]
Thanks Ehmad for this review. It sounds like we can satisfy all our requirements with Strategy 1, just with more custom code and some workarounds, so my view would be to continue on this path. Strategy 2 sounds like an interesting longer term solution but probably too much work at this late stage. Though @isedwards and @istride can give a more informed opinion.

**Comment by isedwards** [comment]
@ehmadzubair  @sheralim012 thank you for looking into these options.

Ideally this functionality would be part of standard Wagtail - I think we should reach out to Torchbox at the beginning of next week and see whether they have any additional insights or ideas on how we could align our approach with future Wagtail versions.

**Comment by isedwards** [comment]
I've not had a reply from Torchbox. Digging deeper I don't think Wagtail can fully solve this without contributing changes to the approach Django itself takes to multi-site.

Before heading down this rabbit hole, I think we should review the benefits that we're anticipating getting from multi-site and consider the implications for deploying v2.0 in single site mode.

@dannyparsons - is the only benefit of multi-site the built-in ability to copy pages/sections to other sites or has anything else been identified?

**Comment by dannyparsons** [comment]
I think the other main benefit would be that it simplifies the processes for global admins who manage all sites i.e. having a single login and central place to manage all sites. I don't think this should be the determining factor though. But if we can get a workable multi-site even if it's not perfect, I think this would be highly appreciated.

**Comment by dannyparsons** [comment]
This has now been discussed further and there is agreement that the short term option is to continue with single site installations. The potential benefits of a multi-tenant site don't outweigh the current limitations in core Wagtail and potential problems and instability that may come from developing and maintaining a lot of custom code to implement this for all features.

The multi-tenant option may be a suitable longer term solution and this can be revisited beyond v2. Continuing with single sites is also a viable long term solution with external infrastructure developed to connect the single sites that could implement multi-tenant-like experiences e.g. single sign on.

@ehmadzubair and @sheralim012 thank you for your investigation of these options, it was very helpful in the decision making process.
