### ISSUE TITLE
After migration, phantom page which is/isn't accessible

### ISSUE THREAD

**Issue by cbunicef** [unicef/iogt#901]
Found when testing site pre-cache/offline access.

This URL 

https://global.iogt.site/ar/sections/arabic-emergency-information/arabic-translation-of-about-coronavirus-1/arabic-translation-of-about-coronavirus/arabic-translation-of-what-else-do-you-want-to-know-about-coronavirus/ 

breaks pre-cache because it isn't accessible.

![image](https://user-images.githubusercontent.com/30042226/146065029-158cbd39-bb42-4ad1-bfac-12a00c188ffc.png)

But, it does appear in /sitemap/

![image](https://user-images.githubusercontent.com/30042226/146065094-562721cd-e1f5-4e33-8869-73d972d67a90.png)

It isn't accessible in Admin Panel https://global.iogt.site/admin/pages/175/ (should be accessible as a child page of this Page)

![image](https://user-images.githubusercontent.com/30042226/146065271-50a25da4-05d1-48e1-b698-b31167348e7b.png)

When unpublishing the parent page, there is a prompt to unpublish the child page

![image](https://user-images.githubusercontent.com/30042226/146065414-ec22f020-028c-442f-a2cb-b219eb4f5adc.png)

![image](https://user-images.githubusercontent.com/30042226/146065439-10c9f5f6-d6bb-469d-975c-02fa711810cd.png)

Once the parent Page is unpublished the Child Page disappears from the /sitemap/

![image](https://user-images.githubusercontent.com/30042226/146065695-5059f6ca-8664-4f90-bb23-171634cb9b05.png)

**Comment by geoo89** [comment]
It appears that the page does exist: https://global.iogt.site/admin/pages/1199/edit/
It can be reached by going to the English version, then changing the language to Arabic. It's also possible to preview it, and it looks sensible.

It seems that the parent page is unaware of its child page.
For the English version, everything seems fine.

Not sure at this point what could cause it.

**Comment by sheralim012** [comment]
@geoo89  invalid paths for pages could be the reason for this and wagtail management command `fixtree` seems to fix the issue
