### ISSUE TITLE
During migration, translations of pages don't always retain images in content blocks

### ISSUE THREAD

**Issue by cbunicef** [unicef/iogt#926]
V1: https://ke.goodinternet.org/sections/emergency-information/covid-19-parenting/swahili-translation-of-read-to-your-child-about-covid-19/
https://ke.goodinternet.org/admin/pages/869/edit/

V2: cannot load due to 504 errors
https://ke.iogt.site/admin/pages/397/edit/

As a result the V2 page cannot be edited due to empty image content blocks, and possibly this causes 504 errors?

**Comment by sheralim012** [comment]
- I ran the content migration and all the images were successfully attached
- even without the attached image (empty image block) the page was rendering without any error (simulated by giving wrong path to load_v1_db command)

am I missing something?

**Comment by geoo89** [comment]
I ran the migration locally, and the images do appear. This seems to be a deployment issue @istride

**Comment by cbunicef** [comment]
The desired full-width size would be the same as the article image size. Keep in mind we just discussed limiting the width of the content column in multi-column view.

**Comment by geoo89** [comment]
We re-migrated the KE site into sandbox with more RAM, and for the page in question the images do appear now in the admin panel: https://sandbox.iogt.site/admin/pages/397/edit/
