### ISSUE TITLE
During migration, URLs for media files are messy

### ISSUE THREAD

**Issue by cbunicef** [unicef/iogt#931]
For example:

https://global.iogt.site/media/media/media-v1/global/media/media/UNICEF_tackles_cyberbullying_compressed.mp4

**Comment by geoo89** [comment]
To clarify, this is only for media, but not for images.
It appears to affect other sites, not only global.

**Comment by istride** [comment]
Some context on how the migration is being done at the moment. The media files from a version 1 site are unpacked into the app root directory, alongside the version 2 media directory.

```
/app
    /media-v1
        /documents
        /images
        /media
            /example_video.mp4
        etc...
    /media
```

The expectation is for files to be transferred from `/app/media-v1` to `/app/media` during the course of the migration. With the conditions above, the migration script is kicked off with the `media-dir` argument set to `media-v1`.

```
python manage.py load_v1_db --media-dir media-v1
```

This results in the example video file, above, being transferred with the full path from the `media-v1` directory.

```
# actual
/app/media/media/media-v1/media/example_video.mp4

# desired
/app/media/media/example_video.mp4
```

I think it may only be possible to achieve this by modifying the migration script to change the location that the media files get uploaded to.
