### ISSUE TITLE
All current HTTP errors in migrated sites

### ISSUE THREAD

**Issue by cbunicef** [unicef/iogt#943]
| URL | Error|
| ---- | ---- |
| https://mz.iogt.site/en/external-link/?next=http%3A%2F%2Fwww.un.org%2Fsustainabledevelopment%2Ftakeaction%2F&from=/en/sections/objectivos-de-desenvolvimento-sustent%C3%A1vel/porqu%C3%AA-deves-salvar-o-mundo/engage-se-com-os-objectivos-de-desenvolvimento-sustent%C3%A1vel-ods/ | 404 |
| https://rw.iogt.site/rw/sections/kinyarwanda-translation-of-youth-zone-1/kinyarwanda-translation-of-your-health/ | 404 |
| https://rw.iogt.site/rw/sections/ubuzima-bwawe/kinyarwanda-translation-of-mental-health/ | 404 |
| https://rw.iogt.site/en/sections/youth-zone/youth-toolkit/be-safe-be-kind/ | 404 |
| https://ss.iogt.site/en/sections/emergency-information/covid-19-parenting/covid-19-parenting-survey/ | 404 |
| https://ke.iogt.site/admin/images/463/ | 504 |
| https://ke.iogt.site/sw/footers/chukua-uchunguzi-wa-haraka/ | 500 |
| https://ke.iogt.site/sw/sections/swahili-translation-of-gen2030-act-for-climate/climate-change/ | 404 |
| https://ke.iogt.site/en/sections/generationunlimited-future-yours/ | 404 |
| https://ke.iogt.site/sw/sections/swahili-translation-of-emergency-information/swahili-translation-of-covid-19-parenting/swahili-translation-of-read-to-your-child-about-covid-19/ | 404 |
| https://ke.iogt.site/sw/sections/swahili-translation-of-gen2030-act-for-climate/climate-change/green-activities/ | 404 |
| https://ke.iogt.site/sw/sections/swahili-translation-of-gen2030-act-for-climate/swahili-translation-of-all-in/swahili-translation-of-about-all-in/ | 404
| https://ke.iogt.site/sw/sections/swahili-translation-of-gen2030-act-for-climate/climate-change/swahili-translation-of-climate-change-impacts-children/swahili-translation-of-cleaner-energy-means-a-healthier-environment/ | 404 |
| https://ke.iogt.site/en/sections/generationunlimited-future-yours/help-change-world/plan-and-run-survey/ | 404 |
| https://ke.iogt.site/en/sections/generationunlimited-future-yours/help-change-world/whats-your-style/ | 404 |
| https://ke.iogt.site/sw/sections/swahili-translation-of-gen2030-act-for-climate/swahili-translation-of-all-in/swahili-translation-of-about-all-in/mapenzi-mahusiano-ngono-vvu-na-maswali-mengine-magumu/ | 404 |
| https://rw.iogt.site/admin/pages/121/edit/ | 500 |
| https://rw.iogt.site/rw/sections/kinyarwanda-translation-of-youth-zone-1/kinyarwanda-translation-of-your-health/ | 404 |
| https://rw.iogt.site/rw/sections/ubuzima-bwawe/kinyarwanda-translation-of-mental-health/ | 404 |
| https://rw.iogt.site/en/sections/youth-zone/youth-toolkit/be-safe-be-kind/ | 404 |
| https://ss.iogt.site/en/sections/emergency-information/covid-19-parenting/covid-19-parenting-survey/ | 404 |
| https://global.iogt.site/ar/sections/arabic-emergency-information/arabic-translation-of-covid-19-parenting/arabic-translation-of-read-to-your-child-about-covid-19/ | 404 |
| https://global.iogt.site/admin/images/491/ | 504 |
| https://global.iogt.site/pt/sections/parents-caregivers/ | 404 |
| https://global.iogt.site/en/footers/take-a-quick-survey/ | 500 |
| https://global.iogt.site/pt/sections/portuguese-translation-of-coronavirus-covid-19/ | 404 |
....

Partial list, some of these are also in V1. A better list is coming soon.

**Comment by geoo89** [comment]
Most (possibly all?) of the 404s in this list seem to be pages which are in draft state.
Example: https://rw.iogt.site/rw/sections/kinyarwanda-translation-of-youth-zone-1/kinyarwanda-translation-of-your-health/

Some of them are PageLinkPage footers which I guess are occur when oressing "Live" in the CMS, but the user-facing links are fine (I believe we already have an issue about this).
Example: https://global.iogt.site/en/footers/take-a-quick-survey/

The first link in the table works fine for me.


The 504 we need to sort (Ian is working on that), and https://rw.iogt.site/admin/pages/121/edit/ is an interesting one, it looks like there is malformed HTML in a content block. How does this behave in V1 and when viewing the site live?

**Comment by geoo89** [comment]
I'm closing this as I believe all of the instances have been classified (see previous comment), and I split the only remaining one into a separate issue: #1014
