### ISSUE TITLE
Less strict registration survey

### ISSUE THREAD

**Issue by geoo89** [unicef/iogt#944]
On the MZ site, the registration survey consists of the optional field "Date of birth". In V1, it is presented on a separate page, no submission of that data is needed to access IoGT. In V2, the form has to be submitted (even if the field is left blank). This is too strict. Note: On most other V1 sites, registration is a one-step process where the registration survey questions are displayed on the same page as the name/password field.

Two possible solutions for V2:

- One-step process: Show the registration survey embedded on the same page as the other registration forms (name, displayname, password).
- Two-step process: Keep everything as it is, with two exceptions:
    - Users are initially directed to, but do not have to submit the registration survey if it only contains optional questions (i.e. if you are in the registration survey, and you click a link to some other page, you will NOT be redirected to the survey, but are free to browse the site)
    - If the registration survey contains required questions, and the user clicks a link to some other page, they do get redirected to the survey (as currently happens), but additional red text appears stating "Please complete the questions marked as required to continue"

Also see https://github.com/unicef/iogt/issues/899#issuecomment-994780752

**Comment by cbunicef** [comment]
Please move forward with solution 1.

**Comment by geoo89** [comment]
@cbunicef We allow certain user groups to re-do the registration survey, though we haven't used this in any of the existing migrations. If we use this in some future migration, what should we display once such a user logs in? Should they be forced onto the registration survey site before being able to do anything else? What if it only contains optional questions?

**Comment by ehmadzubair** [comment]
@geoo89 can we catch up on this sometime?

**Comment by geoo89** [comment]
After discussing, let's move ahead with solution 2 instead, as solution 1 is difficult to implement.
