### ISSUE TITLE
Bypassing external link page in footers

### ISSUE THREAD

**Issue by geoo89** [unicef/iogt#976]
Example from MZ: When I visit http://localhost:8000/pt/external-link/... (due to clicking on some external link), external footer links become direct links:

![image](https://user-images.githubusercontent.com/678199/148737068-eb2ed6ac-0f24-44ba-890d-201a23d1e091.png)

Usually, the footer links _Visita o website do UNICEF_ and _Segue o UNICEF no Facebook_ lead me to the external link redirect page. In this case however, they lead directly to the respective site.

**Comment by sheralim012** [comment]
@geoo89 the reason external link conversion doesn't work on the "transition page" is to avoid conversion of "Continue to external site"  to another external link (loop).
