### ISSUE TITLE
Formatting of "back" button is inconsistent across confirmation pages of data collection tools (polls, quizzes, surveys)

### ISSUE THREAD

**Issue by lauriemarkle** [unicef/iogt#981]
![image](https://user-images.githubusercontent.com/74552270/148780406-2aa92317-1892-4025-9d8d-591e3ac2b79a.png)
**On surveys:** back button appears as large back button at bottom of page, returns user to the full survey page rather than referred article/page

![image](https://user-images.githubusercontent.com/74552270/148780694-21c5d751-83f6-43da-88ba-150794329eb5.png)
**On polls:** back button is in top left corner, returns user to article

![image](https://user-images.githubusercontent.com/74552270/148780870-0c34583a-a7e6-4234-984d-28e15f87e756.png)
**On quiz:** back button is embedded in the middle of survey results as a white button. It takes the user back to the article. 

**Poll is the preferred format for all data collection forms**

**Comment by geoo89** [comment]
The design inconsistency is captured in #489. Also see related discussion here: #359

The issue with the behavior of the back button is captured in #355 and #479 and is non-trivial to fix.

**Comment by geoo89** [comment]
Resolution:
consistent buttons for all questionnaires as follows:
- Back (white on black) on the right
- Replay quiz (quiz)/Go to Homepage (poll, survey) on the left (black on white)

**Comment by geoo89** [comment]
@sheralim012 @ehmadzubair Updated the last comment with full specification. Back button stays on the right for now.
