### ISSUE TITLE
Question counter in surveys/quizzes does not work

### ISSUE THREAD

**Issue by lauriemarkle** [unicef/iogt#982]
When completing embedded surveys/quizzes with more than 2 questions, the survey continues to read “question 2 of 10” regardless of total number of questions completed.

![image](https://user-images.githubusercontent.com/74552270/148782843-3a78a3fa-3b59-4bd3-9a43-fb141e21be3e.png)

**Comment by cbunicef** [comment]
Possibly same as #753

**Comment by geoo89** [comment]
The question counter is implemented very badly, and the only sensible fix is a major refactor, see #529 and #866

**Comment by cbunicef** [comment]
Thanks Georg. Maybe we will have to hide this counter for the time being? Let's discuss today.

**Comment by geoo89** [comment]
Resolution: Temp fix - hide the counter.
