### ISSUE TITLE
When features are embedded in a page and then unpublished, the page where they are embedded should load without the embedded content

### ISSUE THREAD

**Issue by lauriemarkle** [unicef/iogt#985]
Currently, if a page is created with an embedded poll and then published, but then the poll is later unpublished, the page where the poll is embedded will not load (front end users receive an error syntax page). Ideally, in this scenario, the page will still load, but without the unpublished poll and the CMS editor will not be able to republish or resave the page without deleting the poll widget component from page content.

**Comment by cbunicef** [comment]
Applies also to embedded polls that are deleted.

Does this happen with Page Buttons as well? Any other new content block elements?

**Comment by cbunicef** [comment]
Prioritizing this as it affects the homepage, eg if you delete a Page which is promoted on the homepage then the homepage breaks.

This is very different behavior to V1 where you can delete content and it disappears from the homepage without issue.

**Comment by geoo89** [comment]
We should handle this gracefully both when pages are deleted and unpublished. I assume in that case the respective element should simply not be rendered for now. We can make a separate issue about warnings to display on the CMS side.

Can we a compile a complete list of instances?
- questionnaires in articles
- featured content in homepage
- featured content in section
- recommended content in articles
- page buttons?
- ...

**Comment by cbunicef** [comment]
Organized slightly differently

**Content blocks used in all Page types**
- Page button
- Embedded survey/poll/quiz
- Article (in Homepage)
- Image
- Media

**Paragraph Content Block functions**
- Media
- Link (link text seems dependent on the linked asset)
- Document
- Image

**Article Page**
- Recommended content

**Homepage Page**
- Banners

**Page Link Page**
- Destination Page

**Section Page**
- Featured content

**All Page Types**
- Icon

I think this is all the locations where a Page relies on assets outside the Page. These are not necessarily all causing the problem.

Do you need us to manually confirm which of these currently cause problems, or will you build a solution that addresses all?
