### ISSUE TITLE
Slight misalignment of Page Link Page titles on Section Page

### ISSUE THREAD

**Issue by cbunicef** [unicef/iogt#986]
![image](https://user-images.githubusercontent.com/30042226/148990369-b2d348fd-e3b9-417a-82cb-2ea885fb4cdd.png)

Visible here: https://global.iogt.site/en/sections/youth/your-health/sexual-health/

**Comment by geoo89** [comment]
Might be worthwhile to check if #1031 is related and can be fixed in the same go.
