### ISSUE TITLE
Error when loading top-level Section

### ISSUE THREAD

**Issue by cbunicef** [unicef/iogt#998]
https://global.iogt.site/en/sections/youth/

The most recent change was adjusting section title from "Youth" to "Youth - DRAFT".

Then the error appeared, possibly over the weekend.

I've changed the title back to "Youth" but the error is still there.

**Comment by geoo89** [comment]
The issue is that a HomePage was added as a child of this section. I marked it as draft for now to fix the error.

I'm not quite sure why it's possible to as home pages as children of a section. This should probably be disabled?

**Comment by cbunicef** [comment]
Thanks very much for the quick attention @geoo89.

I think there is definitely value in using a Home Page format outside of the homepage itself, but this isn't a priority. I'll create a separate issue for this.
